CARDS = [
 {"f":"Equity investor versus debt investor: who is owner, who is lender?","b":"Equity investor = <b>owner</b>, gets residual profit, has a say in management. Debt investor = <b>lender</b>, gets fixed interest and principal back, no say."},
 {"f":"Face value","b":"The nominal price of a share. Share capital = number of shares &times; face value."},
 {"f":"What changes face value?","b":"Only a <b>split</b> (face value falls) or a <b>consolidation</b> (face value rises)."},
 {"f":"A 30% dividend on a Rs 2 face value share is how much?","b":"<b>Rs 0.60</b>. Dividend % is always on face value."},
 {"f":"Book value per share","b":"Net worth (equity capital + reserves) &divide; shares outstanding. What each share would get, in theory, if the company were wound up."},
 {"f":"Replacement value","b":"What it would cost today to set up a new company with the same plants and infrastructure."},
 {"f":"Intrinsic value","b":"The present value of expected free cash flows. Buffett: \"the discounted value of the cash that can be taken out of a business during its remaining life\"."},
 {"f":"Intrinsic value is above market price. The share is...","b":"<b>Undervalued.</b> Below market price = overvalued."},
 {"f":"Market capitalisation","b":"Market price per share &times; number of shares outstanding (issued, subscribed and fully paid up)."},
 {"f":"Large, mid, small cap: the book's rule of thumb","b":"No fixed cut-off. Commonly: top <b>50 to 100</b> by market cap = large; next <b>200 to 500</b> = mid; the rest = small."},
 {"f":"Which ratio shows the size of a country's stock market?","b":"<b>Market cap to GDP.</b>"},
 {"f":"Enterprise value (standalone)","b":"Market value of equity + preferred capital + debt &minus; cash and equivalents &minus; non-operating financial investments."},
 {"f":"No fair value available for bank debt or unlisted preference shares. What does the analyst use in EV?","b":"The <b>balance sheet value</b> as a proxy."},
 {"f":"EBIT versus EBITDA","b":"EBIT: before interest and taxes. EBITDA: also before depreciation and amortisation."},
 {"f":"Historical, trailing, forward earnings","b":"Historical: past years. Trailing: most recent period, rolling (TTM = trailing twelve months). Forward: projected."},
 {"f":"EPS","b":"Net profit &divide; shares outstanding (strictly, the time-weighted average)."},
 {"f":"Dividend payout ratio","b":"<b>DPS &divide; EPS.</b>"},
 {"f":"P/E ratio","b":"Market price &divide; EPS. What the market pays for Rs 1 of earnings. \"12x\" = 12 times earnings."},
 {"f":"Why is forward P/E often lower than current P/E?","b":"Same price, but divided by <b>higher expected future earnings</b>."},
 {"f":"P/S ratio: formula and best use","b":"Price &divide; sales per share, or market cap &divide; annual net sales. Useful when a company is <b>making losses</b>."},
 {"f":"P/BV: best and worst use","b":"Best for <b>banks and financial institutions</b> and when earnings are negative. Not relevant for <b>services</b> firms with few assets."},
 {"f":"DVR share","b":"Like a normal share but with <b>less than 1 vote</b> per share. Trades at a discount. Examples: Tata Motors, Pantaloons."},
 {"f":"DVR eligibility under the Companies Act, 2013","b":"Dividend of at least <b>10%</b> over the preceding <b>3 years</b>. DVRs at most <b>25%</b> of total post-issue paid-up capital."},
 {"f":"Secured versus unsecured debt","b":"Secured: lenders can have the company's assets sold if it defaults. Unsecured: no such right."},
 {"f":"Debt issued to the public must be...","b":"<b>Listed</b> on a stock exchange. Unlisted debt is held to maturity or traded OTC."},
 {"f":"Coupon rate","b":"Fixed yearly payment as a % of <b>face value</b>. The book advises not to call it the interest rate."},
 {"f":"8.24GS2018, face value Rs 1,000: coupon per payment?","b":"Rs 82.40 a year, paid half-yearly: <b>Rs 41.20</b> every 6 months."},
 {"f":"T-bill tenors","b":"<b>91, 182 and 364 days.</b>"},
 {"f":"Single largest factor behind bond price changes","b":"<b>Maturity.</b>"},
 {"f":"Market interest rates rise. Bond prices?","b":"<b>Fall.</b> Prices and rates move inversely."},
 {"f":"Holding period return","b":"(Coupons + reinvestment income + price gain) &divide; purchase price. Crude: ignores compounding."},
 {"f":"Current yield","b":"Coupon &divide; market price. Ignores future cash flows. Like dividend yield."},
 {"f":"YTM","b":"The rate equating present value of all future cash flows to today's price. The bond's <b>IRR</b>. Excel: XIRR."},
 {"f":"Two assumptions of YTM","b":"Held to <b>maturity</b>; coupons <b>reinvested at the same rate</b> (flat, static yield curve)."},
 {"f":"Realised yield","b":"Annualised return, with compounding, when a bond is sold before maturity."},
 {"f":"Macaulay versus modified duration","b":"Macaulay: weighted average time to get your money back. Modified = Macaulay &divide; (1 + y): price sensitivity to rates."},
 {"f":"What raises duration?","b":"Longer maturity, lower coupon, lower yield."},
 {"f":"Zero coupon bond","b":"No coupon. Issued at a <b>discount</b>, redeemed at <b>par</b>. Higher duration than a coupon bond of the same maturity."},
 {"f":"Money market instruments","b":"Debt under 1 year: T-bills (government), CPs (companies), CDs (banks and FIs). All short-term zeroes."},
 {"f":"Deep discount bond examples","b":"An old <b>IDBI</b> issue and <b>Kisan Vikas Patra</b>."},
 {"f":"Floating rate bond","b":"Coupon reset to a benchmark, typically every 6 months. Lower rate risk. Limits: <b>cap</b> (max) and <b>floor</b> (min)."},
 {"f":"Inverse floater","b":"Coupon moves <b>opposite</b> to the benchmark. Found in developed markets."},
 {"f":"Convertible bond: gain and cost for the issuer","b":"Gain: <b>lower coupon</b>, no repayment. Cost: <b>dilution</b>, EPS falls."},
 {"f":"Principal protected note","b":"Part in debt that grows back to principal, rest in equity, derivatives or commodities. Still has <b>issuer credit risk</b>. NBFC versions: ELBs, CLBs."},
 {"f":"Inflation Indexed Bonds: index used?","b":"<b>WPI</b> (as per the book). Fixed real coupon on inflation-adjusted principal."},
 {"f":"Inflation Indexed National Saving Securities, Cumulative 2013","b":"Retail. 10 years. Fixed <b>1.5%</b> + <b>CPI</b> inflation, compounded half-yearly, paid at maturity."},
 {"f":"Foreign currency bond: who carries currency risk?","b":"The <b>issuer</b>. Example: Delhi International Airport USD bonds, February 2020."},
 {"f":"AT1 perpetual bonds: five features","b":"No maturity; rank below deposits and all other bonds; coupon only from distributable profits; coupon <b>non-cumulative</b>; convertible to equity on a trigger event."},
 {"f":"Basis","b":"<b>Spot price &minus; futures price.</b>"},
 {"f":"Contango versus backwardation","b":"Contango: futures <b>above</b> spot. Backwardation: futures <b>below</b> spot."},
 {"f":"Cost of carry includes...","b":"Storage, insurance, transportation, financing and other costs of holding until delivery."},
 {"f":"Gold spot Rs 1,02,000, carry 8% a year: 3-month futures fair value?","b":"1,02,000 + 1,02,000 &times; 8% &times; 3/12 = <b>Rs 1,04,040</b>."},
]

MCQS = [
 {"id":"3.1","q":"A bond is issued at a face value of Rs 100 and a coupon of 10% p.a. The interest rates in the market have increased subsequently. This bond is likely to quote:","o":["At a price below face value","At a price above face value","At the face value","At a price the issuer announces"],"a":0,"w":"Book sample question. Bond prices move opposite to interest rates. A 10% coupon is less attractive when market rates are higher, so the price falls below face value."},
 {"id":"3.2","q":"Calculate the Enterprise Value (standalone basis): Market capitalisation = 10 lakhs; Total debt = 3 lakhs; Cash = 4 lakhs.","o":["9 lakhs","11 lakhs","13 lakhs","6 lakhs"],"a":0,"w":"Book sample question. EV = 10 + 3 &minus; 4 = 9 lakhs. Cash is subtracted."},
 {"id":"3.3","q":"A company has 5 lakh shares of face value Rs 10 each. Its equity share capital is:","o":["Rs 50 lakh","Rs 5 lakh","Rs 10 lakh","It depends on the market price"],"a":0,"w":"Share capital = number of shares &times; face value = 5 lakh &times; 10 = Rs 50 lakh."},
 {"id":"3.4","q":"A company with face value Rs 5 declares a 25% dividend. The dividend per share is:","o":["Rs 1.25","Rs 0.25","Rs 2.50","25% of the market price"],"a":0,"w":"Dividend % is reckoned on face value: 25% &times; 5 = Rs 1.25."},
 {"id":"3.5","q":"An investor holds 10 shares of face value Rs 10. The company splits each share into 5. After the split the investor holds:","o":["50 shares of face value Rs 2","2 shares of face value Rs 50","10 shares of face value Rs 2","50 shares of face value Rs 10"],"a":0,"w":"A split multiplies the shares and divides the face value by the same number."},
 {"id":"3.6","q":"Face value of a share increases when the company:","o":["Consolidates its shares","Splits its shares","Declares a dividend","Issues shares at a premium"],"a":0,"w":"Consolidation merges shares, so face value rises. A split does the opposite."},
 {"id":"3.7","q":"______ refers to what it would cost a new company today to set up the same infrastructure and plants as an existing company.","o":["Replacement value","Book value","Intrinsic value","Market value"],"a":0,"w":"That is the book's definition of replacement value."},
 {"id":"3.8","q":"If the intrinsic value of a share is perceived to be more than its market price, the share is said to be:","o":["Undervalued","Overvalued","Fairly valued","At par"],"a":0,"w":"Intrinsic value above price means the market is underpricing it: undervalued."},
 {"id":"3.9","q":"Intrinsic value of an asset is best described as:","o":["The present value of expected free cash flows from the asset","Net worth divided by the number of shares","The price at which the share trades on the exchange","The nominal value printed on the share"],"a":0,"w":"The other options describe book value, market value and face value."},
 {"id":"3.10","q":"Which statement about classifying stocks as large, mid and small cap is correct as per the book?","o":["There is no specific size cut-off; the ranking floats with the market and period","Large cap means market cap above Rs 1 lakh crore","Mid cap means the top 100 stocks","Small cap stocks enjoy the highest liquidity"],"a":0,"w":"The book says there is no specific cut-off and gives only a common rule of thumb. Small caps have low liquidity."},
 {"id":"3.11","q":"The ratio of a country's total market capitalisation to its ______ indicates the size and importance of its stock market.","o":["GDP","Population","Foreign exchange reserves","Fiscal deficit"],"a":0,"w":"The book names market cap to GDP."},
 {"id":"3.12","q":"Market cap Rs 500 crore; debt Rs 200 crore; preferred capital Rs 50 crore; cash Rs 80 crore; non-operating investments Rs 20 crore. Standalone EV is:","o":["Rs 650 crore","Rs 850 crore","Rs 750 crore","Rs 550 crore"],"a":0,"w":"500 + 200 + 50 &minus; 80 &minus; 20 = 650."},
 {"id":"3.13","q":"When calculating EV, if the fair market value of bank debt is not available, the analyst may use:","o":["The balance sheet value as a proxy","Zero","The face value of equity","The market capitalisation"],"a":0,"w":"The book allows balance sheet values when fair value cannot be determined."},
 {"id":"3.14","q":"Earnings for the immediately preceding 12 months, calculated on a rolling basis, are called:","o":["Trailing twelve months (TTM) earnings","Forward earnings","Historical earnings","Projected earnings"],"a":0,"w":"TTM is the popular form of trailing earnings. Forward earnings are projections."},
 {"id":"3.15","q":"______ is the earning available to recover capital invested in tangible and intangible assets, and later to be shared among lenders, government and owners.","o":["EBITDA","Net profit","EBIT","EPS"],"a":0,"w":"EBITDA is before depreciation and amortisation, so it includes the amount that recovers asset costs."},
 {"id":"3.16","q":"Net profit Rs 10 lakh; shares outstanding 2 lakh; market price Rs 60. What is the P/E ratio?","o":["12x","5x","20x","6x"],"a":0,"w":"EPS = 10 lakh &divide; 2 lakh = Rs 5. P/E = 60 &divide; 5 = 12."},
 {"id":"3.17","q":"Dividend per share divided by earnings per share is known as:","o":["Dividend payout ratio","Dividend yield","Earnings yield","Retention ratio"],"a":0,"w":"The book defines DPS &divide; EPS as the dividend payout ratio."},
 {"id":"3.18","q":"A share trades at 20 times this year's earnings but 15 times next year's expected earnings. This suggests:","o":["EPS is expected to grow","EPS is expected to fall","The share price is expected to fall","The P/E calculation is wrong"],"a":0,"w":"Same price, lower forward P/E: next year's earnings are expected to be higher."},
 {"id":"3.19","q":"Market cap Rs 400 crore; annual net sales Rs 200 crore. The P/S ratio is:","o":["2","0.5","200","4"],"a":0,"w":"P/S = market cap &divide; annual net sales = 400 &divide; 200 = 2."},
 {"id":"3.20","q":"For a company that is temporarily making losses, which multiple does the book say is especially useful?","o":["Price to sales","Price to earnings","Dividend payout ratio","Earnings per share"],"a":0,"w":"With losses, earnings-based multiples are meaningless. P/S still works."},
 {"id":"3.21","q":"P/BV is considered a good measure for valuing which type of company?","o":["Banks and financial institutions","Software services firms","Consulting firms","All of the above"],"a":0,"w":"Banks carry mostly monetary assets valued near market prices. The book says P/BV may not be relevant for services firms with limited assets."},
 {"id":"3.22","q":"Which statement about a stock with P/BV below 1 is correct?","o":["It may not be a bargain; past poor investments may still need to be written down","It is always undervalued and should be bought","It means the company has no debt","It means the market price is above book value"],"a":0,"w":"The book warns that not all stocks trading below book value are bargains."},
 {"id":"3.23","q":"Which of the following is NOT true of DVR shares?","o":["They carry more voting rights than ordinary shares","They carry less than one vote per share","They usually trade at a discount to ordinary shares","They let companies raise capital without diluting voting control"],"a":0,"w":"DVRs carry fewer votes, not more."},
 {"id":"3.24","q":"Under the Companies Act, 2013, DVR shares cannot exceed ______ of the total post-issue paid-up capital.","o":["25%","10%","49%","74%"],"a":0,"w":"25%. The 10% figure is the dividend record needed over the preceding 3 years."},
 {"id":"3.25","q":"A 7.5% bond with face value Rs 1,000 pays coupons half-yearly. Each coupon payment is:","o":["Rs 37.50","Rs 75","Rs 7.50","Rs 3.75"],"a":0,"w":"Yearly coupon = 1,000 &times; 7.5% = 75. Half-yearly = 37.50."},
 {"id":"3.26","q":"According to the book, the single largest factor contributing to changes in bond prices is:","o":["Maturity","Face value","Credit rating agency","Issue size"],"a":0,"w":"The book says maturity is the single largest factor and the market risk in bonds is linked to it."},
 {"id":"3.27","q":"Irrespective of the price at which a bond is bought in the secondary market, on maturity the issuer repays:","o":["The face value (principal)","The investor's purchase price","The last traded market price","The average market price over its life"],"a":0,"w":"The issuer is liable only for the principal, represented by face value."},
 {"id":"3.28","q":"A bond is bought at Rs 200. It pays a coupon of Rs 16, which is reinvested at 10% for the year. It is sold at Rs 210 after one year. The holding period return is:","o":["13.8%","13.0%","8.0%","5.0%"],"a":0,"w":"(16 + 1.6 + 10) &divide; 200 = 27.6 &divide; 200 = 13.8%."},
 {"id":"3.29","q":"A bond with face value Rs 100 and a 9% coupon trades at Rs 90. Its current yield is:","o":["10%","9%","8.1%","11%"],"a":0,"w":"Current yield = coupon &divide; market price = 9 &divide; 90 = 10%."},
 {"id":"3.30","q":"The biggest drawback of current yield as a measure of bond return is that it:","o":["Does not consider future cash flows from the bond","Is too hard to calculate","Uses face value instead of price","Assumes the bond is held to maturity"],"a":0,"w":"The book names ignoring future cash flows as the biggest drawback. Holding to maturity is an assumption of YTM."},
 {"id":"3.31","q":"Yield to maturity can also be understood as:","o":["The internal rate of return (IRR) of the bond","The coupon divided by face value","The holding period return","The current yield plus inflation"],"a":0,"w":"YTM equates present value of all cash flows to price: that is the IRR. Excel's XIRR can compute it."},
 {"id":"3.32","q":"Which of the following is an assumption of YTM?","o":["Coupons are reinvested at the same rate for the remaining tenor","The bond is sold before maturity","Interest rates will rise every year","The bond pays no coupon"],"a":0,"w":"YTM assumes holding to maturity and reinvesting at the same rate, implying a flat and static yield curve."},
 {"id":"3.33","q":"A bond has a Macaulay duration of 5 years and a YTM of 8%. Its modified duration is about:","o":["4.63","5.40","5.00","3.70"],"a":0,"w":"Modified duration = 5 &divide; 1.08 = 4.63."},
 {"id":"3.34","q":"With all other features the same, which bond has the highest duration?","o":["Long maturity, low coupon, low yield","Short maturity, high coupon, high yield","Long maturity, high coupon, high yield","Short maturity, low coupon, high yield"],"a":0,"w":"Duration rises with longer maturity, lower coupon and lower yield."},
 {"id":"3.35","q":"Zero coupon bonds are:","o":["Issued at a discount and redeemed at par","Issued at par and redeemed at a premium","Issued at a premium and redeemed at par","Bonds that pay a coupon of zero after conversion"],"a":0,"w":"The return on a zero is the gap between issue price and redemption value."},
 {"id":"3.36","q":"Compared with a coupon-paying bond of the same maturity, a zero coupon bond has:","o":["Higher interest rate risk","Lower interest rate risk","No interest rate risk","The same duration"],"a":0,"w":"Zeroes have higher duration, so more rate risk."},
 {"id":"3.37","q":"Treasury bills, commercial papers and certificates of deposit are examples of:","o":["Short-term zero coupon (money market) instruments","Perpetual bonds","Floating rate bonds","Inflation indexed bonds"],"a":0,"w":"All are under one year and issued at a discount. The money market is the segment for securities under one year."},
 {"id":"3.38","q":"The maximum and minimum limits on the coupon of a floating rate bond are called:","o":["Cap and floor","Call and put","Ceiling and base","Premium and discount"],"a":0,"w":"The book uses cap (maximum) and floor (minimum)."},
 {"id":"3.39","q":"Floating rate bonds are especially useful to investors when:","o":["Interest rates are rising","Interest rates are falling","Inflation is zero","The issuer has no credit rating"],"a":0,"w":"The coupon resets upward with market rates, and price risk is low."},
 {"id":"3.40","q":"Which is NOT an advantage of convertible bonds to the issuer?","o":["Existing shareholders are not diluted","Lower coupon than plain debt","No repayment needed for the converted portion","Investors accept lower coupon for possible share gains"],"a":0,"w":"Conversion issues new shares, so existing holders are diluted and EPS falls. That is the disadvantage."},
 {"id":"3.41","q":"Which statement about principal protected notes is correct?","o":["Investors remain exposed to the issuer's credit risk","They are free of all risk","They invest only in government securities","They are equity shares with a guaranteed dividend"],"a":0,"w":"The book stresses that principal protection does not mean absence of credit risk."},
 {"id":"3.42","q":"As per the book, Inflation Indexed Bonds issued by the RBI use which index for the index ratio?","o":["Wholesale Price Index (WPI)","Consumer Price Index (CPI)","Nifty 50","Index of Industrial Production"],"a":0,"w":"WPI for IIBs. The retail Inflation Indexed National Saving Securities 2013 use CPI."},
 {"id":"3.43","q":"An Indian company issues USD bonds. If the USD appreciates against the rupee:","o":["The issuer needs more rupees to repay","The investor loses in dollar terms","The coupon rate automatically falls","Nothing changes for the issuer"],"a":0,"w":"With foreign currency bonds, the issuer carries the currency risk."},
 {"id":"3.44","q":"Which of the following is NOT a feature of AT1 perpetual bonds issued by banks?","o":["Unpaid coupons accumulate and are paid later","No fixed maturity date","Coupon paid only from distributable profits","May be converted into equity on a pre-specified event"],"a":0,"w":"AT1 coupons are non-cumulative. A missed coupon is lost."},
 {"id":"3.45","q":"Basis in the commodity market is defined as:","o":["Spot price minus futures price","Futures price minus spot price","Futures price minus cost of carry","Spot price plus cost of carry"],"a":0,"w":"Basis = spot &minus; futures."},
 {"id":"3.46","q":"When the futures price of a commodity is higher than its spot price, the market is said to be in:","o":["Contango","Backwardation","Arbitrage","Delivery"],"a":0,"w":"Futures above spot is contango. Futures below spot is backwardation."},
 {"id":"3.47","q":"Gold trades at Rs 1,00,000 in the spot market. Cost of carry is 6% a year. The fair value of a 6-month futures contract is:","o":["Rs 1,03,000","Rs 1,06,000","Rs 1,01,500","Rs 97,000"],"a":0,"w":"1,00,000 + 1,00,000 &times; 6% &times; 6/12 = 1,03,000."},
 {"id":"3.48","q":"Which of the following is NOT part of cost of carry?","o":["Dividend received on shares","Storage","Insurance","Financing cost"],"a":0,"w":"The book lists storage, insurance, transportation, financing and other holding costs."},
]

CASES = [
 {"id":"C4","title":"Sunrise Foods: pricing a share","text":"Sunrise Foods Ltd has 50 lakh shares of face value Rs 10, trading at Rs 120. Last year's net profit was Rs 3 crore. Equity capital is Rs 5 crore and reserves are Rs 25 crore. It has debt of Rs 20 crore and cash of Rs 5 crore. The board declares a 25% dividend.",
  "qs":[
   {"q":"What is Sunrise's P/E ratio?","o":["20x","6x","12x","40x"],"a":0,"w":"EPS = 3 crore &divide; 50 lakh = Rs 6. P/E = 120 &divide; 6 = 20."},
   {"q":"What is Sunrise's P/BV ratio?","o":["2x","4x","24x","0.5x"],"a":0,"w":"Book value = (5 + 25) crore &divide; 50 lakh = Rs 60. P/BV = 120 &divide; 60 = 2. (4x would come from using only reserves.)"},
   {"q":"What is Sunrise's enterprise value?","o":["Rs 75 crore","Rs 85 crore","Rs 60 crore","Rs 55 crore"],"a":0,"w":"Market cap = 120 &times; 50 lakh = Rs 60 crore. EV = 60 + 20 &minus; 5 = Rs 75 crore."},
   {"q":"What is the dividend payout ratio?","o":["About 41.7%","25%","About 20.8%","2.5%"],"a":0,"w":"DPS = 25% &times; Rs 10 = Rs 2.50. Payout = 2.50 &divide; 6 = 41.7%. 25% is the dividend rate on face value, not the payout."},
  ]},
 {"id":"C5","title":"Anita's bond and gold","text":"Anita buys a bond with face value Rs 1,000 and a 9% coupon paid half-yearly, for Rs 1,050 in the market. She also watches gold: the spot price is Rs 1,00,000 for 10 grams, and the cost of carry is 6% a year.",
  "qs":[
   {"q":"How much does Anita receive at each coupon payment?","o":["Rs 45","Rs 90","Rs 47.25","Rs 94.50"],"a":0,"w":"Coupon is on face value: 1,000 &times; 9% = 90 a year, so 45 every 6 months. The price she paid does not change it."},
   {"q":"What is the bond's current yield?","o":["About 8.57%","9%","About 9.45%","4.5%"],"a":0,"w":"Current yield = yearly coupon &divide; market price = 90 &divide; 1,050 = 8.57%."},
   {"q":"What is the fair value of a 6-month gold futures contract?","o":["Rs 1,03,000","Rs 1,06,000","Rs 1,00,000","Rs 97,000"],"a":0,"w":"1,00,000 + 1,00,000 &times; 6% &times; 6/12 = 1,03,000."},
   {"q":"If the futures trades at that fair value, which is correct?","o":["The market is in contango and the basis is minus Rs 3,000","The market is in backwardation and the basis is Rs 3,000","The market is in contango and the basis is Rs 3,000","The market is in backwardation and the basis is minus Rs 3,000"],"a":0,"w":"Futures above spot = contango. Basis = spot &minus; futures = 1,00,000 &minus; 1,03,000 = minus 3,000."},
  ]},
]

DATA = {"id":"ch03","short":"Ch3","title":"Chapter 3: Terms in equity and debt markets","cards":CARDS,"mcqs":MCQS,"cases":CASES}
