# Chapter 2 study board, hand-built. Other chapters are converted from their LEARN page (lib/boardkit.py).
# Built by boards.py. Block vocabulary and text markup are documented in lib/boardkit.py.
from boardkit import header, H, P, card, note, row, stack, grid, flow, table, bars, seg, box, side

F = []

F.append({"name": "2.1 What is a security?", "blocks": [
 header("2.1", "What is a security?", "Meaning, the four players, the legal definition"),
 P("A **security** is a financial claim you can **transfer** to someone else. It is one of two things:\n- a **promise to pay** you back (debt, like a bond)\n- a **share of ownership** in a company (equity)\nCompanies, financial institutions and the government issue them. The words security, instrument and product mean the same thing in this book."),
 H("What a securities market does"),
 side([flow(box("**Savers**\nHave spare money. Want a return."),
            box("**Securities market**\nTurns savings into investment", "violet"),
            box("**Issuers**\nNeed money for productive use. Pay a cost for it."),
            labels=["money", "money"], back="securities"),
       card("**The big idea: long term becomes short term**\nThe issuer keeps the money for the full term. You can still get out at any time by selling to another investor. This ability to buy and sell easily, close to the market price, is called **liquidity**.", "violet")],
      note("analogy", "A 10-year bond is a 10-hour train ride. You can get off after 2 hours. The **secondary market** is the station where a new passenger takes your seat.")),
 H("The four parts of a financial market"),
 side(grid(2, "**Investors**\n_Providers of funds_\nThey **buy** securities.",
              "**Borrowers**\n_Seekers of funds_\nThey **sell** (issue) securities.",
              "**Intermediaries**\n_The plumbing_\nPipes that move money and securities.",
              "**Regulators**\n_The referee_\nKeep the market orderly and growing."),
      note("trap", "Borrowers are the **sellers** of securities. Investors are the **buyers**. It feels backwards, so it gets tested.")),
 H("The legal definition: ==Section 2(h), SCRA 1956=="),
 P("SCRA is the Securities Contracts (Regulation) Act, 1956.", color="grey"),
 row(card("**Included**\n- Shares, scrips, stocks, bonds, debentures and similar marketable securities of a company, pooled investment vehicle or body corporate\n- Derivatives\n- Units of collective investment schemes\n- Security receipts (under the SARFAESI Act, 2002)\n- Mutual fund units\n- Units of pooled investment vehicles\n- Certificates from a special purpose entity holding debt or receivables, including mortgage debt\n- Government securities\n- Anything else the Central Government declares\n- Rights or interest in securities", "green"),
     stack(card("**Excluded: ULIPs**\nA unit linked insurance policy mixes life cover with investment and is issued by an insurer. It is **not** a security under SCRA.", "red"),
           card("**Recent addition: Electronic Gold Receipts**\nDeclared securities by gazette notification on ==24 December 2021==. An electronic receipt issued against physical gold deposited under SEBI rules.", "violet")),
     widths=[.53, .47], equal=False),
]})

F.append({"name": "2.2 The products (1 of 3)", "blocks": [
 header("2.2", "The products", "Part 1 of 3: the product family, loans, and how bonds get their names"),
 side([P("Every product has its own mix of risk and return. For each one, know who issues it, who invests, how it is sold and **who regulates it**. The regulator is the part most likely to be asked."),
       grid(3, "**Equity shares**\n_Ownership_\nA slice of the company. You share its risks and rewards.\nRegulator: **SEBI, MCA, NCLT**",
               "**Debentures, bonds, notes**\n_Loan_\nYou lent money. You get interest and your money back.\nRegulator: **RBI, SEBI, MCA, NCLT**",
               "**Warrants**\n_Right to buy_\nA right, not a duty, to buy the company's shares later at a fixed price.\nRegulator: **SEBI**",
               "**Mutual fund units, ETFs**\n_Pooled_\nYou own a slice of a basket someone else manages.\nRegulator: **SEBI**",
               "**Hybrids**\n_Mix_\nPart loan, part ownership. Preference shares, convertibles, DRs, FCCBs, ELDs, MBS, REITs.",
               "**Commodities**\n_Things_\nGold, oil, wheat. Every unit is the same quality, so units can be swapped.")],
      note("trap", "Debt regulators include **RBI**. Equity regulators do not.")),
 H("Debentures, bonds and notes"),
 P("All three are loans. The names overlap and the book says you cannot draw hard lines. Rough usage:\n- **Bonds**: umbrella term in the US. Often government, often longer than 10 years. UK government bonds are called **gilts**.\n- **Debentures**: more common in UK usage and for companies. Can be **secured** (backed by collateral) or **unsecured**.\n- **Notes**: short and medium term."),
 H("Short-term debt (up to one year): who issues what"),
 grid(3, "**Treasury Bills**\nIssued by the **government**", "**Commercial Paper**\nIssued by **companies with high credit ratings**", "**Certificate of Deposit**\nIssued by **banks**"),
 H("Name the bond"),
 P("The issuer is an Indian company. Start at the top diamond.", color="grey"),
 side({"t": "tree", "cols": [0.44, 0.56], "rowGap": 120,
       "nodes": [
        {"id": "q1", "r": 0, "c": 0, "geo": "diamond", "h": 230, "color": "violet", "text": "Sold at home, in the home currency?"},
        {"id": "dom", "r": 0, "c": 1, "color": "green", "text": "**Domestic bond**\nSold in the issuer's home country, in its home currency."},
        {"id": "q2", "r": 1, "c": 0, "geo": "diamond", "h": 230, "color": "violet", "text": "In that country's own currency?"},
        {"id": "for", "r": 1, "c": 1, "text": "**Foreign bond**\nIndian firm sells US dollar bonds in the US. Book's example: Delhi International Airport (GMR), ==February 2020==."},
        {"id": "euro", "r": 2, "c": 0, "text": "**Euro bond**\nNot the local currency. Indian firm sells yen bonds in Germany (a Euro-yen bond)."},
        {"id": "mas", "r": 2, "c": 1, "color": "orange", "text": "**Masala bond**\nA Euro bond priced in **Indian rupees**, sold outside India."}],
       "edges": [["q1", "dom", "Yes"], ["q1", "q2", "No: external"], ["q2", "for", "Yes"], ["q2", "euro", "No"], ["euro", "mas", "In rupees?"]]},
      note("why", "**Who carries the currency risk?**\nDollar bond: the **issuer**.\nMasala bond: the **foreign investor**, because repayment is in rupees."),
      note("trap", "\"Euro bond\" has nothing to do with Europe or the euro. It only means the currency is not local where it is sold."),
      note("remember", "First masala bond: **IFC**, ==November 2014==, listed on the **London Stock Exchange**.")),
]})

F.append({"name": "2.2 The products (2 of 3)", "blocks": [
 header("2.2", "The products", "Part 2 of 3: hybrids. Part loan, part ownership"),
 H("Convertible debentures: how much turns into shares?"),
 P("A loan that may turn into shares. Terms are fixed **at the time of issue**: conversion date, ratio (shares per debenture), price (usually below market price), and the portion that converts."),
 bars({"label": "**FCD**\nFully convertible", "segs": [seg(1, "100% becomes shares", "violet")]},
      {"label": "**PCD**\nPartly convertible", "segs": [seg(.5, "Part becomes shares", "violet"), seg(.5, "Rest earns interest, repaid", "grey")]},
      {"label": "**OCD**\nOptionally convertible", "segs": [seg(1, "The **holder chooses**", "violet", "pattern")]},
      {"label": "**NCD**\nNon-convertible", "segs": [seg(1, "Pure loan, repaid at maturity", "grey")]}),
 row(card("**Issuer gains**\n- Pays a **lower coupon**, because investors also hope for share gains\n- No repayment needed, because shares replace it\n- Downside: existing shareholders get **diluted**"),
     card("**Investor gains**\n- Interest in the early years, while the project is young\n- Share price gains later if the company does well")),
 H("Preference shares: half equity, half debt"),
 row(card("**Like equity**\n- Holders are **shareholders**, not creditors\n- Payment is a **dividend**, paid from profit after tax\n- The dividend is **not an obligation**, unlike interest", "violet"),
     card("**Like debt**\n- Fixed rate of dividend\n- Paid **before** ordinary shareholders\n- Repaid **before** ordinary shareholders if the company winds up")),
 P("**Missing**: no voting rights, no claim on leftover assets.\n**Cumulative**: an unpaid dividend carries forward. **Non-cumulative**: it lapses."),
 H("Depository receipts (DRs)"),
 side([P("A DR lets people in one country trade shares of a company from another country, in their own currency, on their own exchange."),
       flow(box("**1. Deliver**\nA company or an investor gives shares to a depository (usually a foreign bank)"),
            box("**2. Park**\nThe depository keeps them with a custodian in the company's home country"),
            box("**3. Issue**\nThe depository issues DRs to investors in the overseas market", "violet")),
       row(card("**Sponsored**\nThe **company** starts it. Can be **listed** on an exchange if listing rules are met.", "green"),
           card("**Unsponsored**\nAn **investor** starts it. Usually **not allowed on exchanges**. Trades OTC only. Lighter regulation.", "red")),
       table([1, 1.2, 1.5, 2.3],
             ["Type", "Traded in", "Issued by", "Book's example"],
             ["ADR", "USA", "A non-US company", "Infosys, Wipro, ICICI Bank, HDFC Bank"],
             ["IDR", "India", "A non-Indian company", "Standard Chartered Bank"],
             ["HKDR", "Hong Kong", "A non-Hong Kong company", ""],
             ["GDR", "**More than one country**", "Any foreign company", "Often issued in EU countries, since common rules make compliance easy"]),
       P("DR holders get dividends and price gains, but **no voting rights**. **Two-way fungibility**: shares can become DRs and DRs can become shares again, subject to rules.")],
      note("analogy", "A cloakroom token. It stands for your coat. Pass the token on, and whoever holds it can claim the coat."),
      note("trap", "IDR rules: a cap on money raised in India, a ==one-year lock-in== before converting to shares, and **resident Indians only**.")),
 H("More hybrids, one line each"),
 grid(2, "**FCCB**: Foreign Currency Convertible Bond\nUsually **optionally** convertible, issued offshore. Interest and principal in foreign currency. After conversion, dividends are in rupees and the currency risk moves to the investor. Regulated by **RBI under FEMA**.",
         "**ELD**: Equity Linked Debenture\nInterest depends on an equity index or shares. Most money goes into bonds to protect capital; the rest buys options for equity upside. **Capital protection does not remove credit risk**, so ELDs are rated.",
         "**CLD**: Commodity Linked Debenture\nSame idea as an ELD, linked to a commodity. Mostly **gold and silver**.",
         "**MBS and ABS**\nBonds paid from loan repayments. **MBS**: home loans. **ABS**: auto loans, rent, credit card dues. Turns loans that cannot be sold into tradable bonds (securitisation)."),
]})

F.append({"name": "2.2 The products (3 of 3)", "blocks": [
 header("2.2", "The products", "Part 3 of 3: pooled products, indices, commodities"),
 H("Pooled products"),
 side(grid(2, "**Mutual fund units**\nA pool of money in a portfolio. One unit's value is the **NAV**.\n**Open-ended**: buy from and sell to the fund at any time. No maturity.\n**Close-ended**: fixed number of units. **Must be listed** and traded on an exchange.",
              "**ETF**\nTracks an index, a commodity like gold, or a basket. **Listed and traded** in real time, even one unit. Passive, so a **lower expense ratio**.",
              "**REIT**\nA trust investing in income-producing real estate. At least ==80%== of assets in real estate.",
              "**InvIT**\nA trust investing in income-producing infrastructure. At least ==90%== of unit capital in such projects."),
      note("remember", "REITs and InvITs both pay out at least ==90%== of distributable cash flow to unit holders."),
      note("why", "**ETF: a bit of both**\nLike an open-ended fund: new units can be made. Like a close-ended fund: trades on an exchange.")),
 H("How ETF units are made"),
 flow(box("**Sponsor**\nA mutual fund or global asset manager sets up the ETF"),
      box("**Authorised participant**\nA big broker or bank assembles the basket and hands it to the sponsor", "violet"),
      box("**ETF units**\nThe participant gets units in return and sells them in the market"),
      box("**Retail investors**\nTrade units like ordinary shares")),
 H("Indices"),
 P("An index tracks the market using a **sample** of shares. Most big indices are **market-cap weighted**: bigger companies count for more. Shares are picked for liquidity, free float and market cap, and the list is reviewed from time to time."),
 row(stack(grid(3, box("**Nifty 50**\n==50== stocks on **NSE**", "violet", size="l"), box("**Sensex**\n==30== stocks on **BSE**", "violet", size="l"), box("**SX40**\n==40== stocks on **MSEI**", "violet", size="l")),
           P("The full name of the Sensex is the S&P BSE Sensex.", color="grey")),
     card("**Five uses of an index**\n- Compare returns with gold or debt\n- Benchmark for a fund\n- Barometer of the economy or a sector\n- Real-time mood of investors\n- Base for index funds, futures and options", "grey"),
     widths=[.57, .43], equal=False),
 H("Commodities"),
 side([P("A commodity is a basic good where every unit is the same, so units can be swapped. **Hard** commodities are mined or extracted: metals, crude oil. **Soft** commodities are grown: grains, pulses.\nThey protect against inflation, but storage is costly. So people invest through:"),
       grid(2, "**Precious metals**\nLong life, low storage cost",
               "**Commodity ETFs**\nThe fund stores it. Gold ETFs are the most common.",
               "**Managed futures**\nProfessionals trade futures, not the goods",
               "**Warehouse receipts**\nProof you own stored goods. Usually negotiable: pass the receipt, pass the ownership.")],
      note("analogy", "A 10-gram gold bar is a commodity: any bar will do. A gold necklace is not: you care which design you get.")),
]})

F.append({"name": "2.3 How the market is built (1 of 2)", "blocks": [
 header("2.3", "How the market is built", "Part 1 of 2: primary and secondary market, ways to issue, the IPO split"),
 row(card("**Primary market**\n_The new issue market_\nThe company sells **new** securities. Money goes **to the issuer**. **Creates** financial assets.", "violet"),
     card("**Secondary market**\n_Trading existing securities_\nMoney goes **between investors**. The issuer is not involved. Gives **liquidity**, which makes people happier to buy in the primary market."),
     note("analogy", "Primary is the car showroom. Secondary is the used-car market, where the maker gets nothing. People buy new cars more happily because they can resell."),
     widths=[1, 1, 260]),
 H("Every way a company can issue shares"),
 side([grid(2, "**To the public**\n- **IPO**: first ever sale of shares to the public. Mainly to raise equity for growth.\n- **FPO**: an already listed company offers shares to the public again. For growth, to repay debt, or to meet public shareholding rules.\n- **OFS**: existing holders sell their shares. **No new shares**, share capital unchanged. Example: government disinvestment in PSUs.",
               "**To a select few (private placement)**\n- Up to ==50== investors, as per the book (Companies Act, 2013)\n- **QIP**: a **listed** company places shares with Qualified Institutional Buyers (FIs, mutual funds, banks and others)\n- **Preferential issue**: a listed company issues to a select person or group. SEBI rules on pricing, disclosure and lock-in apply.",
               "**To existing shareholders**\n- **Rights**: buy more shares at a set price, in a ratio, as on the record date. Three choices: **exercise, transfer, or let lapse**.\n- **Bonus**: **free** shares, instead of dividends. Needs enough retained earnings, which move to share capital.",
               "**To employees and insiders**\n- **Sweat equity**: shares as a reward for contribution. ==Section 54==, Companies Act, 2013. It keeps managers working in the owners' interest (reducing agency risk).\n- **ESOP**: option to buy shares at a set price after a **vesting period**, usually more than a year. The employee gains only if the price rises above the exercise price."),
       P("**Onshore** means raised from investors in India. **Offshore** means raised from investors abroad.")],
      note("trap", "OFS: no new shares. Money goes to the **sellers**, not the company. It is a secondary market deal done through the primary market route."),
      note("trap", "\"FPO\" can also mean Farmer Producer Organisation. Read the context.")),
 H("How an IPO is split between investors"),
 bars({"segs": [seg(35, "**Retail**: at least 35%", "green"), seg(50, "**QIBs**: at most 50%", "blue"), seg(15, "Others", "grey")]}),
 row(card("**Retail investor**\nInvests up to ==Rs 2,00,000== in the issue."),
     card("**Anchor investor**\nA QIB applying for ==Rs 10 crore== or more in a book-built issue. Can get up to ==60%== of the QIB portion. Bids open **one day before** the IPO. Introduced in ==2009==. Strong anchor demand signals a good issue.", "violet"),
     widths=[.4, .6]),
 P("SEBI also sets IPO eligibility (net tangible assets, profitability, net worth), requires listing on a nationwide exchange, and requires shares in demat form."),
]})

F.append({"name": "2.3 How the market is built (2 of 2)", "blocks": [
 header("2.3", "How the market is built", "Part 2 of 2: the secondary market, clearing and settlement"),
 H("Two ways to trade"),
 side([table([1, 1.4, 1.4],
             ["", "Over-the-counter (OTC)", "Exchange traded"],
             ["How the deal is made", "Negotiated directly between the parties", "Electronic order matching on the exchange"],
             ["Who settles", "The parties themselves", "The clearing corporation"],
             ["Default risk", "Each party manages it alone", "Clearing corporation **guarantees** settlement"]),
       H("Life of an exchange trade"),
       flow(box("**1. Trading**\nYou place an order through a broker. The exchange matches buyers and sellers."),
            box("**2. Clearing**\nWork out each party's **net** dues. The clearing house sends obligation reports to brokers and custodians.", "violet"),
            box("**3. Settlement**\nThe seller delivers shares. The buyer pays. Miss the deadline and pay a penalty.", "green"))],
      note("why", "**Novation**\nThe clearing corporation becomes the **buyer to every seller** and the **seller to every buyer**."),
      note("analogy", "An online marketplace that holds the money. You trust the platform, not the stranger selling to you.")),
 H("Margins: how the clearing corporation protects itself"),
 P("Guaranteeing every trade is risky, so the clearing corporation collects **margins**:"),
 grid(3, "**Initial (upfront) margin**\nA percentage of trade value, based on ==Value at Risk==.",
         "**Peak margin**\nThe book names it as one of the three but does not explain it. Know the name.",
         "**Mark-to-market (MTM) margin**\nThe paper loss on an open trade due to price moves."),
]})

F.append({"name": "2.4 Who is in the market? (1 of 2)", "blocks": [
 header("2.4", "Who is in the market?", "Part 1 of 2: intermediaries. Sort them by the job they do"),
 side(grid(2, "**Help companies issue (primary)**\n- **Merchant bankers**: SEBI-registered issue managers or lead managers. Single point of contact for the issuer. Plan the issue, price it, run it until listing, and coordinate other intermediaries.\n- **Underwriters**: promise to buy what the public does not. **Hard**: committed at the start. **Soft**: committed after pricing, with an exit clause.",
              "**Run the marketplace**\n- **Stock exchanges**: NSE, BSE, MSEI (nationwide). Anonymous electronic order matching. Appoint clearing agencies and clearing banks.\n- **Trading members (brokers)**: every exchange trade must go through one.\n- **Authorised persons**: agents of a broker. Need prior exchange approval, per person and per segment.",
              "**After the trade**\n- **Clearing corporation**: legal counterparty to all exchange trades. Guarantees settlement.\n- **Clearing banks**: every clearing member keeps an account here for money pay-in and pay-out.\n- **Depositories**: hold securities electronically. Two in India: **NSDL** and **CDSL**. Company-level accounts.\n- **Depository participants (DPs)**: the depository's agents. Investor-level accounts.\n- **Custodians**: hold securities and funds for big institutions, settle their trades, track corporate actions.",
              "**Commodity side**\n- **Farmer Producer Organisations**: farmer collectives for better prices and market access.\n- **Warehouse service providers**: storage. Many registered with **WDRA**. Issue Negotiable Warehouse Receipts (NWRs).\n- **Quality assayers**: test and certify quality. Often accredited by WDRA. Their certificates are needed for NWRs."),
      note("analogy", "Depository and DP are a bank and its branch. NSDL or CDSL is head office. The DP is the branch where you open your account."),
      note("trap", "**Sub-brokers** were abolished. SEBI decided on ==21 June 2018==, effective ==1 April 2019==. They became authorised persons or trading members.")),
 card("**Who can be a DP?**\nPublic financial institutions, scheduled commercial banks, RBI-approved foreign banks, state financial corporations, custodians, stockbrokers, clearing corporations, NBFCs, and registrars and share transfer agents. Appointed by the depository with SEBI approval.", "grey"),
]})

F.append({"name": "2.4 Who is in the market? (2 of 2)", "blocks": [
 header("2.4", "Who is in the market?", "Part 2 of 2: the investors"),
 H("Institutional investors"),
 side(grid(3, "**FPI**\nSet up outside India, invests in India. **Must register with SEBI**.",
              "**P-Note holders**\nOverseas investors who do **not** register with SEBI.",
              "**Mutual funds**\nPool money; a fund manager decides. Diversification lowers risk.",
              "**Insurance companies**\nLarge corpus. Invest in equity, government securities and bonds.",
              "**Pension funds**\nRetirement money from employers and employees. Among the largest investors.",
              "**Venture capital**\nEarly-stage firms with long-term potential. Bring expertise as well as money.",
              "**Private equity**\nGrowth, expansion, buy-outs. Includes VC. Investors are **limited partners**; managers are **general partners**.",
              "**Hedge funds**\nVery wide mandate. The name is a **misnomer**: they are not necessarily hedged.",
              "**EPF**\nEmployer pays ==12%== of basic salary, the employee the same. Run by **EPFO**. Employees have no say in investments.",
              "**NPS**\nGovernment-sponsored retirement scheme. Buy an annuity at maturity; partial withdrawal allowed.",
              "**Family offices**\nManage a wealthy family's money, tax, estate, even household payments.",
              "**Corporate treasuries**\nInvest a company's spare cash. Small firms mostly use mutual funds."),
      note("trap", "P-Notes are issued **by SEBI-registered FPIs** to overseas investors who are **not** registered with SEBI.")),
 H("Alternative Investment Funds (AIFs): three categories"),
 P("Defined in Regulation 2(1)(b), SEBI (AIF) Regulations, 2012. A privately pooled fund not already covered by other SEBI fund rules or by IRDAI, PFRDA or RBI.", color="grey"),
 grid(3, box("**Category I**\n_Good for the economy_\nStart-ups, early-stage, social ventures, SMEs, infrastructure. Includes VC funds and **angel funds**.", "green"),
         box("**Category II**\n_The rest, no leverage_\nNot I or III. No borrowing except for day-to-day needs. Real estate funds, **PE funds**, distressed asset funds."),
         box("**Category III**\n_Complex, uses leverage_\nLeverage and derivatives. **Hedge funds**, PIPE funds.", "red")),
 H("Everyone else"),
 grid(4, "**Retail investors**\nIndividuals trading for themselves. **HNIs** and **UHNIs** invest large sums. RBI lets **NRIs, PIOs and QFIs** invest directly.",
         "**Corporates**\nProcessors, manufacturers, importers and exporters whose margins depend on commodity prices.",
         "**Investment advisers**\nHelp with asset allocation and financial plans based on needs, horizon and risk.",
         "**Proxy advisers**\nTell investors, mostly **institutions**, how to vote on company proposals.", color="grey"),
]})

F.append({"name": "2.5 Kinds of deals (1 of 2)", "blocks": [
 header("2.5", "Kinds of deals", "Part 1 of 2: settlement days and the four derivatives"),
 H("When does settlement happen?"),
 P("**T** is the trade date. The number after it is how many days later money and goods change hands."),
 flow(box("**T+0: Cash**\nSame day. Like buying vegetables at the market.", "green"),
      box("**T+1: Tom**\nNext day (\"tomorrow\"). Some FX deals settle this way."),
      box("**T+2: Spot**\nNormally two business days after the trade. The global default for FX.", "violet"),
      labels=["+1 day", "+1 day"]),
 P("The book notes Indian exchanges have moved stocks to a T+1 cycle. For the exam, learn the three definitions above.", color="grey"),
 H("The four derivatives"),
 P("A derivative is a contract whose value comes from something else: a share, an index, wheat, an interest rate."),
 table([1, 1.3, 1.3, 1.3, 1.3],
       ["", "Forward", "Futures", "Options", "Swaps"],
       ["What it is", "Agree today to buy or sell later at a fixed price", "A forward with **standard terms**", "**Right, not obligation**, to buy (call) or sell (put)", "Swap cash flows by a set formula"],
       ["Where", "OTC", "Exchange", "OTC or exchange", "OTC"],
       ["Terms", "Customised", "Standard lot, quality, delivery date", "Strike price, expiry", "Notional amount, fixed and floating legs"],
       ["Default risk", "High. Relies on trust.", "Clearing corporation guarantees. Strict margins.", "Buyer pays the premium upfront", "Counterparty"],
       ["Book's example", "Farmer sells wheat to a miller 6 months ahead", "MCX wheat: 10 MT trading unit, physical delivery", "Arvind buys a Nifty call from Salim", "Borrower turns a floating-rate loan into fixed"]),
 H("Arvind's call option"),
 P("Arvind buys a Nifty call from Salim. Strike ==11,000==. Premium ==Rs 100==. The chart shows each side's profit or loss on expiry day."),
 side({"t": "payoff", "K": 11000, "P": 100, "lo": 10600, "hi": 11400, "height": 480},
      note("remember", "Arvind breaks even at ==11,100==: strike plus premium."),
      note("trap", "The buyer pays the premium and gets a **right**. The writer receives it and takes an **obligation**.")),
]})

F.append({"name": "2.5 Kinds of deals (2 of 2)", "blocks": [
 header("2.5", "Kinds of deals", "Part 2 of 2: swaps, the four motives, pledging"),
 card("**Swap in one line**\nThe borrower pays a **fixed** rate to a swap dealer and receives a **floating** rate (T-bill plus spread). The floating money received pays the floating loan. What is left is a fixed payment. Only interest is exchanged; the principal (the **notional**) is not.", "violet"),
 H("Four motives: why people trade"),
 side([grid(2, "**Trading**\nShort term: hours, days, weeks. Based on **price patterns** (technical analysis), assuming history repeats. The book says traders have a **higher probability of gains** than speculators.",
               "**Speculating**\nBuy or sell expecting a price change, usually short term. Based on private or insider information, or a view on fundamentals.",
               box("**Hedging**\nTake a position to **offset losses** on something you already hold. The aim is **no gain, no loss**.", "green"),
               box("**Arbitrage**\n**Buy and sell at the same time** in two markets to profit from a price gap. Example: buy in spot, sell in futures.", "violet")),
       P("Traders and speculators add liquidity. Both often use borrowed money, which magnifies gains and losses.")],
      note("trap", "Hedging aims for **no gain, no loss**. Arbitrage is a **simultaneous** buy and sell.")),
 H("Pledging shares"),
 side(card("**Taking a loan against your shares**\n- **Pledgor**: the investor who borrows. **Pledgee**: the lender.\n- Pledged shares **stay in the pledgor's demat account**, but are **blocked**.\n- Once the loan is repaid, they are unpledged.\n- On default, the pledgee can sell them, after giving notice and a fair chance to repay."),
      note("analogy", "Leaving gold with a jeweller for a loan, except the gold stays in your own locker and the lender holds the key.")),
]})

F.append({"name": "2.6 Paper to electronic", "blocks": [
 header("2.6", "Paper to electronic", "Demat and remat"),
 flow(box("**Paper certificates**\nEach share has a distinctive number, folio and certificate number.", "grey"),
      box("**Electronic holdings**\nBook entries. Shares lose their distinctive numbers. One investor's shares cannot be told apart from another's.", "violet"),
      labels=["demat"], back="remat, on the investor's request"),
 side(P("**Remat** brings shares back as certificates **with distinctive numbers**.\nA company making a public issue must sign an agreement with **all** depositories, so investors can hold its shares in demat form."),
      note("trap", "Remat gives back **distinctive numbers**.")),
]})

TRAPS = [
 "Borrowers **sell** securities; investors **buy** them.",
 "Securities are defined in **Section 2(h) of SCRA, 1956**. ULIPs are excluded. Electronic Gold Receipts were added on 24 December 2021.",
 "Debt regulators include **RBI**; equity regulators do not. Warrants, mutual funds and ETFs: **SEBI**.",
 "T-bills: government. Commercial paper: highly rated companies. CDs: banks.",
 "Foreign bond: local currency of the country where sold. Euro bond: a different currency. Masala bond: rupees, sold abroad.",
 "Foreign currency bond: the issuer carries currency risk. Masala bond: the investor carries it.",
 "First masala bond: IFC, November 2014, London Stock Exchange.",
 "OCD: the holder chooses to convert. FCCBs are usually optionally convertible and regulated by RBI under FEMA.",
 "Preference shares: no voting rights. Cumulative carries an unpaid dividend forward.",
 "Sponsored DRs can list; unsponsored trade OTC. GDRs trade in more than one country. IDR: one-year lock-in, resident Indians only.",
 "Sensex 30 (BSE), Nifty 50 (NSE), SX40 40 (MSEI). Most indices are market-cap weighted.",
 "Close-ended fund units must be listed. ETFs have lower expense ratios.",
 "REIT: 80% in real estate. InvIT: 90% in infra. Both distribute at least 90%.",
 "IPO: retail at least 35% (up to Rs 2 lakh), QIB at most 50%. Anchor: Rs 10 crore plus, up to 60% of the QIB portion, one day early.",
 "OFS: no new shares; money to the sellers. Rights: exercise, transfer or lapse. Bonus: free, from retained earnings.",
 "Private placement: up to 50 investors as per the book. QIP is for listed companies only.",
 "Sweat equity: Section 54, Companies Act, 2013.",
 "Novation: the clearing corporation is buyer to every seller and seller to every buyer. Initial margin is based on Value at Risk.",
 "Two depositories: NSDL and CDSL. Sub-brokers ended 1 April 2019.",
 "P-Notes are issued by FPIs to overseas investors who are not registered with SEBI.",
 "AIF Cat I: VC and angel funds. Cat II: PE and real estate funds. Cat III: hedge funds and PIPE funds.",
 "Cash T+0, Tom T+1, Spot T+2.",
 "Option buyer pays the premium and has a right. The writer receives the premium and has an obligation.",
 "Hedging aims for no gain, no loss. Arbitrage is a simultaneous buy and sell.",
 "Pledged shares stay in the pledgor's account, blocked.",
 "Remat gives back distinctive numbers.",
]
F.append({"name": "Exam traps: all 26", "blocks": [
 header("!", "All exam traps in this chapter", "Read these the night before. Each one is a question waiting to happen"),
 {"t": "notes", "kind": "trap", "cols": 5, "numbered": True, "items": TRAPS},
]})

F.append({"name": "For the group discussion", "blocks": [
 header("?", "For the group discussion", "Pick one each. Argue it out"),
 {"t": "notes", "kind": "discuss", "cols": 5, "numbered": True, "items": [
  "Walk through the life of one share you bought last month. Name every intermediary it touched.",
  "Why would an Indian company issue a masala bond instead of a dollar bond? Who wins, who takes the risk?",
  "A company does an OFS and an FPO in the same year. What changes in its share capital in each case?",
  "Is a gold ETF a security, a commodity, or both? Argue it using the SCRA list.",
  "Look at the option chart. At what Nifty level are Arvind and Salim both at zero? Why is that not 11,000?",
 ]},
]})

SPEC = {
 "slug": "ch02", "pageName": "Chapter 2: The securities market", "frameWidth": 1400, "columns": 5,
 "style": {"bodyFont": "sans", "bodySize": "m", "headFont": "draw", "noteFont": "draw", "dash": "draw", "noteWidth": 260},
 "banner": {
  "title": "Chapter 2: The securities market",
  "sub": "NISM Series XV Research Analyst  ·  Worth 2 marks of 100  ·  Book pages 22 to 54  ·  Notes from the February 2026 workbook. Study aid only.",
  "oneline": "A securities market moves savers' money to businesses that need it, and lets savers get out whenever they want.",
  "legend": [["trap", "A point the exam likes to twist"], ["analogy", "An everyday picture of the idea"], ["why", "WHY IT MATTERS\nThe reason behind a rule"], ["remember", "A number or date to learn. ==Highlighted== text means the same."]],
  "hint": "Frames read top to bottom, then left to right. Zoom into one frame at a time.",
 },
 "frames": F,
}
