CARDS = [
 {"f":"What is a security?","b":"A <b>transferable</b> financial claim: either a promise to pay (debt) or ownership in a company (equity)."},
 {"f":"How does a secondary market turn long-term securities into short-term ones?","b":"The issuer keeps the money for the full term, but an investor can <b>exit anytime</b> by selling to another investor."},
 {"f":"Four parts of a financial market","b":"Investors (buyers of securities), borrowers (sellers of securities), intermediaries, regulators."},
 {"f":"Where is 'securities' defined in Indian law?","b":"<b>Section 2(h)</b> of the Securities Contracts (Regulation) Act, <b>1956</b>."},
 {"f":"Which insurance product is excluded from the SCRA definition of securities?","b"
 :"<b>ULIPs</b> (unit linked insurance policies)."},
 {"f":"When were Electronic Gold Receipts declared securities?","b":"Gazette notification of <b>24 December 2021</b>."},
 {"f":"Regulators for equity shares","b":"SEBI, MCA (Ministry of Corporate Affairs), NCLT."},
 {"f":"Regulators for debentures and bonds","b":"<b>RBI</b>, SEBI, MCA, NCLT."},
 {"f":"Treasury Bills, Commercial Paper, Certificate of Deposit: who issues each?","b":"T-bills: government. CP: highly rated companies. CD: banks. All up to one year."},
 {"f":"Foreign bond","b":"Issued abroad, in the <b>local currency of that foreign country</b>. Example: Indian firm sells USD bonds in the US."},
 {"f":"Euro bond","b":"Issued abroad, in a currency <b>different from</b> that country's local currency. Example: Indian firm sells yen bonds in Germany. Not about Europe."},
 {"f":"Masala bond","b":"A euro bond <b>denominated in Indian rupees</b>, issued outside India. First: IFC, <b>November 2014</b>, London Stock Exchange."},
 {"f":"Who carries currency risk: foreign currency bond vs masala bond?","b":"Foreign currency bond: the <b>issuer</b>. Masala bond: the <b>foreign investor</b>."},
 {"f":"Warrant","b":"The <b>right, not obligation</b>, to buy the issuer's shares after a set period at a pre-set price. Regulator: SEBI."},
 {"f":"Sensex, Nifty 50, SX40: how many stocks and which exchange?","b":"Sensex: 30, BSE. Nifty 50: 50, NSE. SX40: 40, MSEI."},
 {"f":"Five uses of an index","b":"Compare with other assets. Benchmark for funds. Barometer of economy or sector. Real-time sentiment. Base for index funds and derivatives."},
 {"f":"Open-ended vs close-ended mutual fund","b":"Open: buy from and sell to the fund anytime, no maturity. Close: fixed units, <b>must be listed</b>, traded on the exchange."},
 {"f":"ETF in one line","b":"A fund that tracks an index or commodity, <b>listed and traded in real time</b>, with a lower expense ratio. Units created via <b>authorised participants</b>."},
 {"f":"Preference shares: equity-like features","b":"Holders are shareholders, payment is a dividend from profit after tax, dividend is not an obligation."},
 {"f":"Preference shares: debt-like features","b":"Fixed dividend rate, paid before ordinary shareholders, repaid first on winding up. No voting rights."},
 {"f":"Cumulative vs non-cumulative preference shares","b":"Cumulative: unpaid dividend carries forward. Non-cumulative: it lapses."},
 {"f":"FCD, PCD, OCD","b":"FCD: all converts to shares. PCD: part converts, rest repaid. OCD: <b>holder chooses</b>."},
 {"f":"Why do convertibles carry a lower coupon?","b":"Investors also expect gains when the debt becomes shares."},
 {"f":"Sponsored vs unsponsored DR","b":"Sponsored: company starts it, can list on an exchange. Unsponsored: investor starts it, OTC only."},
 {"f":"ADR, IDR, GDR","b":"ADR: traded in the US by a non-US firm (Infosys). IDR: traded in India by a non-Indian firm (Standard Chartered). GDR: traded in <b>more than one country</b>."},
 {"f":"SEBI's IDR conditions","b":"Limit on money raised, <b>one-year lock-in</b> on conversion, only <b>resident Indians</b> can invest."},
 {"f":"FCCB","b":"Foreign currency convertible bond, usually optionally convertible, issued offshore. Regulated by <b>RBI under FEMA</b>."},
 {"f":"Equity Linked Debenture","b":"Interest tied to equity returns. Bonds for capital protection plus options for upside. Still has <b>credit risk</b>."},
 {"f":"MBS vs ABS","b":"MBS: backed by home loans. ABS: backed by auto loans, rent, credit card dues."},
 {"f":"REIT and InvIT asset rules","b":"REIT: at least <b>80%</b> in real estate. InvIT: at least <b>90%</b> in income-producing infra. Both distribute at least <b>90%</b>."},
 {"f":"Hard vs soft commodities","b":"Hard: mined or extracted (metals, crude). Soft: grown (grains, pulses)."},
 {"f":"Primary vs secondary market","b":"Primary: issuer sells new securities, money goes to issuer. Secondary: investors trade existing ones, issuer not involved."},
 {"f":"IPO allocation limits","b":"Retail at least <b>35%</b> (up to Rs 2 lakh each). QIBs at most <b>50%</b>. Others get the balance."},
 {"f":"Anchor investor","b":"QIB applying <b>Rs 10 crore+</b> in a book-built issue. Up to <b>60% of the QIB portion</b>. Bids <b>one day before</b>. Introduced 2009."},
 {"f":"Offer for Sale (OFS)","b":"Existing holders sell. <b>No new shares</b>, no change in share capital, money goes to sellers."},
 {"f":"Three choices with a rights entitlement","b":"Exercise it, transfer it, or let it lapse."},
 {"f":"Bonus shares","b":"Free shares, instead of dividends. Need enough retained earnings, which are moved to share capital."},
 {"f":"Sweat equity","b":"Shares given as a reward for contribution. <b>Section 54</b>, Companies Act, 2013."},
 {"f":"Clearing vs settlement","b":"Clearing: work out net dues. Settlement: seller delivers shares, buyer pays money."},
 {"f":"Novation","b":"Clearing corporation becomes <b>buyer to every seller and seller to every buyer</b>."},
 {"f":"Initial margin vs MTM margin","b":"Initial: a % of trade value based on <b>Value at Risk</b>. MTM: the paper loss on an open trade from price moves."},
 {"f":"Depository vs depository participant","b":"Depository (NSDL, CDSL): company-level accounts. DP: its agent, keeps investor-level accounts."},
 {"f":"When did sub-brokers cease to exist?","b":"<b>1 April 2019</b> (SEBI decision of 21 June 2018)."},
 {"f":"Hard vs soft underwriting","b":"Hard: committed at the start. Soft: committed after pricing, with an exit clause."},
 {"f":"P-Notes","b":"Issued by <b>SEBI-registered FPIs</b> to overseas investors who are <b>not registered</b> with SEBI."},
 {"f":"AIF categories","b":"Cat I: start-ups, SMEs, social, infra, VC, angel. Cat II: the rest, no leverage (PE, real estate). Cat III: leverage and derivatives (hedge funds, PIPE)."},
 {"f":"Cash, tom, spot","b":"Cash T+0. Tom T+1. Spot T+2 (normally)."},
 {"f":"Forward vs futures","b":"Forward: OTC, customised, counterparty risk. Futures: exchange, standardised, clearing guarantee, margins."},
 {"f":"Call option vs put option","b":"Call: right to <b>buy</b>. Put: right to <b>sell</b>. Buyer pays premium; writer takes the obligation."},
 {"f":"Hedging vs arbitrage","b":"Hedging: offset losses, aim no gain no loss. Arbitrage: simultaneous buy and sell in two markets to profit from a price gap."},
 {"f":"Pledgor vs pledgee","b":"Pledgor: investor who borrows. Pledgee: lender. Shares stay in pledgor's demat account, blocked."},
 {"f":"Demat vs remat","b":"Demat: paper to electronic, no distinctive numbers. Remat: electronic to paper, distinctive numbers come back."},
]

MCQS = [
 {"id":"2.1","q":"As per the Securities Contracts (Regulation) Act, 1956, the term 'securities' includes which of the following?","o":["Government securities","Derivatives","Shares, scrips or bonds","All of the above"],"a":3,"w":"All three appear in the SCRA Section 2(h) list."},
 {"id":"2.2","q":"Where the entire face value of a debenture is converted into equity shares, it is called a:","o":["Fully convertible debenture","Partly convertible debenture","Optionally convertible debenture","None of the above"],"a":0,"w":"FCD: the full face value converts."},
 {"id":"2.3","q":"Which of these is NOT a security under Section 2(h) of SCRA?","o":["Mutual fund units","Unit linked insurance policy","Security receipts","Government securities"],"a":1,"w":"ULIPs are expressly excluded because they combine life cover with investment and are issued by insurers."},
 {"id":"2.4","q":"In a financial market, borrowers or seekers of funds are:","o":["Buyers of securities","Regulators of securities","Sellers of securities","Custodians of securities"],"a":2,"w":"Borrowers issue, that is sell, securities to investors."},
 {"id":"2.5","q":"Commercial Paper is issued by:","o":["The Government of India","Banks only","Companies with high credit ratings","The RBI"],"a":2,"w":"T-bills: government. CP: highly rated companies. CD: banks."},
 {"id":"2.6","q":"An Indian company issues a bond in Germany denominated in Japanese yen. This is a:","o":["Foreign bond","Euro bond","Masala bond","Domestic bond"],"a":1,"w":"The currency (yen) differs from the local currency of the country of issue (Germany), so it is a Euro bond, specifically a Euro-yen bond."},
 {"id":"2.7","q":"An Indian company issues US dollar bonds in the United States. This is a:","o":["Foreign bond","Euro bond","Masala bond","Domestic bond"],"a":0,"w":"Issued abroad in that country's own currency: a foreign bond."},
 {"id":"2.8","q":"In a masala bond, the currency risk is borne by:","o":["The Indian issuer","The Reserve Bank of India","The foreign investor","The stock exchange"],"a":2,"w":"Masala bonds are in rupees, so a falling rupee hurts the foreign investor."},
 {"id":"2.9","q":"The first masala bond was issued in November 2014 by:","o":["State Bank of India","International Finance Corporation","HDFC Ltd","World Bank"],"a":1,"w":"IFC issued it and listed it on the London Stock Exchange."},
 {"id":"2.10","q":"A warrant gives the holder:","o":["The obligation to buy shares at market price","The right, but not the obligation, to buy the issuer's shares after a set period at a pre-determined price","A fixed interest payment","Voting rights immediately"],"a":1,"w":"That is the book's definition. Regulator: SEBI."},
 {"id":"2.11","q":"The S&P BSE Sensex is computed from how many stocks?","o":["30","40","50","100"],"a":0,"w":"Sensex 30 (BSE), SX40 40 (MSEI), Nifty 50 50 (NSE)."},
 {"id":"2.12","q":"Most leading market indices are weighted by:","o":["Share price","Market capitalisation","Dividend yield","Trading volume"],"a":1,"w":"Most leading indices are market-cap weighted."},
 {"id":"2.13","q":"Units of a close-ended mutual fund scheme:","o":["Can be sold back to the fund anytime","Have no fixed number","Are mandatorily listed and traded on a stock exchange","Cannot be traded at all"],"a":2,"w":"Close-ended funds have fixed unit capital and must be listed."},
 {"id":"2.14","q":"Which statement about ETFs is correct?","o":["They are actively managed with high expense ratios","They trade on an exchange at real-time prices and usually have lower expense ratios","They can only be bought from the fund at day-end NAV","They cannot track commodities"],"a":1,"w":"ETFs are passive, listed, traded in real time, and cheaper than typical mutual funds."},
 {"id":"2.15","q":"Which is a feature of preference shares?","o":["Voting rights equal to equity shares","Right over residual assets on winding up","Dividend paid before dividend on ordinary equity shares","Dividend payment is a legal obligation like interest"],"a":2,"w":"Preference shareholders are paid before ordinary shareholders. They have no voting rights or residual claim, and dividend is not an obligation."},
 {"id":"2.16","q":"In cumulative preference shares, unpaid dividend:","o":["Lapses","Is carried forward","Is converted into equity","Is paid as interest"],"a":1,"w":"Cumulative: carried forward. Non-cumulative: lapses."},
 {"id":"2.17","q":"Debentures that holders may choose to convert into equity or keep as debt are called:","o":["FCDs","PCDs","OCDs","NCDs"],"a":2,"w":"Optionally convertible debentures convert at the holder's discretion."},
 {"id":"2.18","q":"A disadvantage of convertible debentures for the issuing company is:","o":["Higher coupon than pure debt","Dilution of existing shareholders on conversion","Mandatory repayment in cash","No investor interest"],"a":1,"w":"Converting into new shares dilutes existing holders. Coupons are actually lower than pure debt."},
 {"id":"2.19","q":"Depository receipts created when an investor, not the company, delivers the shares are:","o":["Sponsored DRs, which can be listed","Unsponsored DRs, usually traded only OTC","IDRs","Always GDRs"],"a":1,"w":"Unsponsored DRs are investor-initiated and typically not allowed on exchanges."},
 {"id":"2.20","q":"Depository receipts that can be traded in more than one country are called:","o":["ADRs","IDRs","HKDRs","GDRs"],"a":3,"w":"GDRs trade across multiple countries, often in the EU."},
 {"id":"2.21","q":"Which of the following is NOT a SEBI condition for IDRs mentioned in the book?","o":["Limit on money raised in India","One-year lock-in on conversion into shares","Available only to resident Indian investors","Mandatory voting rights for IDR holders"],"a":3,"w":"DR holders generally have no voting rights. The other three are listed conditions."},
 {"id":"2.22","q":"FCCBs are regulated by:","o":["SEBI under the SEBI Act","RBI under FEMA","IRDAI","MCA under the Companies Act only"],"a":1,"w":"FCCBs are governed by RBI notifications under FEMA."},
 {"id":"2.23","q":"Which statement about Equity Linked Debentures is correct?","o":["Capital protection means no credit risk","They carry credit risk and are rated by credit rating agencies","Interest is always fixed","They invest only in equity shares"],"a":1,"w":"Capital protection does not remove the risk of the issuer defaulting."},
 {"id":"2.24","q":"A REIT must hold at least what share of its assets in real estate?","o":["51%","75%","80%","90%"],"a":2,"w":"REIT: 80% real estate. InvIT: 90% of unit capital in revenue-generating infra. Both distribute at least 90%."},
 {"id":"2.25","q":"Crude oil is an example of a:","o":["Soft commodity","Hard commodity","Financial derivative","Warehouse receipt"],"a":1,"w":"Hard commodities are mined or extracted. Soft ones are grown."},
 {"id":"2.26","q":"In an eligible IPO, the minimum allocation to retail investors is:","o":["25%","35%","50%","60%"],"a":1,"w":"At least 35% to retail (up to Rs 2 lakh each). QIBs at most 50%."},
 {"id":"2.27","q":"An anchor investor is a QIB applying for at least ______ in a book-built public issue.","o":["Rs 2 lakh","Rs 1 crore","Rs 10 crore","Rs 100 crore"],"a":2,"w":"Anchors apply for Rs 10 crore or more and can take up to 60% of the QIB portion."},
 {"id":"2.28","q":"Which statement about an Offer for Sale is correct?","o":["It increases the company's share capital","Proceeds go to the company","Existing shareholders sell already allotted shares and proceeds go to them","It can only be made to QIBs"],"a":2,"w":"No new shares are issued, so share capital does not change and money goes to the selling holders."},
 {"id":"2.29","q":"An investor who receives rights entitlements can do all of the following EXCEPT:","o":["Exercise the right","Transfer the right to another investor","Let the right lapse","Convert the right into bonus shares"],"a":3,"w":"The three options are exercise, transfer, or lapse."},
 {"id":"2.30","q":"Sweat equity shares are issued under which section of the Companies Act, 2013?","o":["Section 42","Section 54","Section 62","Section 2(h)"],"a":1,"w":"Section 54 covers sweat equity. Section 2(h) is from SCRA, a distractor."},
 {"id":"2.31","q":"The clearing corporation acting as buyer to every seller and seller to every buyer is called:","o":["Netting","Novation","Arbitrage","Dematerialisation"],"a":1,"w":"Novation substantially reduces counterparty risk for investors."},
 {"id":"2.32","q":"Initial margin charged by a clearing corporation is based on the concept of:","o":["Mark to market","Value at Risk","Book value","Face value"],"a":1,"w":"Initial margin is a percentage of trade value based on Value at Risk."},
 {"id":"2.33","q":"Which two depositories are registered with SEBI in India?","o":["NSE and BSE","NSDL and CDSL","NSCCL and ICCL","RBI and SEBI"],"a":1,"w":"NSDL and CDSL. NSE and BSE are exchanges."},
 {"id":"2.34","q":"Sub-brokers as a category of intermediary ceased to exist with effect from:","o":["21 June 2018","1 April 2019","1 January 2020","24 December 2021"],"a":1,"w":"SEBI decided on 21 June 2018; it took effect on 1 April 2019. The other dates are distractors from this chapter."},
 {"id":"2.35","q":"Participatory Notes are issued by:","o":["SEBI to foreign investors","SEBI-registered FPIs to overseas investors who are not registered with SEBI","Indian companies to NRIs","Stock exchanges to brokers"],"a":1,"w":"P-Notes let unregistered overseas investors access Indian securities through registered FPIs."},
 {"id":"2.36","q":"Hedge funds are registered in India as:","o":["Category I AIFs","Category II AIFs","Category III AIFs","Mutual funds"],"a":2,"w":"Category III covers complex strategies with leverage and derivatives, such as hedge funds and PIPE funds."},
 {"id":"2.37","q":"A trade where settlement happens on the next day after trade date is a:","o":["Cash trade","Tom trade","Spot trade","Forward trade"],"a":1,"w":"Cash T+0, Tom T+1, Spot T+2."},
 {"id":"2.38","q":"Which statement correctly distinguishes futures from forwards?","o":["Futures are OTC and customised","Futures are standardised and exchange traded with clearing guarantee","Forwards have no counterparty risk","Forwards require exchange margins"],"a":1,"w":"Futures are standardised forwards traded on exchanges, guaranteed by the clearing corporation, with margins."},
 {"id":"2.39","q":"The buyer of a put option has:","o":["The obligation to sell","The right to sell","The right to buy","The obligation to buy"],"a":1,"w":"Put buyer: right to sell. Call buyer: right to buy. The writer carries the obligation."},
 {"id":"2.40","q":"Simultaneous purchase and sale of an asset in two markets to profit from a price difference is called:","o":["Hedging","Speculation","Arbitrage","Pledging"],"a":2,"w":"That is arbitrage. Hedging offsets losses on an existing position."},
 {"id":"2.41","q":"When dematerialised shares are pledged, they:","o":["Move to the pledgee's demat account","Stay in the pledgor's demat account but are blocked","Are converted to physical form","Are sold immediately"],"a":1,"w":"They remain with the pledgor, blocked, until the loan is repaid."},
 {"id":"2.42","q":"Converting securities held electronically back into physical form is called:","o":["Dematerialisation","Rematerialisation","Securitisation","Novation"],"a":1,"w":"Remat gives back certificates with distinctive numbers."},
]

CASES = [
 {"id":"C2","title":"Riverline Infra raises money","text":"Riverline Infra Ltd is an Indian company listed on NSE. This year it (i) issues rupee-denominated bonds to investors in London, (ii) lets its promoter sell 5% of his stake to the public, and (iii) gives existing holders one free share for every ten held, out of retained earnings.",
  "qs":[
   {"q":"The rupee bonds sold in London are best called:","o":["Foreign bonds","Masala bonds","Domestic bonds","FCCBs"],"a":1,"w":"Rupee-denominated bonds issued outside India are masala bonds."},
   {"q":"Who bears the currency risk on the London bonds?","o":["Riverline Infra","The promoter","The foreign investors","NSE"],"a":2,"w":"Repayment is in rupees, so a falling rupee hurts the foreign investors."},
   {"q":"The promoter's sale of 5% to the public is an Offer for Sale. Its effect on Riverline's share capital is:","o":["Share capital rises by 5%","Share capital falls by 5%","No change in share capital","Share capital doubles"],"a":2,"w":"OFS uses existing shares. No new shares, so no change in share capital."},
   {"q":"The one-for-ten free share is a:","o":["Rights issue","Bonus issue","Preferential issue","QIP"],"a":1,"w":"Free shares from retained earnings to existing holders are bonus shares."}
  ]},
 {"id":"C3","title":"Meera's first trade","text":"Meera buys 100 shares of a listed bank through her broker on NSE. The seller is someone she will never know. Her broker is a trading member. Her shares are credited to her account with her depository participant, which is linked to NSDL. Later she pledges these shares to take a loan from an NBFC.",
  "qs":[
   {"q":"Why does Meera not need to worry about the unknown seller defaulting?","o":["The broker personally guarantees it","The clearing corporation acts as counterparty through novation","SEBI pays for defaults","The bank whose shares she bought guarantees it"],"a":1,"w":"The clearing corporation is buyer to every seller and seller to every buyer."},
   {"q":"Which entity maintains Meera's investor-level securities account?","o":["NSDL","NSE","Her depository participant","The clearing bank"],"a":2,"w":"The DP keeps investor-level accounts. The depository keeps company-level accounts."},
   {"q":"In the pledge, Meera is the:","o":["Pledgee","Pledgor","Custodian","Underwriter"],"a":1,"w":"The borrower who pledges is the pledgor. The NBFC lender is the pledgee."},
   {"q":"After the pledge, Meera's shares:","o":["Move to the NBFC's account","Stay in her account, blocked","Are rematerialised","Are sold at once"],"a":1,"w":"Pledged demat shares stay in the pledgor's account but cannot be used for other transactions."}
  ]},
]
