CARDS = [
 {"f":"Industry versus business sector versus economic sector","b":"Industry: firms meeting the same need. Business sector: related industries. Economic sector: agriculture, manufacturing, utilities, services."},
 {"f":"First step in industry analysis","b":"<b>Defining the industry</b> the company operates in."},
 {"f":"NIC, GICS, NAICS","b":"NIC: India's National Industry Classification. GICS: Global Industry Classification Standard. NAICS: North American Industry Classification System."},
 {"f":"GICS structure (MSCI, March 2023)","b":"4 tiers: <b>11</b> sectors, <b>25</b> industry groups, <b>74</b> industries, <b>163</b> sub-industries."},
 {"f":"How should an analyst classify a company like PVR?","b":"Group it with businesses that share the <b>same driving factors</b>."},
 {"f":"Defensive industries","b":"Low <b>income elasticity</b>; little affected by economic cycles. Food, agricultural inputs, healthcare."},
 {"f":"Semi-cyclical industries","b":"Grow in expansion, fall in recession, but keep base demand. Consumer durables."},
 {"f":"Deep cyclical industries","b":"Extreme swings from economic and commodity cycles. Capital goods, steel."},
 {"f":"Top-down versus bottom-up market sizing","b":"Top-down: start from macro factors (patients &times; spend). Bottom-up: add up individual companies' data."},
 {"f":"Tyre sample: organised players Rs 24,000 crore, unorganised 20%. Market size?","b":"24,000 &divide; 0.8 = <b>Rs 30,000 crore</b>."},
 {"f":"Five drivers of secular trends","b":"Technology, change in income, demography, culture and tastes, regulation or policy."},
 {"f":"Secular trend from GST (book)","b":"More efficient logistics, so <b>lower demand for new commercial vehicles</b>."},
 {"f":"Value migration","b":"A shift that gives one party a long-term advantage at another's cost, moving shareholder value."},
 {"f":"Four kinds of value migration","b":"Across geographies, across industries, across the value chain, across companies in one industry (least common)."},
 {"f":"Value chain migration example (book)","b":"Cheap Indian telecom hurt telecom companies but helped <b>digital content</b> providers."},
 {"f":"Five stages of the business life cycle","b":"Pioneering, growth, mature, declining, reinvention and revival (rare)."},
 {"f":"Indian life cycle example (book)","b":"<b>Call taxis</b>: grew with phones and incomes, declined with app-based aggregators."},
 {"f":"Porter's five forces: horizontal and vertical (book)","b":"Horizontal: substitutes, new entrants, established rivals. Vertical: supplier power, buyer power."},
 {"f":"When was Porter's model developed?","b":"<b>1979</b>, by Dr. Michael Porter."},
 {"f":"Unattractive industries per Porter (book)","b":"Aviation, telecom, retail, textile, sugar, power."},
 {"f":"Attractive industries per Porter (book)","b":"Education, FMCG, healthcare, IT."},
 {"f":"High rivalry leads to...","b":"<b>Lower</b> pricing power and <b>lower</b> incomes."},
 {"f":"Four signs of high rivalry","b":"Many companies; little differentiation; same strategies (low price, long credit); low switching cost."},
 {"f":"Munger on price competition","b":"\"If only basis of competition in an industry is pricing, it is a self-defeating business.\""},
 {"f":"Industries with no threat of substitutes (book)","b":"Power, healthcare, education."},
 {"f":"Kodak's lesson","b":"Its engineers invented the digital camera, but it protected film, missed the substitute threat and went bankrupt."},
 {"f":"When is buyer power high?","b":"Strong competition among sellers; standardised products; close substitutes with low switching cost."},
 {"f":"When is supplier power high?","b":"Few suppliers and many buyers; critical inputs; differentiated products; no substitutes; high switching cost."},
 {"f":"Examples of strong supplier power (book)","b":"Sugarcane farmers (price set by government); OPEC in crude oil; hospitals and schools."},
 {"f":"Entry barriers","b":"Licensing, patents, huge specialised investment, strong brands, distribution, customer loyalty. Buffett's \"moat\"."},
 {"f":"Five features of an attractive industry","b":"Low competition, high barriers to entry, weak supplier power, weak buyer power, few substitutes."},
 {"f":"PESTLE","b":"Political, Economic, Socio-cultural, Technological, Legal, Environmental. External factors, mainly for choosing a country."},
 {"f":"STEEPLED","b":"PESTLE plus <b>Ethics</b> and <b>Demographics</b>."},
 {"f":"Legal factor examples of investor discomfort (book)","b":"Vodafone retrospective tax; cancelled telecom and mining licences."},
 {"f":"What does the BCG matrix analyse?","b":"Segments <b>within a business</b>, as a portfolio, through market growth and cash generation."},
 {"f":"BCG: Star","b":"Fast-growing market, large share. Book: <b>Cera Sanitaryware</b>."},
 {"f":"BCG: Cash cow","b":"Low growth, established share, steady cash. Book: <b>Navneet Publications</b>, <b>Colgate</b>."},
 {"f":"BCG: Question mark","b":"Fast-growing market, low share. Book: <b>Tata Nano</b> (failed), <b>Bajaj Pulsar</b> (succeeded)."},
 {"f":"BCG: Dog","b":"Slow growth, intense competition, low cash."},
 {"f":"SCP","b":"Structure (players, concentration), Conduct (pricing, seasonality, cyclicality), Performance (RoE, RoIC, WACC). An extension of Porter."},
 {"f":"Unit of pricing","b":"What a company treats as one unit when pricing. Starbucks prices per <b>patron</b>, not per cup."},
 {"f":"Three types of constraint","b":"Demand side, supply side, regulatory."},
 {"f":"Constraint to KPI","b":"Limited market: <b>penetration rate</b>. Limited capacity: <b>capacity utilisation</b>. Regulatory: regulators' metrics."},
 {"f":"Airline KPIs","b":"Passenger or cargo km; price per passenger or cargo km; capacity and occupancy rate."},
 {"f":"Bank and NBFC KPIs","b":"Net interest margin, capital adequacy, NPA ratio, deposit and loan growth, CRR and SLR, CASA ratio."},
 {"f":"IT services KPIs","b":"FTEs billed, revenue per FTE, bench strength, attrition, constant currency growth, customer concentration, million dollar clients."},
 {"f":"Media KPIs","b":"Readership, viewership, TRPs, site visitors; ad realisation per unit; content acquisition cost."},
 {"f":"Retail KPIs","b":"Number of stores; <b>same-store sales growth</b>."},
 {"f":"Telecom KPIs","b":"<b>ARPU</b>, churn rate, subscriber acquisition cost, market share."},
 {"f":"Kerala fat tax","b":"2017: <b>14.5%</b> additional tax on junk food."},
 {"f":"Direct versus indirect tax","b":"Direct: the person bearing it pays it (income tax). Indirect: seller collects, consumer bears (GST)."},
 {"f":"R&amp;D tax incentive (book)","b":"Claim <b>1.5 times</b> actual spend on certain scientific research."},
 {"f":"Deferred tax asset versus liability","b":"Asset: paying more tax now, less later. Liability: paying less now, more later."},
 {"f":"Corporate income tax rate (book)","b":"<b>30%</b>; <b>25%</b> if turnover below Rs 400 crore. Optional schemes 15% to 25%."},
 {"f":"MAT","b":"If tax is below <b>15% of book profits</b>, pay 15% + cess + surcharge. Excess is MAT credit."},
 {"f":"Surcharge rates, AY 2025-26 (book)","b":"<b>12%</b> above Rs 10 crore income; <b>7%</b> for Rs 1 to 10 crore; nil below Rs 1 crore. All to the central government."},
 {"f":"Cess (book)","b":"<b>4%</b> on tax plus surcharge, for health and education. Used only for its purpose."},
 {"f":"Which goods still have excise and VAT?","b":"Liquor, petrol, diesel."},
 {"f":"STT","b":"Securities Transaction Tax, paid on sale of securities. Discourages short-term trading; affects traders and brokers."},
 {"f":"Four sources for industry analysis","b":"Industry reports; annual reports (MD&amp;A); associations and trade bodies; relevant ministry."},
]

MCQS = [
 {"id":"6.1","q":"The tyre industry has three organised players and several unorganised players. About 20% of total sales come from the unorganised sector. The three major companies reported revenue of Rs 6,000 crore, Rs 8,000 crore and Rs 10,000 crore. Which is closest to a fair estimate of the overall market size?","o":["Rs 30,000 crore","Rs 48,000 crore","Rs 24,000 crore","Rs 36,000 crore"],"a":0,"w":"Book sample question. Organised = 24,000 = 80% of the market. 24,000 &divide; 0.8 = 30,000."},
 {"id":"6.2","q":"In an industry where rivalry is high, the end result will be ______ pricing power and ______ incomes for the industry participants.","o":["Lower; lower","Lower; higher","Higher; higher","Higher; lower"],"a":0,"w":"Book sample question."},
 {"id":"6.3","q":"Which of the following is considered an economic factor in PESTLE analysis?","o":["Forex reserves","Monetary policies of the RBI","Country's dependence on other countries for important natural resources","All of the above"],"a":3,"w":"Book sample question. All three are listed under economic factors."},
 {"id":"6.4","q":"Which of the following relates to industry structure in Structure Conduct Performance (SCP) analysis?","o":["Industry growth rate","Relationship among the various players in the industry","Market size","All of the above"],"a":3,"w":"Book sample question. Structure covers competitive intensity, concentration, relationships, market size and growth."},
 {"id":"6.5","q":"Financial services, comprising insurance, banking, credit rating and investment banking, is an example of a(n):","o":["Business sector","Industry","Economic sector","Sub-industry"],"a":0,"w":"A business sector groups related industries. Economic sectors are agriculture, manufacturing, utilities, services."},
 {"id":"6.6","q":"The National Industry Classification (NIC) system is used in:","o":["India","The United States","Europe","All MSCI indices"],"a":0,"w":"NAICS is North American; GICS is global."},
 {"id":"6.7","q":"GICS, as of March 2023, has how many sectors?","o":["11","25","74","163"],"a":0,"w":"11 sectors, 25 industry groups, 74 industries, 163 sub-industries."},
 {"id":"6.8","q":"According to the book, the most appropriate way to classify a company into an industry is by:","o":["The common factors that drive its business","The name of its main product","The largest shareholder","Its stock exchange listing"],"a":0,"w":"The PVR example: classify by what drives the business."},
 {"id":"6.9","q":"Industries whose products have low income elasticity and are barely affected by economic cycles are called:","o":["Defensive industries","Deep cyclical industries","Semi-cyclical industries","Sunrise industries"],"a":0,"w":"Food, agricultural inputs and healthcare are the book's examples."},
 {"id":"6.10","q":"According to the book, which industry is an example of a deep cyclical industry?","o":["Capital goods","Healthcare","Food","Agricultural inputs"],"a":0,"w":"Capital goods and steel swing hard with economic and commodity cycles."},
 {"id":"6.11","q":"The consumer durables industry has exhibited the traits of a ______ industry.","o":["Semi-cyclical","Defensive","Deep cyclical","Declining"],"a":0,"w":"It grows in expansion and falls in recession but keeps a base level of demand."},
 {"id":"6.12","q":"Estimating a therapy's market by multiplying the number of patients by the average spend per patient is an example of:","o":["Top-down market sizing","Bottom-up market sizing","Value migration","SCP analysis"],"a":0,"w":"Bottom-up would add up the therapy revenue of each hospital."},
 {"id":"6.13","q":"Which of the following is NOT one of the drivers of secular trends listed in the book?","o":["Quarterly inventory adjustments","Technological advancement","Demographic changes","Changes in regulation or government policy"],"a":0,"w":"Inventory adjustments drive short inventory cycles, not secular trends."},
 {"id":"6.14","q":"According to the book, the ageing population in Japan resulted in:","o":["A decrease in per capita consumption of beer","A rise in demand for western clothing","A shift to electric vehicles","Growth of call taxis"],"a":0,"w":"An example of demographic change driving a secular trend."},
 {"id":"6.15","q":"The advent of digital cameras causing the decline of the film roll industry is an example of:","o":["Cross-industry value migration","Geographic value migration","Migration across the value chain","Seasonal trend"],"a":0,"w":"One industry gained at the cost of another."},
 {"id":"6.16","q":"Falling mobile service prices hurt Indian telecom companies but helped digital content providers. This is value migration:","o":["Across the value chain","Across geographies","Across companies in the same industry","Across economic cycles"],"a":0,"w":"Value moved between different levels of the value chain."},
 {"id":"6.17","q":"In which stage of the business life cycle have most potential customers already adopted the product?","o":["Mature","Pioneering","Growth","Reinvention"],"a":0,"w":"In the mature stage, few new customers are left."},
 {"id":"6.18","q":"Porter's five forces model was developed in:","o":["1979","1969","1989","1999"],"a":0,"w":"By Dr. Michael Porter in 1979."},
 {"id":"6.19","q":"As per the book, which of the following are the vertical forces in Porter's model?","o":["Bargaining power of suppliers and bargaining power of customers","Threat of substitutes and threat of new entrants","Threat of established rivals and threat of substitutes","Threat of new entrants and bargaining power of suppliers"],"a":0,"w":"The book lists 3 horizontal forces (substitutes, new entrants, rivals) and 2 vertical ones (suppliers, customers)."},
 {"id":"6.20","q":"As per the book, which of these industries is termed unattractive under Porter's model?","o":["Aviation","Education","FMCG","IT"],"a":0,"w":"Aviation, telecom, retail, textile, sugar and power are termed unattractive."},
 {"id":"6.21","q":"Which of the following indicates high industry rivalry?","o":["Low switching cost for customers","Strong product differentiation","Few companies in the segment","High entry barriers"],"a":0,"w":"The other three reduce rivalry."},
 {"id":"6.22","q":"According to the book, which of the following industries has no threat of substitutes?","o":["Power","Film rolls","Typewriters","Telegram"],"a":0,"w":"Power, healthcare and education. The others were replaced by substitutes."},
 {"id":"6.23","q":"Buyers' bargaining power in an industry would be high when:","o":["Products are standardised with little differentiation","There are very few sellers","Switching cost for customers is very high","Products have no substitutes"],"a":0,"w":"Standard products, strong competition and easy switching give buyers power."},
 {"id":"6.24","q":"In the Indian sugar industry, the price of sugarcane is decided by the government after considering farmers' views. This indicates:","o":["Strong bargaining power of suppliers","Strong bargaining power of buyers","High threat of substitutes","Low entry barriers"],"a":0,"w":"The input cost depends on what the suppliers demand."},
 {"id":"6.25","q":"Warren Buffett's \"economic castles protected by unbreachable moats\" refers to businesses with:","o":["High barriers to entry","High industry rivalry","Strong supplier power","Many substitutes"],"a":0,"w":"Moats keep new entrants out and give pricing power."},
 {"id":"6.26","q":"Which is NOT a feature of an attractive industry from the shareholders' perspective?","o":["Strong buyers' bargaining power","Low competition","High barriers to entry","Few substitutes"],"a":0,"w":"An attractive industry has weak buyer and supplier power."},
 {"id":"6.27","q":"PESTLE extended with Ethics and Demographics is called:","o":["STEEPLED","SWOT","SCP","BCG"],"a":0,"w":"STEEPLED adds the two extra factors."},
 {"id":"6.28","q":"According to the book, PESTLE analysis is done mostly from the perspective of:","o":["A business choosing a country in which to set up a unit","A bank assessing a loan","An investor valuing a single share","A regulator setting rules"],"a":0,"w":"It analyses external environmental factors across countries."},
 {"id":"6.29","q":"The Vodafone retrospective tax case is cited in the book under which PESTLE factor?","o":["Legal","Political","Technological","Environmental"],"a":0,"w":"It is an example of legal discomfort to investors."},
 {"id":"6.30","q":"In the BCG matrix, a segment with low market growth but a large, established market share that generates steady cash is a:","o":["Cash cow","Star","Question mark","Dog"],"a":0,"w":"Book examples: Navneet Publications and Colgate."},
 {"id":"6.31","q":"As per the book, Tata Nano and Bajaj Pulsar are examples of which BCG category?","o":["Question mark","Star","Cash cow","Dog"],"a":0,"w":"Both started in fast-growing markets with low share; Nano failed, Pulsar succeeded."},
 {"id":"6.32","q":"Which of the following is studied under 'performance' in SCP analysis?","o":["Return on equity and return on invested capital","Number of players in the industry","Whether the business is seasonal","Threat from substitute products"],"a":0,"w":"Performance covers RoE, RoIC, WACC. The others are structure or conduct."},
 {"id":"6.33","q":"Whether a business is seasonal or year-round, commoditised or branded, is studied under which part of SCP?","o":["Conduct","Structure","Performance","None of the above"],"a":0,"w":"Conduct covers how businesses behave on pricing and innovation."},
 {"id":"6.34","q":"If an industry's growth is limited by the number of target customers, the key metric to track is:","o":["Penetration rate","Capacity utilisation","Revenue per employee","Bench strength"],"a":0,"w":"Demand constraint: penetration rate. Capacity constraint: utilisation rate."},
 {"id":"6.35","q":"Revenue per employee is a useful KPI for which type of business?","o":["A BPO service provider","A steel plant","A cement manufacturer","An oil refinery"],"a":0,"w":"BPOs bill by headcount. Capital-intensive manufacturers are poorly measured this way."},
 {"id":"6.36","q":"CASA ratio and NPA ratio are key performance indicators for:","o":["Banks and NBFCs","Airlines","Retailers","Media companies"],"a":0,"w":"Other bank KPIs: net interest margin, capital adequacy, deposit and loan growth."},
 {"id":"6.37","q":"Same-store sales growth is a key metric for which industry?","o":["Retail","Telecom","IT services","Capital goods"],"a":0,"w":"Retail growth depends on its store network."},
 {"id":"6.38","q":"ARPU and subscriber churn rate are key metrics for:","o":["Telecom and internet service providers","Banks","Airlines","Consumer goods"],"a":0,"w":"In telecom the subscriber is the unit of pricing."},
 {"id":"6.39","q":"An airline carries 200 passengers each on 5 flights of 1,000 km. The passenger km is:","o":["10,00,000","1,000","2,00,000","5,000"],"a":0,"w":"Passengers &times; distance = (200 &times; 5) &times; 1,000 = 10,00,000 passenger km."},
 {"id":"6.40","q":"In a direct tax:","o":["The person who bears the tax also pays it to the government","The seller collects it from the buyer","The end consumer bears it but does not pay it","It is charged only on imports"],"a":0,"w":"Income tax is the main example. GST is indirect."},
 {"id":"6.41","q":"As per the book, companies in India can claim ______ times the actual expenditure on certain scientific research as an expense.","o":["1.5","2","1.25","3"],"a":0,"w":"This is used to promote research and development."},
 {"id":"6.42","q":"A company pays more tax today than its reported profits suggest, and its future taxes will reduce. This creates a:","o":["Deferred tax asset","Deferred tax liability","MAT liability","Cess"],"a":0,"w":"That is a deferred tax asset. The opposite case, paying less now and more later, creates a deferred tax liability."},
 {"id":"6.43","q":"A company's taxable profit is Rs 100 crore, taxed at 30%. Income is above Rs 10 crore. Using the book's surcharge and cess rates, total tax is about:","o":["Rs 34.94 crore","Rs 30 crore","Rs 33.60 crore","Rs 46 crore"],"a":0,"w":"Tax 30; surcharge 12% of 30 = 3.6; cess 4% of 33.6 = 1.344. Total 34.944."},
 {"id":"6.44","q":"Under MAT, if the income tax payable is less than ______ of book profits, the company pays that percentage of book profits plus cess and surcharge.","o":["15%","25%","30%","12%"],"a":0,"w":"The excess paid can be carried as MAT credit."},
 {"id":"6.45","q":"Which statement about surcharge is correct as per the book?","o":["The entire surcharge revenue goes to the central government","It is shared equally with state governments","It is charged on turnover","It is used only for education"],"a":0,"w":"Income tax is shared with states; surcharge is not. Cess is for specific purposes."},
 {"id":"6.46","q":"Excise duty and VAT currently apply only to:","o":["Liquor, petrol and diesel","All imported goods","Services","Gold and silver"],"a":0,"w":"These products are outside GST."},
 {"id":"6.47","q":"Securities Transaction Tax (STT) mainly:","o":["Discourages short-term trading","Encourages frequent trading","Applies to real estate purchases","Is paid on new vehicles"],"a":0,"w":"It reduces sale proceeds, so it affects traders and brokers."},
 {"id":"6.48","q":"A change in stamp duty affects which of the following, as per the book?","o":["Real estate and stock broking firms","Airlines","Software exporters","Hospitals"],"a":0,"w":"It changes the cost of buying assets and the value realised on selling them."},
 {"id":"6.49","q":"Which section of a company's annual report is listed as a source for industry analysis?","o":["Management Discussion and Analysis","Auditor's signature page","Notice of AGM","Share transfer form"],"a":0,"w":"MD&amp;A discusses industry conditions and KPIs."},
]

CASES = [
 {"id":"C10","title":"Should Meena invest in airlines or education?","text":"Meena compares two industries. Airlines: many carriers, similar service, fares matched daily, passengers switch easily, fuel supplied by a few oil companies. Private education: demand is growing, many licences are needed to open an institute, quality institutes are few, and students have little bargaining power.",
  "qs":[
   {"q":"Which Porter force is clearly strong for airlines from the description?","o":["Industry rivalry","Threat of new entrants being low","Weak supplier power","Weak buyer power"],"a":0,"w":"Many players, little differentiation, same pricing strategy and low switching cost: high rivalry."},
   {"q":"Many licences needed to open an institute are an example of:","o":["High barriers to entry","High threat of substitutes","High buyer power","Low rivalry caused by price wars"],"a":0,"w":"Licensing is a classic entry barrier."},
   {"q":"Fuel supplied by a few oil companies suggests, for airlines:","o":["Strong supplier bargaining power","Weak supplier bargaining power","Low threat of substitutes","High entry barriers"],"a":0,"w":"Few suppliers of a critical input means strong supplier power."},
   {"q":"Which conclusion matches the book?","o":["Education is attractive and aviation is unattractive for shareholders","Aviation is attractive and education is unattractive","Both are equally attractive","Neither can be judged with Porter's model"],"a":0,"w":"The book uses education as its attractive example and lists aviation as unattractive."},
  ]},
 {"id":"C11","title":"Profiling Speedline Telecom","text":"Rahul is building an industry profile for Speedline Telecom, a mobile operator. Mobile prices fell sharply after a price war, and data use has surged, helping video apps. Speedline also owns a small, fast-growing fibre business with low market share, and a large, slow-growing landline business that still generates steady cash. Its taxable profit is Rs 50 crore.",
  "qs":[
   {"q":"Which KPIs should Rahul track first for the mobile business?","o":["ARPU and subscriber churn","Same-store sales growth","Passenger km","CASA ratio"],"a":0,"w":"The subscriber is the unit of pricing in telecom."},
   {"q":"Value moving from telecom companies to video apps is value migration:","o":["Across the value chain","Across geographies","Across industries due to regulation","Across economic cycles"],"a":0,"w":"The book uses exactly this Indian telecom example."},
   {"q":"In the BCG matrix, the fibre business and the landline business are respectively a:","o":["Question mark and cash cow","Star and dog","Cash cow and question mark","Dog and star"],"a":0,"w":"Fast growth, low share = question mark. Slow growth, established share, steady cash = cash cow."},
   {"q":"Which surcharge rate applies to Speedline under the book's figures?","o":["12%","7%","Nil","4%"],"a":0,"w":"Income above Rs 10 crore attracts 12%. 4% is the cess."},
  ]},
]

DATA = {"id":"ch06","short":"Ch6","title":"Chapter 6: Industry analysis","cards":CARDS,"mcqs":MCQS,"cases":CASES}
