def _table(head, rows):
    h = "".join(f"<th>{x}</th>" for x in head)
    b = ""
    for r in rows:
        if len(r) == 1:
            b += f'<tr><th colspan="{len(head)}">{r[0]}</th></tr>'
        else:
            b += "<tr><th>" + r[0] + "</th>" + "".join(f"<td>{x}</td>" for x in r[1:]) + "</tr>"
    return f'<div class="scroll"><table class="cmp"><thead><tr>{h}</tr></thead><tbody>{b}</tbody></table></div>'

# Book case study 5 (page 183): Company A and Company B, Rs lakhs
_AB = _table(["Rs lakhs", "A 2XX8", "A 2XX9", "B 2XX8", "B 2XX9"], [
 ["Income statement summary"],
 ["Operating revenue", "8,642.0", "9,100.0", "6,427.0", "7,524.0"],
 ["Cost of raw materials", "3,024.7", "3,003.0", "2,185.2", "2,558.2"],
 ["Changes in inventory of finished goods and WIP", "120.0", "-35.0", "160.0", "140.0"],
 ["Employee cost", "976.5", "1,055.6", "687.7", "880.3"],
 ["Depreciation and amortisation", "240.7", "241.2", "213.3", "218.6"],
 ["Finance cost", "175.8", "180.4", "184.8", "195.2"],
 ["Other expenses", "557.2", "561.7", "596.3", "602.1"],
 ["Profit before tax", "3,547.1", "4,093.1", "2,399.7", "2,929.6"],
 ["(-) Tax expense", "1,170.5", "1,330.0", "791.9", "966.8"],
 ["Profit after tax", "2,376.5", "2,763.1", "1,607.8", "1,962.8"],
 ["Balance sheet summary"],
 ["Fixed assets", "2,407.0", "2,412.0", "2,133.0", "2,186.0"],
 ["Net working capital", "2,160.5", "2,275.0", "1,606.8", "1,881.0"],
 ["Total assets", "4,567.5", "4,687.0", "3,739.8", "4,067.0"],
 ["Debt", "1,598.6", "1,640.5", "1,540.0", "1,626.8"],
 ["Equity", "2,968.9", "3,046.6", "2,199.8", "2,440.2"],
 ["Total debt and equity", "4,567.5", "4,687.0", "3,739.8", "4,067.0"],
])

# Book case study 6 (page 185): one company, Rs lakhs
_ONE = _table(["Rs lakhs", "2XX6", "2XX7"], [
 ["Income statement summary"],
 ["Operating revenue", "8,642.0", "9,100.0"],
 ["Cost of raw materials", "3,024.7", "3,003.0"],
 ["Changes in inventory of finished goods and WIP", "120.0", "-35.0"],
 ["Employee cost", "976.5", "1,055.6"],
 ["Depreciation and amortisation", "240.7", "241.2"],
 ["Finance cost", "175.8", "180.4"],
 ["Other expenses", "557.2", "561.7"],
 ["Profit before tax", "3,547.1", "4,093.1"],
 ["(-) Tax expense", "1,170.5", "1,330.0"],
 ["Profit after tax", "2,376.5", "2,763.1"],
 ["Balance sheet summary"],
 ["Fixed assets", "2,407.0", "2,412.0"],
 ["Net working capital", "2,160.5", "2,275.0"],
 ["Total assets", "4,567.5", "4,687.0"],
 ["Debt", "1,598.6", "1,640.5"],
 ["Equity", "2,968.9", "3,046.6"],
 ["Total debt and equity", "4,567.5", "4,687.0"],
])

_SHARMA = _table(["Rs crore", "Value"], [
 ["Net sales", "1,000"], ["EBIT", "90"], ["Interest expense", "30"], ["Net profit (PAT)", "40"],
 ["Current assets (of which inventory 200)", "600"], ["Current liabilities", "400"],
 ["Total debt", "500"], ["Net worth", "400"], ["Total assets", "1,000"],
])

CARDS = [
 {"f":"Which rules govern the format of Indian financial statements?","b":"<b>Schedule III</b> of the Companies Act, 2013 and <b>Ind AS 1</b>."},
 {"f":"Complete set of financial statements under Ind AS 1","b":"Balance sheet, statement of profit and loss (with OCI), statement of changes in equity, cash flow statement, notes."},
 {"f":"Minimum comparative period","b":"At least <b>one prior period</b> for every statement."},
 {"f":"Who does not follow the Schedule III format?","b":"<b>Banks, insurers and utilities</b>: they use formats set by their regulators."},
 {"f":"Standalone versus consolidated","b":"Standalone: one legal entity. Consolidated: all companies controlled by the parent, combined as one group."},
 {"f":"When does a company control another?","b":"More than 50% of voting rights, or the right to appoint a majority of the board, or de facto control (Ind AS 110)."},
 {"f":"Which is usually preferred for equity analysis?","b":"<b>Consolidated</b>: more holistic. Check standalone too if subsidiaries cannot pay dividends to the parent."},
 {"f":"SEBI publishing rules, as per the book","b":"Consolidated statements <b>annually</b>; standalone results <b>quarterly</b>. Quarterly consolidated is voluntary."},
 {"f":"Can a company show its own brand as an asset?","b":"<b>No.</b> Only assets measurable in money and paid for. Internally developed software is an exception that can be shown."},
 {"f":"Current versus non-current asset","b":"Current: benefit within one operating cycle (usually one year). Non-current: everything else, usually over a year."},
 {"f":"PPE valuation","b":"Historical cost less accumulated depreciation. Ind AS 16 allows revaluation, applied to a whole asset class."},
 {"f":"Goodwill","b":"Price paid for a business above the fair value of net assets. Tested for impairment. Book: Tigo Rwanda, 3,200 &minus; 2,838 = Rs 362 crore."},
 {"f":"Paying less than fair value of net assets acquired","b":"The difference goes to <b>capital reserve</b> under equity."},
 {"f":"Investments in JVs and associates are shown using...","b":"The <b>equity method</b>."},
 {"f":"Inventory valuation","b":"<b>Lower of cost or market value.</b>"},
 {"f":"Receivables are shown...","b":"Net of <b>provision for doubtful debts</b>."},
 {"f":"Capital and revaluation reserves","b":"Surplus from showing assets above purchase price. Usually <b>not available for dividends</b>."},
 {"f":"Non-controlling (minority) interest","b":"Outside shareholders' share in a subsidiary. Appears <b>only in consolidated</b> statements."},
 {"f":"Lease liability","b":"Right to use an asset for more than a year. Analysts often treat it as <b>debt</b>."},
 {"f":"Deferred revenue (book example)","b":"6-month pack for Rs 1,200, 5 months left: Rs 200 revenue, Rs <b>1,000</b> deferred."},
 {"f":"Provision versus reserve","b":"Provision: for a <b>specific</b> obligation not fully quantified (retirement benefits, warranty). Reserve: no specific obligation."},
 {"f":"Total debt (book)","b":"Long-term debt + current portion of long-term debt + short-term debt + finance lease obligations + accrued interest."},
 {"f":"Net working capital (accountant's)","b":"Current assets &minus; current liabilities."},
 {"f":"Core working capital","b":"Inventory + trade receivables &minus; trade payables (book suggests adding a reasonable cash balance)."},
 {"f":"Why does a company need working capital, per the book?","b":"It spends first and waits for customers to pay later. \"Day-to-day needs\" is a misnomer."},
 {"f":"Cost of raw materials consumed","b":"Purchases + opening stock &minus; closing stock."},
 {"f":"Purchase of stock-in-trade","b":"Goods bought and sold without further processing (most retail purchases)."},
 {"f":"Depreciation method under Ind AS 16","b":"Should reflect how the asset is used, for example a cab fleet by distance."},
 {"f":"Exceptional items","b":"Income or expenses outside the normal course of business: natural calamity losses, one-time regulatory charges."},
 {"f":"Three parts of tax expense","b":"Current tax, MAT, deferred tax. Deferred tax has no cash impact."},
 {"f":"Basic versus diluted EPS","b":"Diluted assumes in-the-money warrants, ESOPs and convertibles are converted. Same as basic for a <b>loss-making</b> company."},
 {"f":"Five OCI items (book)","b":"Revaluation surplus changes; defined benefit remeasurement; foreign operation translation; fair value changes through OCI; effective hedge gains or losses."},
 {"f":"Single-step versus multi-step P&amp;L","b":"Single-step: all income minus all expenses = PBT. Multi-step: shows intermediate profits like EBITDA."},
 {"f":"Why can't most Indian companies' gross profit be computed?","b":"They disclose only raw material costs, not other direct costs."},
 {"f":"Why is EBITDA good for comparing firms?","b":"Unaffected by capital structure (interest) and infrastructure and accounting choices (depreciation)."},
 {"f":"EBIT is also called...","b":"<b>Operating profit.</b> Used for interest coverage and free cash flow to the firm."},
 {"f":"Adjusted PAT","b":"PAT without exceptional items, adjusted for their tax impact."},
 {"f":"Accrual basis","b":"Income when earned, expenses when incurred, not when cash moves. So profit and cash differ."},
 {"f":"Three cash flow types and signs","b":"Operating: from the business. Investing: buying assets negative, selling positive. Financing: borrowing or issuing equity positive, repaying negative."},
 {"f":"Kingfisher Airlines lesson","b":"Years of negative operating cash flow; borrowed to pay interest until lenders stopped."},
 {"f":"Four cash flow rules (book)","b":"Net cash flow can deceive; analyse each stream separately; focus on sustainable recurring flows; adjust non-recurring items."},
 {"f":"Frequent changes in accounting policy suggest...","b":"A reason for <b>suspicion</b> of manipulation."},
 {"f":"Contingent liabilities","b":"Depend on an uncertain future event. <b>Not recorded</b> in the accounts; disclosed in notes. Judge their size."},
 {"f":"Off-balance sheet items (book)","b":"Operating leases, contingent liabilities, derivative contracts."},
 {"f":"Signs of a value-creating company (8.8)","b":"Consistent growth in sales, profit and net worth; falling debt; better margins; rising RoNW."},
 {"f":"Three kinds of audit report (book)","b":"<b>Clean</b> (no issues), <b>disclaimer</b> (could not verify), <b>qualified</b> (not true and fair)."},
 {"f":"Three purposes of ratio analysis","b":"Descriptive, diagnostic, predictive."},
 {"f":"EBITDA margin","b":"EBITDA &divide; Net sales. Bharti FY 2019: <b>32.2%</b>."},
 {"f":"PAT margin","b":"PAT &divide; Net sales."},
 {"f":"ROE","b":"PAT &divide; Net worth (use average net worth). \"Single most important parameter\" for equity investors."},
 {"f":"ROCE","b":"EBIT &divide; Capital employed. Capital employed = total assets &minus; non-interest-bearing current liabilities, or equity + debt."},
 {"f":"D/E ratio and benchmark","b":"Total adjusted debt &divide; Net worth. Most conservative benchmark: <b>1 or less</b>."},
 {"f":"Interest coverage ratio","b":"<b>EBIT &divide; Interest expense.</b> Below 1: earnings do not cover interest."},
 {"f":"Current ratio","b":"Current assets &divide; Current liabilities. Also called working capital ratio."},
 {"f":"Quick ratio","b":"(Current assets &minus; <b>Inventories</b>) &divide; Current liabilities."},
 {"f":"Is a current ratio below 1 always bad?","b":"<b>No.</b> If customers pay cash and suppliers give credit, customers are funding working capital."},
 {"f":"Receivable turnover","b":"Revenue &divide; Average receivables. Higher is better."},
 {"f":"Payable turnover","b":"Purchases &divide; Accounts payable. Low: long supplier credit (strength, or lack of cash)."},
 {"f":"Asset turnover","b":"Net sales &divide; Total assets."},
 {"f":"Inventory turnover","b":"Sales &divide; Inventory. High for FMCG, low for capital goods."},
 {"f":"DuPont formula","b":"ROE = Net profit margin &times; Asset turnover &times; Equity multiplier (Assets &divide; Equity)."},
 {"f":"DuPont: HighLevCo versus LowLevCo (book)","b":"HighLevCo ROE 92.3% (20%, 2.3x, 2.0x). LowLevCo 52.4% (22%, 2.4x, 1.0x). LowLevCo operates better; its lower ROE is only from no debt."},
 {"f":"Suzlon lesson (8.13)","b":"Past behaviour may not represent the future: competition ended its pricing power."},
 {"f":"Which share issues dilute existing holders?","b":"All except rights issues, which dilute only those who do not subscribe."},
 {"f":"Preferential allotment at a premium","b":"Value-accretive to minority shareholders: less dilution risk."},
 {"f":"QIP signal","b":"Dilutes, but likely shows institutional confidence in fundamentals."},
 {"f":"Predictable dividends with interims (book examples)","b":"Mature defensive companies such as <b>Colgate Palmolive</b> and <b>Britannia</b>."},
 {"f":"High-growth company raises its dividend","b":"May signal fewer growth opportunities ahead."},
 {"f":"Peter Lynch on insiders","b":"Insiders sell for many reasons; if they are <b>buying</b>, there is only one: they expect big profits."},
]

MCQS = [
 {"id":"8.1","q":"Which of the following items is found in an income statement?","o":["Changes in inventory of finished goods and work in progress","Change in accounts receivables","Changes in long-term debt","None of the above"],"a":0,"w":"Book sample question. Changes in inventory of WIP and finished goods is a P&amp;L expense line. The others are balance sheet or cash flow items."},
 {"id":"8.2","q":"Which section of the cash flow statement provides information about the amount of funds a company borrowed during the preceding year?","o":["Cash flow from financing activities","Cash flow from operating activities","Cash flow from investing activities","Cash flows from net operations"],"a":0,"w":"Book sample question. Borrowing and issuing equity are financing cash flows."},
 {"id":"8.3","q":"Which of the following measures the ability of a company to satisfy its short-term obligations as and when they come due?","o":["Current ratio","Return on equity","Return on capital employed","Inventory turnover ratio"],"a":0,"w":"Book sample question. Current ratio is a liquidity ratio."},
 {"id":"8.4","q":"The P/E ratio of a business is 10, its P/BV ratio is 5, book value per share is Rs 15 and there are 10,000 shares outstanding. What is the return on equity?","o":["50%","25%","75%","20%"],"a":0,"w":"Book sample question. Price = 5 &times; 15 = 75. EPS = 75 &divide; 10 = 7.5. ROE = EPS &divide; BV = 7.5 &divide; 15 = 50%. The number of shares is not needed."},
 {"id":"8.5","q":"Which of the following is NOT part of a complete set of financial statements under Ind AS 1?","o":["Directors' report","Balance sheet","Statement of changes in shareholders' equity","Cash flow statement"],"a":0,"w":"Ind AS 1 lists the balance sheet, profit and loss (with OCI), changes in equity, cash flow and notes."},
 {"id":"8.6","q":"Ind AS 1 requires the statement of profit and loss to also include:","o":["Other comprehensive income","The directors' remuneration policy","The auditor's report","Share price history"],"a":0,"w":"OCI is shown below net profit."},
 {"id":"8.7","q":"Banking, insurance and utility companies prepare their financial statements in the format prescribed by:","o":["Their respective industry regulators","Schedule III of the Companies Act, 2013","The stock exchange","The statutory auditor"],"a":0,"w":"The Schedule III format applies to all other industries."},
 {"id":"8.8","q":"According to the book, a company controls another company if it:","o":["Owns more than 50% of the voting rights or has the right to appoint a majority of the board","Owns at least 10% of the shares","Is its largest supplier","Has a seat on its board"],"a":0,"w":"Even below 50%, de facto control over strategy and operations requires consolidation under Ind AS 110."},
 {"id":"8.9","q":"As per the book, SEBI regulations require listed companies to publish:","o":["Consolidated statements annually and standalone results quarterly","Consolidated results quarterly only","Standalone statements annually only","Neither standalone nor consolidated results"],"a":0,"w":"Quarterly consolidated results are voluntary, as per the book."},
 {"id":"8.10","q":"When is it especially important to also analyse a parent company's standalone financial position?","o":["When subsidiaries cannot pay dividends to the parent due to capital controls or debt covenants","When the parent has no subsidiaries","When the group publishes quarterly consolidated results","Never; consolidated statements are always enough"],"a":0,"w":"Then the parent must be able to stand on its own in a crisis."},
 {"id":"8.11","q":"Which of the following cannot be recognised as an asset on the balance sheet?","o":["A self-generated brand name","An acquired patent","Internally developed software","An acquired brand"],"a":0,"w":"Self-generated assets cannot be shown, except that internally developed software can be."},
 {"id":"8.12","q":"A company pays Rs 500 crore to acquire 100% of a business whose net assets have a fair value of Rs 420 crore. The goodwill recognised is:","o":["Rs 80 crore","Rs 420 crore","Rs 500 crore","Rs 920 crore"],"a":0,"w":"Goodwill = consideration &minus; fair value of net assets = 500 &minus; 420 = 80. Same logic as the book's Tigo Rwanda example."},
 {"id":"8.13","q":"If a company pays less than the fair value of net assets taken over, the difference is taken to:","o":["Capital reserve","Goodwill","Revenue","Deferred tax"],"a":0,"w":"It goes to capital reserve under equity."},
 {"id":"8.14","q":"Inventory is shown in the balance sheet at:","o":["Cost price or market value, whichever is lower","Market value always","Selling price","Cost price plus profit margin"],"a":0,"w":"Lower of cost or market value."},
 {"id":"8.15","q":"Investments in joint ventures and associates are reported under the:","o":["Equity method","Revaluation model","Straight-line method","Cost of carry method"],"a":0,"w":"The carrying amount is adjusted for the investor's share of profit and OCI, and reduced by dividends."},
 {"id":"8.16","q":"Non-controlling (minority) interest appears in:","o":["Consolidated financial statements only","Standalone financial statements only","Both standalone and consolidated statements","Neither"],"a":0,"w":"It is the outside shareholders' share of a subsidiary's equity."},
 {"id":"8.17","q":"A customer buys a 12-month prepaid pack for Rs 2,400. After 3 months, the deferred revenue shown is:","o":["Rs 1,800","Rs 600","Rs 2,400","Rs 200"],"a":0,"w":"9 months of service remain: 2,400 &times; 9/12 = 1,800. Same logic as the book's 6-month pack example."},
 {"id":"8.18","q":"An amount set aside to meet a specific obligation that cannot yet be fully quantified, such as retirement benefits, is a:","o":["Provision","General reserve","Revaluation reserve","Share premium"],"a":0,"w":"Reserves are set aside without a specific obligation."},
 {"id":"8.19","q":"Which of the following is NOT included in total debt as calculated in the book?","o":["Trade payables","Current portion of long-term debt","Financial lease obligations","Accrued interest"],"a":0,"w":"Total debt = long-term debt + current portion + short-term debt + finance leases + accrued interest. Payables carry no interest."},
 {"id":"8.20","q":"Inventory Rs 50 crore, trade receivables Rs 120 crore, trade payables Rs 90 crore, cash Rs 30 crore. Core working capital (as usually calculated in the book) is:","o":["Rs 80 crore","Rs 110 crore","Rs 260 crore","Rs 170 crore"],"a":0,"w":"Inventory + receivables &minus; payables = 50 + 120 &minus; 90 = 80. The usual calculation leaves out cash."},
 {"id":"8.21","q":"Opening raw material stock Rs 40 lakh, purchases Rs 300 lakh, closing stock Rs 60 lakh. Cost of raw materials consumed is:","o":["Rs 280 lakh","Rs 320 lakh","Rs 300 lakh","Rs 400 lakh"],"a":0,"w":"Purchases + opening stock &minus; closing stock = 300 + 40 &minus; 60 = 280."},
 {"id":"8.22","q":"Most of the purchases in the retail sector are shown under:","o":["Purchase of stock-in-trade","Cost of raw materials","Capital work in progress","Finance cost"],"a":0,"w":"Stock-in-trade is goods sold without further processing."},
 {"id":"8.23","q":"According to Ind AS 16, the method of depreciation should take into consideration:","o":["The way the asset is used","Only the tax rate","The share price","The auditor's preference"],"a":0,"w":"The book's example: a cab operator may depreciate by distance travelled."},
 {"id":"8.24","q":"For a loss-making company, diluted EPS is:","o":["The same as basic EPS","Always higher than basic EPS","Always zero","Not reported"],"a":0,"w":"The book states that for loss-making companies the two are one and the same."},
 {"id":"8.25","q":"A company earns net profit of Rs 22 lakh. It had 10 lakh shares all year and issued 2 lakh more exactly halfway through the year. Basic EPS is:","o":["Rs 2.00","Rs 1.83","Rs 2.20","Rs 1.10"],"a":0,"w":"Weighted average shares = 10 + 2 &times; 0.5 = 11 lakh. EPS = 22 &divide; 11 = Rs 2.00."},
 {"id":"8.26","q":"Which of the following is an item of other comprehensive income?","o":["Re-measurement gain or loss on defined benefit plans","Revenue from operations","Finance cost","Purchase of stock-in-trade"],"a":0,"w":"OCI bypasses the P&amp;L and mostly covers non-operating value changes."},
 {"id":"8.27","q":"Why is it generally not possible to calculate gross profit for Indian companies?","o":["They do not separately disclose direct costs other than raw materials","They do not report revenue","Gross profit is banned by Ind AS","They report only cash flows"],"a":0,"w":"Raw material cost is disclosed, but other direct costs are not."},
 {"id":"8.28","q":"EBITDA is an appropriate metric for comparing two firms because it is:","o":["Not affected by capital structure and infrastructure choices","Always equal to cash flow","Calculated after tax","Required by SEBI"],"a":0,"w":"Interest depends on funding choices; depreciation on infrastructure and accounting choices."},
 {"id":"8.29","q":"EBIT is referred to as:","o":["Operating profit","Gross profit","Net profit","Cash profit"],"a":0,"w":"It is also the numerator of the interest coverage ratio."},
 {"id":"8.30","q":"While calculating adjusted profit after tax, analysts remove exceptional items and also factor in:","o":["Their tax impact","Their effect on share price","Dividends paid","The auditor's fees"],"a":0,"w":"Exceptional items affect tax too, so the tax impact must be adjusted."},
 {"id":"8.31","q":"A business buys goods for Rs 80,000 in cash and sells them for Rs 1,00,000 on credit. At this point the business has:","o":["A profit of Rs 20,000 but no cash from the sale","A cash gain of Rs 20,000","A loss of Rs 80,000","Neither profit nor cash"],"a":0,"w":"The book's example of accrual profit without cash. If the customer never pays, even the Rs 80,000 is lost."},
 {"id":"8.32","q":"A company buys new machinery for cash. In the cash flow statement this is a:","o":["Negative investing cash flow","Positive investing cash flow","Negative financing cash flow","Positive operating cash flow"],"a":0,"w":"Buying assets is negative investing cash flow; selling them is positive."},
 {"id":"8.33","q":"Repaying a bank loan is shown as a:","o":["Negative financing cash flow","Positive financing cash flow","Negative investing cash flow","Negative operating cash flow"],"a":0,"w":"Borrowing is positive financing cash flow; repaying is negative."},
 {"id":"8.34","q":"PAT is Rs 100 crore and depreciation is Rs 30 crore. Receivables rose by Rs 20 crore and payables rose by Rs 10 crore. Operating cash flow is:","o":["Rs 120 crore","Rs 160 crore","Rs 130 crore","Rs 100 crore"],"a":0,"w":"Add back non-cash depreciation: 130. Higher receivables means sales not yet collected in cash: minus 20. Higher payables means purchases not yet paid: plus 10. Total 120."},
 {"id":"8.35","q":"According to the book, a business that runs negative operating cash flows for several years:","o":["Signals an alarming risk and needs continuous borrowing or equity to keep going","Is always growing healthily","Should be valued on P/E only","Has no need for external funds"],"a":0,"w":"The book's example is Kingfisher Airlines."},
 {"id":"8.36","q":"Which of the following is NOT one of the book's points on cash flow analysis?","o":["Net cash flow alone is the best measure of health","Each cash flow stream should be analysed independently","Focus on sustainable and recurring cash flows","Adjust for non-recurring or extraordinary items"],"a":0,"w":"The book warns that looking at net cash flows could be deceptive."},
 {"id":"8.37","q":"Contingent liabilities are:","o":["Not recorded in the accounts, but disclosed in the notes to accounts","Recorded as current liabilities","Recorded as provisions","Shown as negative assets"],"a":0,"w":"Examples: lawsuits, tax disputes, bank guarantees, warranty claims."},
 {"id":"8.38","q":"Which of the following is an off-balance sheet item as per the book?","o":["Operating lease","Long-term debt","Trade payables","Share capital"],"a":0,"w":"Operating leases, contingent liabilities and derivative contracts are the book's examples."},
 {"id":"8.39","q":"A company that keeps changing its accounting policies every year should:","o":["Attract closer scrutiny for possible manipulation","Be seen as more transparent","Get a clean audit report automatically","Be ignored, as policies do not matter"],"a":0,"w":"The book calls frequent changes a reason for suspicion."},
 {"id":"8.40","q":"Auditors are unable to verify part of the financials because information is not available. They will issue a:","o":["Disclaimer","Clean report","Qualified report","Unmodified report"],"a":0,"w":"A qualified report is when auditors believe the statements do not give a true and fair view."},
 {"id":"8.41","q":"Auditors believe part of the financial statements do not reflect a true and fair view because they disagree with an accounting policy. They will issue a:","o":["Qualified report","Clean report","Disclaimer","Comfort letter"],"a":0,"w":"They must also explain the reasons."},
 {"id":"8.42","q":"Which of the following is NOT one of the three purposes of ratio analysis listed in the book?","o":["Regulatory","Descriptive","Diagnostic","Predictive"],"a":0,"w":"The book lists descriptive, diagnostic and predictive studies."},
 {"id":"8.43","q":"EBITDA is Rs 300 crore and net sales are Rs 1,200 crore. The EBITDA margin is:","o":["25%","4%","30%","400%"],"a":0,"w":"EBITDA &divide; Net sales = 300 &divide; 1,200 = 25%."},
 {"id":"8.44","q":"PAT is Rs 50 crore. Net worth was Rs 450 crore at the start of the year and Rs 550 crore at the end. ROE on average net worth is:","o":["10%","11.1%","9.1%","5%"],"a":0,"w":"Average net worth = (450 + 550) &divide; 2 = 500. ROE = 50 &divide; 500 = 10%. The book recommends averages for balance sheet items."},
 {"id":"8.45","q":"EBIT is Rs 150 crore. Capital employed was Rs 1,100 crore at the start and Rs 1,300 crore at the end. ROCE on average capital employed is:","o":["12.5%","13.6%","11.5%","8.0%"],"a":0,"w":"Average = 1,200. ROCE = 150 &divide; 1,200 = 12.5%."},
 {"id":"8.46","q":"On the most conservative basis, the book suggests a debt-to-equity ratio benchmark of:","o":["1 or less","2 or more","Exactly 3","There is no benchmark"],"a":0,"w":"Then the decision should depend on industry, track record and capital needs."},
 {"id":"8.47","q":"An interest coverage ratio below 1 means:","o":["Earnings before interest and tax are less than the interest expense","The company has no debt","The company is very liquid","Net profit is higher than interest"],"a":0,"w":"Interest coverage = EBIT &divide; interest expense."},
 {"id":"8.48","q":"The quick ratio differs from the current ratio because it excludes:","o":["Inventories","Cash","Receivables","Liquid fund investments"],"a":0,"w":"Inventories cannot be converted into cash immediately."},
 {"id":"8.49","q":"A company collects cash on sales and pays its suppliers on credit, so its current ratio is below 1. According to the book this is:","o":["Not a red flag; its working capital is funded by customers","Always a sign of distress","A sign of excess inventory","A reason for a qualified audit report"],"a":0,"w":"Firms with strong bargaining power often prefer negative working capital."},
 {"id":"8.50","q":"Revenue is Rs 1,200 crore and average accounts receivable are Rs 200 crore. Accounts receivable turnover is:","o":["6 times","0.17 times","1,000 times","2 times"],"a":0,"w":"Revenue &divide; average receivables = 1,200 &divide; 200 = 6."},
 {"id":"8.51","q":"According to the book, inventory turnover would typically be:","o":["High for FMCG companies and low for capital goods companies","Low for FMCG and high for capital goods","The same across all industries","Irrelevant for manufacturers"],"a":0,"w":"FMCG goods sell fast; capital goods take long to build and sell."},
 {"id":"8.52","q":"Asset turnover ratio is calculated as:","o":["Net sales &divide; Total assets","Total assets &divide; Net worth","Net profit &divide; Total assets","Current assets &divide; Current liabilities"],"a":0,"w":"It is also a component of DuPont analysis."},
 {"id":"8.53","q":"A company has a net profit margin of 5%, asset turnover of 2 times and an equity multiplier of 3 times. Its ROE is:","o":["30%","10%","15%","6%"],"a":0,"w":"ROE = 5% &times; 2 &times; 3 = 30%."},
 {"id":"8.54","q":"According to DuPont analysis, a rise in ROE caused only by higher leverage is:","o":["Not necessarily a reason to cheer, as it also brings higher risk","Always the best kind of improvement","A sign of higher operating efficiency","A sign of higher profit margin"],"a":0,"w":"Rises from margin or efficiency are welcome; leverage adds risk."},
 {"id":"8.55","q":"In the book's example, LowLevCo has a lower ROE than HighLevCo mainly because of its:","o":["Lower leverage","Lower profit margin","Lower asset turnover","Higher tax rate"],"a":0,"w":"LowLevCo has a higher margin and slightly higher turnover; its equity multiplier is only 1.0x."},
 {"id":"8.56","q":"The book's Suzlon example shows that:","o":["Projecting financials purely from history can be a blunder when the business environment changes","Wind energy is a defensive industry","Ratios cannot be used for forecasting at all","Pricing power never changes"],"a":0,"w":"Suzlon lost its pricing power when competition arrived."},
 {"id":"8.57","q":"A rights issue causes dilution only for:","o":["Shareholders who do not exercise their rights","All shareholders equally","Promoters only","New investors only"],"a":0,"w":"Rights shares are offered to existing holders in proportion to their holdings."},
 {"id":"8.58","q":"According to the book, a preferential allotment made at a premium is:","o":["Value-accretive to minority shareholders and poses lesser dilution risk","Always harmful to minority shareholders","Not allowed by regulators","The same as a rights issue"],"a":0,"w":"The price of such issues should be considered along with the situation."},
 {"id":"8.59","q":"According to the book, when a high-growth company increases its dividend, it may indicate that:","o":["The company foresees reduced growth opportunities","The company is about to go bankrupt","The company has stopped making profits","Insiders are selling shares"],"a":0,"w":"When a dividend deviates sharply from the past, ask management why."},
 {"id":"8.60","q":"According to Peter Lynch, as quoted in the book, insiders buying their company's shares suggests:","o":["The company is likely to make huge profits in future","Nothing at all","The shares are overvalued","Insiders need cash"],"a":0,"w":"Insider selling can happen for many reasons; buying has only one."},
]

CASES = [
 {"id":"C14","title":"Book case study: Company A versus Company B","text":"Comparative financials of two companies for the past two years. Both are in the same industry and of reasonably similar size. (Book case study 5.)" + _AB,
  "qs":[
   {"q":"Company A had Rs 320 lakhs of finished goods and WIP in inventory at the end of 2XX8. Which is closest to its inventory of finished goods and WIP at the end of 2XX9?","o":["Rs 220 lakhs","Rs 285 lakhs","Rs 355 lakhs","Rs 440 lakhs"],"a":2,"w":"Change in inventory (an expense line) = opening &minus; closing = &minus;35. So closing = 320 + 35 = 355."},
   {"q":"Companies in the industry raised selling prices, at different rates. Which company is likely to have raised its price at a higher rate, and why?","o":["Company B, as its sales grew faster than A's","Company A, as its cost of materials to sales ratio decreased year over year, while it remained constant for Company B","Company B, as its net profit margin increased by 23% compared to only 15% growth for Company A","Company A, as it earned higher net profit"],"a":1,"w":"Raw materials to sales: A fell from 35.0% to 33.0%; B stayed at 34.0%. A falling ratio points to higher selling prices. Faster sales growth can come from volume, so it proves nothing about price."},
   {"q":"Which is closest to the difference between the EBITDA margins of Company A and Company B for 2XX9? (1 basis point = 0.01%)","o":["Both companies have very similar margins","Company A's EBITDA margin is 427 bps higher than Company B's","Company B's EBITDA margin is 450 bps higher than Company A's","Company A's EBITDA margin is 518 bps higher than Company B's"],"a":3,"w":"EBITDA = PBT + finance cost + D&amp;A. A: 4,093.1 + 180.4 + 241.2 = 4,514.7, margin 49.6%. B: 2,929.6 + 195.2 + 218.6 = 3,343.4, margin 44.4%. Gap about 518 bps."},
   {"q":"Which of the two companies has a higher level of financial leverage?","o":["Company A, as it has a higher level of debt","Company A, as it has a higher debt to asset ratio","Company B, as it has a higher debt to asset ratio","Company B, as it has a higher finance cost"],"a":2,"w":"Debt &divide; assets in 2XX9: A 1,640.5 &divide; 4,687 = 35.0%; B 1,626.8 &divide; 4,067 = 40.0%. A has more debt in rupees only because it is bigger."},
   {"q":"Which is closest to the operating profit of Company B for 2XX9?","o":["Rs 2,929.6 lakhs","Rs 3,124.8 lakhs","Rs 3,343.4 lakhs","Rs 3,945.5 lakhs"],"a":1,"w":"The book calls EBIT operating profit. EBIT = PBT + finance cost = 2,929.6 + 195.2 = 3,124.8. (3,343.4 is EBITDA.)"},
   {"q":"Company A has a higher ROE than Company B. Which combination of factors has favourably contributed to A's higher ROE?","o":["Higher net profit margin and higher activity ratio","Higher net profit margin, higher activity ratio and lower financial leverage","Higher net profit margin, higher activity ratio and higher financial leverage","Higher net profit margin only"],"a":0,"w":"2XX9: margin A 30.4% vs B 26.1%; asset turnover A 1.94 vs B 1.85; equity multiplier A 1.54 vs B 1.67. A's lower leverage pulls its ROE down, so it is not a favourable factor."},
  ]},
 {"id":"C15","title":"Book case study: forecasting from two years of data","text":"Financial statements of a company for the previous two years. (Book case study 6.)" + _ONE,
  "qs":[
   {"q":"Which is closest to the capital expenditure incurred by the company in 2XX7?","o":["Rs 5.0 lakhs","Rs 6.2 lakhs","Rs 241.2 lakhs","Rs 246.2 lakhs"],"a":3,"w":"Capex = closing fixed assets &minus; opening fixed assets + depreciation = 2,412.0 &minus; 2,407.0 + 241.2 = 246.2."},
   {"q":"Which is closest to the estimated revenue for 2XX8, if revenue grows at the same rate as in 2XX7?","o":["Rs 9,100 lakhs","Rs 9,558 lakhs","Rs 9,582 lakhs","Rs 9,614 lakhs"],"a":2,"w":"Growth = 9,100 &divide; 8,642 &minus; 1 = 5.30%. 9,100 &times; 1.053 = 9,582."},
   {"q":"Revenue for 2XX8 is expected to be Rs 9,500 lakhs, with EBITDA margin 25 bps lower than the previous year. Which is closest to the estimated EBITDA for 2XX8?","o":["Rs 2,647 lakhs","Rs 2,860 lakhs","Rs 4,475 lakhs","Rs 4,689 lakhs"],"a":3,"w":"2XX7 EBITDA = 4,093.1 + 180.4 + 241.2 = 4,514.7, margin 49.61%. Less 0.25% = 49.36%. 9,500 &times; 49.36% = 4,689."},
   {"q":"Net working capital as a % of revenue is expected to stay the same in 2XX8. With revenue of Rs 9,500 lakhs, which is closest to the increase or decrease in working capital?","o":["Rs 0.0 lakhs","Rs 100.0 lakhs","Rs 275.0 lakhs","Rs 400.0 lakhs"],"a":1,"w":"2XX7 ratio = 2,275 &divide; 9,100 = 25%. 2XX8 NWC = 25% &times; 9,500 = 2,375. Increase = 100."},
   {"q":"The company will repay Rs 200 lakhs of debt in the middle of 2XX8. If its average interest rate is unchanged, which is closest to the expected finance cost for 2XX8?","o":["Rs 144 lakhs","Rs 172 lakhs","Rs 180 lakhs","Rs 200 lakhs"],"a":1,"w":"Rate = 180.4 &divide; average 2XX7 debt (1,598.6 + 1,640.5) &divide; 2 = 11.1%. 2XX8 average debt = 1,640.5 &minus; 100 = 1,540.5 (the repayment counts for half a year). 1,540.5 &times; 11.1% = about 172."},
   {"q":"2XX8 profit is estimated at Rs 3,200 lakhs. The company will pay an interim dividend of Rs 900 lakhs and a special dividend of Rs 1,000 lakhs. No other dividend, buyback or share issue. Which is closest to the book value of equity at the end of 2XX8?","o":["Rs 1,300 lakhs","Rs 4,347 lakhs","Rs 5,347 lakhs","Rs 6,247 lakhs"],"a":1,"w":"3,046.6 + 3,200 &minus; 900 &minus; 1,000 = 4,346.6."},
  ]},
 {"id":"C16","title":"Sharma Textiles: a health check","text":"An analyst pulls these figures for Sharma Textiles for the latest year." + _SHARMA,
  "qs":[
   {"q":"What is Sharma's current ratio?","o":["1.5","1.0","0.67","2.5"],"a":0,"w":"Current assets &divide; current liabilities = 600 &divide; 400 = 1.5."},
   {"q":"What is Sharma's quick ratio?","o":["1.0","1.5","0.5","2.0"],"a":0,"w":"(Current assets &minus; inventories) &divide; current liabilities = (600 &minus; 200) &divide; 400 = 1.0."},
   {"q":"What is Sharma's interest coverage ratio?","o":["3.0 times","1.33 times","2.0 times","0.33 times"],"a":0,"w":"EBIT &divide; interest = 90 &divide; 30 = 3.0. (Using PAT, 40 &divide; 30, would be wrong.)"},
   {"q":"How does Sharma's debt to equity ratio compare with the book's most conservative benchmark?","o":["1.25, above the benchmark of 1","1.25, below the benchmark of 2","0.8, below the benchmark of 1","0.5, well below the benchmark"],"a":0,"w":"Total debt &divide; net worth = 500 &divide; 400 = 1.25. The book's most conservative benchmark is 1 or less."},
  ]},
]

DATA = {"id":"ch08","short":"Ch8","title":"Chapter 8: Company analysis, financial analysis","cards":CARDS,"mcqs":MCQS,"cases":CASES}
