from .ch08_qs import _table

# Book case study (page 215): Company A and Company B, Rs lakhs. 2XX9 E = estimate.
_AB = _table(["Rs lakhs", "A 2XX8", "A 2XX9 E", "B 2XX8", "B 2XX9 E"], [
 ["Income statement summary"],
 ["Operating revenue", "8,642.0", "9,100.0", "6,427.0", "7,524.0"],
 ["EBITDA", "4,611.8", "4,754.6", "3,375.2", "3,938.8"],
 ["Net profit", "2,376.5", "2,763.1", "1,607.8", "1,962.8"],
 ["EPS", "17.0", "19.5", "26.8", "32.2"],
 ["PE ratio", "17.7", "15.4", "21.9", "18.2"],
 ["Balance sheet summary"],
 ["Cash, cash equivalents and investments", "165.0", "169.0", "54.0", "57.0"],
 ["Other assets", "4,402.5", "4,518.0", "3,685.8", "4,010.0"],
 ["Total assets", "4,567.5", "4,687.0", "3,739.8", "4,067.0"],
 ["Debt", "1,598.6", "1,640.5", "1,540.0", "1,626.8"],
 ["Equity", "2,968.9", "3,046.6", "2,199.8", "2,440.2"],
 ["Total debt and equity", "4,567.5", "4,687.0", "3,739.8", "4,067.0"],
])

CARDS = [
 {"f":"Seth Klarman on price and value","b":"\"Price is set by the most panicked seller; value, which is determined by cash flows and assets, is not.\""},
 {"f":"Buffett on price and value","b":"<b>\"Price is what you pay and Value is what you get.\"</b>"},
 {"f":"Why is valuation an art and a science?","b":"No formula gives a precise value; inputs are uncertain. It needs knowledge, experience and judgement. The result is an educated estimate."},
 {"f":"Six reasons to value a business","b":"Buying; selling; M&amp;A; owners' sense of value; fairness in an equity swap; accounting, tax, regulatory and legal needs."},
 {"f":"Purpose of any valuation","b":"Relate price to value: fairly priced, over-priced or under-priced. Valuers show several scenarios."},
 {"f":"Buffett: sources of value in a business","b":"Only two: <b>earnings and assets</b>."},
 {"f":"How do lenders look at a borrower?","b":"Cash flows first. Collateral is only a fallback."},
 {"f":"Three approaches to valuation","b":"Cost based; cash flow based (intrinsic); selling price based (relative)."},
 {"f":"Cost-based valuation","b":"Value = cost to create the asset. For buy-versus-make decisions; generally not for financial investors; strategic investors may use it."},
 {"f":"Risk-neutral valuation","b":"Probability-adjusted cash flows discounted at the <b>risk-free rate</b>. Used for insurance companies (embedded value, appraisal value)."},
 {"f":"Real-world valuation","b":"Most likely cash flows discounted at risk-free rate <b>plus a risk premium</b>."},
 {"f":"Bond with coupon equal to required return","b":"Worth its <b>face value</b>. Required return higher: below face value; lower: above."},
 {"f":"Three things DCF needs","b":"Future cash flows, their timing, and the discount rate."},
 {"f":"DDM suits...","b":"Regular, substantial dividend payers: <b>mature companies in defensive industries</b>. Discount at cost of equity."},
 {"f":"Gordon growth model","b":"P = D1 &divide; (k &minus; g). D1 = dividend expected at year end; g must be below k. Also called the perpetual growth model."},
 {"f":"Why use FCFE instead of DDM?","b":"Some companies pay little or no dividend (book: Alphabet has never paid one). FCFE suits high-growth companies."},
 {"f":"FCFE (book)","b":"Operating cash flow &minus; capex &minus; interest payments &plusmn; net borrowings."},
 {"f":"Why use FCFF instead of FCFE?","b":"Without an objective debt policy, future borrowing cannot be estimated without bias."},
 {"f":"FCFF, indirect (book)","b":"EBIT &times; (1 &minus; tax) + depreciation and non-cash charges &minus; increase in non-cash working capital &minus; capex."},
 {"f":"Discount rate for FCFF versus FCFE","b":"FCFF: <b>WACC</b>. FCFE: <b>cost of equity</b>."},
 {"f":"Two-stage valuation","b":"PV of cash flows in the high-growth years + PV of terminal value."},
 {"f":"Cap on the perpetual growth rate","b":"Often the <b>long-term nominal GDP growth rate</b>: no business outgrows the economy forever."},
 {"f":"Terminal value by exit multiple","b":"EBITDA (or EBIT) at the end of high growth &times; EV/EBITDA (or EV/EBIT) of comparable firms."},
 {"f":"From firm value to equity value","b":"Subtract minority interest, preferred share capital and interest-bearing debt."},
 {"f":"Cost of debt in valuations","b":"Prevailing interest rate for borrowers of comparable credit quality."},
 {"f":"CAPM","b":"Ke = Rf + &beta; &times; (Rm &minus; Rf)."},
 {"f":"Market risk premium versus equity risk premium","b":"MRP = Rm &minus; Rf. Equity risk premium = &beta; &times; MRP."},
 {"f":"Beta","b":"Sensitivity of a stock's return to the market's return; proxy for business and financial risk."},
 {"f":"WACC","b":"Ke &times; We + Kd &times; (1 &minus; tax) &times; Wd."},
 {"f":"Dividend yield","b":"DPS &divide; current price. Price/dividend is its reciprocal."},
 {"f":"Equity yields above bond yields means...","b":"Equity is <b>cheap</b>; typical when markets are down."},
 {"f":"Companion variables","b":"Company fundamentals checked alongside a market multiple, to tell a real bargain from a weak company."},
 {"f":"Earnings yield","b":"EPS &divide; current price. P/E is its reciprocal."},
 {"f":"Which companies deserve a higher P/E?","b":"Higher growth or lower risk. Lower growth or higher risk: a discount."},
 {"f":"PEG ratio","b":"(Price &divide; EPS) &divide; growth rate. Coined by <b>Peter Lynch</b>. Below 1 may mean undervalued."},
 {"f":"PEG example (book)","b":"A: P/E 12, growth 10% = 1.2x. B: P/E 14, growth 15% = 0.93x. B is better value."},
 {"f":"Why EV/EBITDA for acquirers?","b":"It is <b>neutral to capital structure</b>, which a controlling shareholder can change."},
 {"f":"EV/EBITDA versus EV/EBIT","b":"EV/EBITDA for <b>capital-intensive</b> industries (depreciation distorts). EV/EBIT for others."},
 {"f":"When to use EV/Sales","b":"Losses or just broken even, but likely to turn and stay profitable. Otherwise: liquidation value."},
 {"f":"P/B ratio","b":"Market cap &divide; book value of equity, or price &divide; BVPS."},
 {"f":"Where is P/B preferred, and where poor?","b":"Preferred: <b>financial companies</b> (monetary assets). Poor: capital-intensive (historical cost), services and tech (people and IP off balance sheet)."},
 {"f":"P/B example (book)","b":"AFB: 200 &divide; 198 = 1.01. LKH: 175 &divide; 160 = 1.09. AFB is less expensive."},
 {"f":"Industry average multiple: mean or median?","b":"Check <b>both</b>. Outliers in fragmented industries can pull up the mean."},
 {"f":"EV to capital employed","b":"EV &divide; (equity + debt). With ROCE, shows the return on the price paid."},
 {"f":"EV/CE example (book)","b":"EV/CE 3, ROCE 45%: return on price paid 15%. For 20%, pay at most 2.25x."},
 {"f":"Net asset value (NAV)","b":"<b>Market</b> value of assets minus liabilities. Used for real estate, shipping, aviation."},
 {"f":"Price / Embedded value","b":"For <b>life insurers</b>. Embedded value: PV of expected net future cash flows from policies in force."},
 {"f":"Price / Adjusted book value","b":"For <b>NBFCs</b>. Fair value of assets minus fair value of liabilities, including off-balance sheet items."},
 {"f":"EV / Capacity","b":"For start-ups and special situations: a closed steel plant by capacity; e-commerce by users or transactions."},
 {"f":"Trading versus transaction multiples","b":"Trading: stock market prices. Transaction: recent deals. Transaction multiples are <b>more relevant</b>."},
 {"f":"SOTP valuation","b":"Value each business separately, then add. Book examples: ITC, L&amp;T."},
 {"f":"New-age valuation measures (book)","b":"Eyeballs, page views, footfall, ARPU, number of users. They must eventually become profits."},
 {"f":"Is valuation objective?","b":"<b>No.</b> Subjective inputs, no generally accepted standards, not timeless. Complex models give a false impression of preciseness."},
 {"f":"True value of the firm for a private owner","b":"<b>EV</b>, not market cap."},
 {"f":"ROE or EPS?","b":"Focus on <b>ROE</b>: EPS does not account for retained earnings."},
 {"f":"ROCE versus ROE","b":"ROCE reflects the true return on capital; ROE can be inflated by leverage. A wide gap needs investigation."},
]

MCQS = [
 {"id":"10.1","q":"If interest rates in the economy rise, the price of a bond would:","o":["Fall","Rise"],"a":0,"w":"Book sample question. Bond prices move opposite to interest rates."},
 {"id":"10.2","q":"What is the earnings yield if the price of a stock is Rs 195 and EPS is Rs 13?","o":["6.67 percent","15 percent","0.067 percent","0.15 percent"],"a":0,"w":"Book sample question. Earnings yield = EPS &divide; price = 13 &divide; 195 = 6.67%."},
 {"id":"10.3","q":"How is the price to earnings ratio calculated?","o":["Current price of stock &divide; EPS","EPS &divide; Current price of stock","Current price of stock &times; EPS","EPS &times; Current price of stock"],"a":0,"w":"Book sample question. EPS &divide; price is the earnings yield, its reciprocal."},
 {"id":"10.4","q":"\"Price is what you pay and value is what you get\" is a quote from:","o":["Warren Buffett","Seth Klarman","Peter Lynch","Charlie Munger"],"a":0,"w":"The book also quotes Seth Klarman on price being set by the most panicked seller."},
 {"id":"10.5","q":"According to Warren Buffett, as quoted in the book, the only two sources of value in a business are:","o":["Earnings and assets","Price and volume","Debt and equity","Brand and management"],"a":0,"w":"Every asset produces periodic earnings and a final inflow on sale."},
 {"id":"10.6","q":"Valuation is often considered an art as well as a science because:","o":["The inputs are uncertain, so the result is an educated estimate needing judgement","Only artists can do it","It needs no numbers","It always gives one precise value"],"a":0,"w":"It combines knowledge, experience and professional judgement."},
 {"id":"10.7","q":"Which valuation approach is suitable only for a buyer choosing between buying and making, and is generally not suitable for financial investors?","o":["Cost based valuation","Relative valuation","Discounted cash flow","Dividend discount model"],"a":0,"w":"Strategic investors may use it. It often needs technical assessment by engineers."},
 {"id":"10.8","q":"In risk-neutral valuation, probability-adjusted cash flows are discounted at the:","o":["Risk-free rate","Cost of equity plus a risk premium","WACC","Inflation rate"],"a":0,"w":"Insurance companies are typically valued this way. Real-world valuation adds a risk premium."},
 {"id":"10.9","q":"A 10-year bond pays a 9% coupon on face value of Rs 1,00,000. Investors expect 9% for this maturity and credit quality. Its value today is:","o":["Rs 1,00,000","More than Rs 1,00,000","Less than Rs 1,00,000","Rs 9,000"],"a":0,"w":"When the coupon equals the discount rate, the value equals face value. The book's own example."},
 {"id":"10.10","q":"The same bond's required return rises to 10%. Its value will be:","o":["Less than Rs 1,00,000","More than Rs 1,00,000","Exactly Rs 1,00,000","Rs 10,000"],"a":0,"w":"A higher required return than the coupon means a value below face value (about Rs 93,855)."},
 {"id":"10.11","q":"Which of the following is NOT one of the three things DCF needs to be known with certainty?","o":["The company's share price","The stream of future cash flows","The timing of the cash flows","The expected rate of return (discount rate)"],"a":0,"w":"DCF estimates value; it does not need the market price."},
 {"id":"10.12","q":"The dividend discount model is most suitable for:","o":["Mature companies in defensive industries paying regular, substantial dividends","High-growth start-ups","Companies that never pay dividends","Loss-making companies"],"a":0,"w":"Dividends are discounted at the cost of equity."},
 {"id":"10.13","q":"Using the Gordon growth model, what is the value of a share if next year's dividend is Rs 5, cost of equity is 13% and growth is 8%?","o":["Rs 100","Rs 38.46","Rs 62.50","Rs 23.81"],"a":0,"w":"P = D1 &divide; (k &minus; g) = 5 &divide; (0.13 &minus; 0.08) = 100."},
 {"id":"10.14","q":"A company just paid a dividend of Rs 4. Dividends grow at 5% a year forever and the cost of equity is 10%. The Gordon model value is:","o":["Rs 84","Rs 80","Rs 40","Rs 26.67"],"a":0,"w":"D1 = 4 &times; 1.05 = 4.20. P = 4.20 &divide; (0.10 &minus; 0.05) = 84. Using 4 instead of D1 gives the wrong 80."},
 {"id":"10.15","q":"An important assumption of the Gordon growth model is that:","o":["The growth rate is lower than the cost of equity","The growth rate is higher than the cost of equity","The company pays no dividend","The cost of equity is zero"],"a":0,"w":"If g were equal to or above k, the formula would break down."},
 {"id":"10.16","q":"Why might an analyst use FCFE instead of DDM?","o":["The company pays little or no dividend","The company pays very regular dividends","The company has no cash flow statement","FCFE ignores capital expenditure"],"a":0,"w":"The book's example: Alphabet has never paid a dividend."},
 {"id":"10.17","q":"Operating cash flow Rs 500 crore, capex Rs 200 crore, interest payments Rs 50 crore, net borrowings Rs 30 crore. FCFE is:","o":["Rs 280 crore","Rs 220 crore","Rs 250 crore","Rs 330 crore"],"a":0,"w":"500 &minus; 200 &minus; 50 + 30 = 280."},
 {"id":"10.18","q":"EBIT Rs 400 crore, tax rate 25%, depreciation Rs 80 crore, increase in non-cash working capital Rs 30 crore, capex Rs 150 crore. FCFF (indirect method) is:","o":["Rs 200 crore","Rs 300 crore","Rs 260 crore","Rs 230 crore"],"a":0,"w":"400 &times; 0.75 = 300; + 80 &minus; 30 &minus; 150 = 200."},
 {"id":"10.19","q":"Analysts prefer the FCFF model over the FCFE model mainly when:","o":["The company has no objective debt policy, so future borrowings are hard to estimate","The company pays large dividends","The company has no debt","The company is a life insurer"],"a":0,"w":"Estimating borrowings arbitrarily can bias an FCFE valuation."},
 {"id":"10.20","q":"Free cash flow to the firm (FCFF) is discounted at the:","o":["Weighted average cost of capital","Cost of equity","Risk-free rate","Cost of debt only"],"a":0,"w":"FCFF belongs to all sources of capital. FCFE is discounted at the cost of equity."},
 {"id":"10.21","q":"Firm value is Rs 2,000 crore. Minority interest is Rs 50 crore, preferred share capital Rs 100 crore and interest-bearing debt Rs 500 crore. The value of equity is:","o":["Rs 1,350 crore","Rs 1,500 crore","Rs 1,450 crore","Rs 2,650 crore"],"a":0,"w":"2,000 &minus; 50 &minus; 100 &minus; 500 = 1,350."},
 {"id":"10.22","q":"In a two-stage valuation, the perpetual growth rate for the terminal value is often capped at:","o":["The long-term nominal GDP growth rate","The company's current growth rate","The cost of equity","Zero"],"a":0,"w":"No business can grow faster than the economy forever."},
 {"id":"10.23","q":"Which statement about terminal value is correct?","o":["It must also be discounted to present value","It is added without discounting","It is always calculated using P/B","It ignores the high-growth phase"],"a":0,"w":"The book stresses that terminal value has to be discounted further to its present value."},
 {"id":"10.24","q":"Risk-free rate 7%, beta 1.2, expected market return 12%. The cost of equity under CAPM is:","o":["13%","14.4%","19%","8.4%"],"a":0,"w":"Ke = 7 + 1.2 &times; (12 &minus; 7) = 13%."},
 {"id":"10.25","q":"In CAPM, (Rm &minus; Rf) is called the:","o":["Market risk premium","Equity risk premium","Risk-free rate","Beta"],"a":0,"w":"Beta &times; (Rm &minus; Rf) is the equity risk premium."},
 {"id":"10.26","q":"Cost of equity 13%, pre-tax cost of debt 10%, tax rate 25%, equity 60% and debt 40% of capital. WACC is:","o":["10.8%","11.8%","12.0%","9.3%"],"a":0,"w":"0.6 &times; 13 + 0.4 &times; 10 &times; 0.75 = 7.8 + 3.0 = 10.8%."},
 {"id":"10.27","q":"In valuations, the cost of debt is usually taken as:","o":["The prevailing interest rate for borrowers with comparable credit quality","The company's dividend yield","The risk-free rate always","Zero, as interest is tax-deductible"],"a":0,"w":"As stated in the book."},
 {"id":"10.28","q":"A share pays a dividend of Rs 6 and trades at Rs 150. Its dividend yield and price to dividend ratio are:","o":["4% and 25 times","25% and 4 times","6% and 15 times","4% and 6 times"],"a":0,"w":"6 &divide; 150 = 4%. 150 &divide; 6 = 25."},
 {"id":"10.29","q":"When equity yields are generally higher than bond yields:","o":["Equity is available cheap; this is typical when markets are down","Equity is expensive; this is typical in bull markets","Bonds are always better","Dividends must be cut"],"a":0,"w":"In bull markets equity yields are well below bond yields."},
 {"id":"10.30","q":"A stock has a much higher dividend yield than its peers. According to the book:","o":["It may not necessarily be a value pick; a high payout may mean limited avenues for growth","It is always a value pick","It must be overvalued","It will always outperform"],"a":0,"w":"Check it against company fundamentals, the companion variables."},
 {"id":"10.31","q":"All else held constant, a stock with a higher P/E than its peer group and the market is considered:","o":["Expensive","Undervalued","Fairly valued","Risk-free"],"a":0,"w":"But higher growth or lower risk can justify a premium."},
 {"id":"10.32","q":"According to the book, shares of companies with higher growth potential or lesser risk should trade at:","o":["A premium to their peer group","A discount to their peer group","The same multiple as peers","Book value"],"a":0,"w":"Lower growth or higher risk should trade at a discount."},
 {"id":"10.33","q":"A stock has a P/E of 20 and expected earnings growth of 25%. Its PEG ratio is:","o":["0.8","1.25","5","500"],"a":0,"w":"PEG = 20 &divide; 25 = 0.8. Below 1, so Lynch's rule of thumb would call it undervalued."},
 {"id":"10.34","q":"The PEG ratio was coined by:","o":["Peter Lynch","Warren Buffett","Seth Klarman","Benjamin Graham"],"a":0,"w":"He warned that high growth may not last very long."},
 {"id":"10.35","q":"Why is EV/EBITDA preferred when valuing a company from an acquirer's perspective?","o":["It is neutral to the capital structure","It ignores the company's debt","It uses only the share price","It is required by SEBI"],"a":0,"w":"A controlling shareholder can change the capital structure, which affects EPS and P/E."},
 {"id":"10.36","q":"According to the book, EV/EBITDA rather than EV/EBIT is preferable for:","o":["Capital-intensive industries","Service industries","Banks","Life insurers"],"a":0,"w":"Historical asset costs and depreciation choices distort EBIT in capital-intensive industries."},
 {"id":"10.37","q":"Market cap Rs 900 crore, debt Rs 300 crore, cash Rs 100 crore, EBITDA Rs 110 crore. EV/EBITDA is:","o":["10x","8.2x","11.8x","9.1x"],"a":0,"w":"EV = 900 + 300 &minus; 100 = 1,100. 1,100 &divide; 110 = 10x."},
 {"id":"10.38","q":"EV/Sales is most meaningful for a company that:","o":["Is making losses but is likely to turn and stay profitable","Is profitable with stable earnings","Has no sales","Is loss-making with no turnaround in sight"],"a":0,"w":"If no turnaround is likely, the company should be valued at liquidation value."},
 {"id":"10.39","q":"The price to book value ratio is preferred for valuing companies in the:","o":["Financial sector","Technology sector","Services sector","Capital-intensive manufacturing sector"],"a":0,"w":"Their assets are mostly monetary, so book value is close to fair value."},
 {"id":"10.40","q":"Market cap is Rs 1,200 crore and book value of equity is Rs 800 crore. The P/B ratio is:","o":["1.5","0.67","2.0","400"],"a":0,"w":"1,200 &divide; 800 = 1.5."},
 {"id":"10.41","q":"In the book's example, AFB Finance (price Rs 200, BVPS Rs 198) and LKH Finance (price Rs 175, BVPS Rs 160). On P/B alone:","o":["AFB Finance is less expensive","LKH Finance is less expensive, because its price is lower","Both are equally priced","Neither can be compared"],"a":0,"w":"AFB P/B = 1.01, LKH P/B = 1.09. A lower share price does not mean cheaper."},
 {"id":"10.42","q":"When comparing a company's multiple with its industry, the book advises checking:","o":["Both the mean and the median of the industry","Only the highest multiple","Only one peer","Only the mean"],"a":0,"w":"Outliers in a fragmented industry can pull the mean up."},
 {"id":"10.43","q":"Net worth Rs 200, debt Rs 100, market cap Rs 800, cash nil, ROCE 30%. What return does an investor earn on the EV paid?","o":["10%","30%","15%","3.75%"],"a":0,"w":"EV = 800 + 100 = 900; capital employed = 300; EV/CE = 3. 30% &divide; 3 = 10%. Same logic as the book's example."},
 {"id":"10.44","q":"Net asset value (NAV) differs from book value because NAV uses:","o":["Market value of assets","Historical cost of assets","Face value of shares","Only intangible assets"],"a":0,"w":"It is used for asset-heavy businesses like real estate, shipping and aviation."},
 {"id":"10.45","q":"Price to embedded value is specifically used for valuing:","o":["Life insurance businesses","NBFCs","Steel plants","E-commerce start-ups"],"a":0,"w":"Price to adjusted book value is for NBFCs; EV/capacity for start-ups and special situations."},
 {"id":"10.46","q":"A large steel plant that is currently out of operation may be valued using:","o":["EV/Capacity","P/E","Dividend yield","PEG ratio"],"a":0,"w":"Operating metrics replace financial metrics when the financials do not reflect potential."},
 {"id":"10.47","q":"Which multiples are considered more relevant and authentic, according to the book?","o":["Transaction multiples","Trading multiples","Historical P/E only","Dividend yields"],"a":0,"w":"They show that someone was actually willing to acquire the asset at that value."},
 {"id":"10.48","q":"Valuing each business of a conglomerate separately and adding them up is called:","o":["Sum-of-the-parts valuation","Gordon growth model","Relative valuation","Cost-based valuation"],"a":0,"w":"Book examples: ITC and L&amp;T."},
 {"id":"10.49","q":"According to the book, complicated quantitative valuation models:","o":["Only give a false impression of preciseness","Make valuation fully objective","Remove the need for judgement","Are timeless"],"a":0,"w":"Valuation is subjective and can change dramatically when circumstances change."},
 {"id":"10.50","q":"According to the book, the true value of the firm for a private owner is:","o":["Enterprise value","Market capitalisation","Book value","Face value"],"a":0,"w":"One of the book's important considerations in valuation."},
 {"id":"10.51","q":"Which statement is part of the book's important considerations in valuation?","o":["Focus on ROE and not EPS, because EPS does not account for retained earnings","Focus on EPS and not ROE","Leverage never affects ROE","Use only standalone numbers"],"a":0,"w":"The book also says to look at consolidated numbers."},
]

CASES = [
 {"id":"C19","title":"Book case study: valuing Company A and Company B","text":"Financial summary of two companies: one year of history and one year of estimates (E). (Book case study 4.)" + _AB,
  "qs":[
   {"q":"Company B's PE ratio is higher than Company A's. Which is a plausible reason to justify B's higher PE?","o":["EPS growth rate for Company B is higher than for Company A, and higher growth justifies a higher PE","Company B is a relatively smaller company, and the smaller base justifies a higher PE","Company B has high financial leverage, which justifies a higher PE","None of the above"],"a":0,"w":"EPS growth for 2XX9: A 17.0 to 19.5 = 14.7%; B 26.8 to 32.2 = 20.1%. Higher growth justifies a premium."},
   {"q":"Which company appears cheaper on PEG? Use the expected growth rate for 2XX9.","o":["Company A, as its PEG is 1.05x compared to 0.91x for B","Company B, as its PEG is 0.91x compared to 1.05x for A","Company A, as its PEG is 2.91x compared to 1.07x for B","Company B, as its PEG is 1.07x compared to 2.91x for A"],"a":1,"w":"A: 15.4 &divide; 14.7 = 1.05. B: 18.2 &divide; 20.1 = 0.91 (about 0.90). The lower PEG is cheaper."},
   {"q":"Which is closest to the market value of equity (market capitalisation) of Company A in 2XX9?","o":["Rs 3,046 lakhs","Rs 30,000 lakhs","Rs 42,600 lakhs","None of the above"],"a":2,"w":"Market cap = PE &times; net profit = 15.4 &times; 2,763.1 = 42,552, about 42,600. Rs 3,046 lakhs is the book value of equity."},
   {"q":"Company B's market cap based on its last traded price is Rs 36,000 (lakhs). Which is closest to its EV/EBITDA based on the 2XX9 forecast?","o":["8.17x","8.74x","9.14x","9.54x"],"a":3,"w":"EV = 36,000 + debt 1,626.8 &minus; cash 57.0 = 37,569.8. &divide; EBITDA 3,938.8 = 9.54x. The book's question says \"crores\", but only the table's unit, lakhs, fits the options."},
   {"q":"The industry's average PE is 16x on 2XX9 earnings. The analyst thinks Company B deserves a 20% premium for its low risk and high growth. Which is closest to the fair price of its share?","o":["Rs 428.7","Rs 514.8","Rs 617.8","Rs 643.6"],"a":2,"w":"Fair PE = 16 &times; 1.2 = 19.2. &times; 2XX9 EPS of 32.2 = about 618."},
   {"q":"The analyst's fair EV/EBITDA multiple for Company A is 8.5x. Which is closest to the fair value of A's equity in 2XX9?","o":["Rs 38,943 lakhs","Rs 40,415 lakhs","Rs 41,886 lakhs","Rs 42,224 lakhs"],"a":0,"w":"EV = 8.5 &times; 4,754.6 = 40,414. Equity = EV &minus; debt 1,640.5 + cash 169.0 = 38,943. (40,415 is the EV, not equity.)"},
  ]},
 {"id":"C20","title":"Valuing Delta Foods","text":"Delta Foods is a mature, steady dividend payer. The risk-free rate is 7%, the expected market return is 12% and Delta's beta is 0.8. Next year's dividend is expected to be Rs 4.40, growing at 6% a year forever. Delta's pre-tax cost of debt is 9%, its tax rate 25%, and its capital is 70% equity and 30% debt. It trades at a P/E of 22 with expected earnings growth of 20%.",
  "qs":[
   {"q":"What is Delta's cost of equity under CAPM?","o":["11%","9.6%","12%","15.8%"],"a":0,"w":"7 + 0.8 &times; (12 &minus; 7) = 11%."},
   {"q":"Using the Gordon growth model, what is the value of a Delta share?","o":["Rs 88","Rs 40","Rs 73.33","Rs 93.28"],"a":0,"w":"4.40 &divide; (0.11 &minus; 0.06) = 88."},
   {"q":"What is Delta's WACC, closest to?","o":["9.7%","10.4%","11.0%","8.3%"],"a":0,"w":"0.7 &times; 11 + 0.3 &times; 9 &times; 0.75 = 7.7 + 2.03 = 9.73%."},
   {"q":"What is Delta's PEG ratio, and what does Lynch's rule of thumb suggest?","o":["1.1; slightly above 1, so not undervalued by the rule","0.91; undervalued","1.1; clearly undervalued","4.4; heavily overvalued"],"a":0,"w":"22 &divide; 20 = 1.1. The rule treats a PEG below 1 as undervalued."},
  ]},
]

DATA = {"id":"ch10","short":"Ch10","title":"Chapter 10: Valuation principles","cards":CARDS,"mcqs":MCQS,"cases":CASES}
