CARDS = [
 {"f":"Two things an investor expects","b":"A return and, more importantly, the <b>capital back</b>."},
 {"f":"Three ways to judge a return","b":"Its level, its volatility, its nature (periodic or capital appreciation)."},
 {"f":"Return on investment","b":"(Net profit &divide; Investment) &times; 100."},
 {"f":"Total return","b":"Periodic income (interest, dividend, rent) + change in value, realised or not."},
 {"f":"Book example: simple return","b":"Cost 3,770; sale 4,480 + dividend 150 = 4,630. 4,630 &divide; 3,770 &minus; 1 = <b>23%</b> (holding period return)."},
 {"f":"Simple annualised return","b":"HPR &divide; months held &times; 12 (or days &times; 365). Book: 23% over 15 months = <b>18.4%</b>."},
 {"f":"CAGR","b":"(End value &divide; Beginning value)<sup>1/n</sup> &minus; 1. Book: 23% over 5 years = <b>4.2%</b> a year."},
 {"f":"Why CAGR over simple annualised?","b":"It accounts for <b>compounding</b> and time value of money."},
 {"f":"When is CAGR not the standard measure?","b":"For periods of <b>less than one year</b>."},
 {"f":"Multiple cash flows on different dates","b":"Use Excel's <b>XIRR</b>. Book example: 8.06%."},
 {"f":"Risk (book definition)","b":"Volatility and uncertainty of returns and, at the extreme, loss of capital; also actual returns differing from expected."},
 {"f":"Inflation risk","b":"Also called <b>purchasing power risk</b>. Highest for fixed-return instruments; lower for equity."},
 {"f":"8% bond, 7% inflation","b":"Real return about <b>1%</b>. If inflation rises to 9%, real return turns negative."},
 {"f":"Venezuela 2018 (book)","b":"Inflation peaked at 65,370%. Bonds became almost worthless; the Caracas stock index rose over 1,000 times."},
 {"f":"Interest rate risk","b":"Bond prices fall when rates rise and rise when rates fall."},
 {"f":"Business risk: how is it measured?","b":"Standard deviation of <b>EBIT or EBITDA</b>. Includes commodity, operations, competition, supply chain, currency risk."},
 {"f":"Market risk","b":"Loss from adverse price moves in traded assets. Deposits and small savings have none."},
 {"f":"Credit (default) risk","b":"Issuer may not pay interest or principal. None for a sovereign's local-currency debt."},
 {"f":"Credit rating symbols (book)","b":"AAA and A1 highest creditworthiness; D = default. SEBI standardised the symbols."},
 {"f":"Liquidity risk","b":"Cannot sell when desired, or only below value, or at high cost. Book: Sovereign Gold Bond bid-ask gap above Rs 80 (about 2%)."},
 {"f":"Three meanings of liquidity","b":"A company's ability to meet short-term obligations; an asset's ease of conversion to cash; a market's depth of buyers and sellers."},
 {"f":"Call risk","b":"Bond called before maturity. Most prevalent when rates are <b>falling</b>. Goes with reinvestment risk."},
 {"f":"Reinvestment risk","b":"Coupons reinvested at a lower rate. Rises when rates fall; falls when rates rise. Cumulative option avoids it."},
 {"f":"Political versus country risk","b":"Political: unfavourable government action (nationalisation, tax, licensing). Country: socio-economic-political-cultural risks; a country default hits all its securities."},
 {"f":"Systematic risks (book)","b":"Market, inflation, exchange rate, interest rate, reinvestment. Cannot be diversified away."},
 {"f":"Unsystematic risks (book)","b":"Credit, business, liquidity. Can be diversified away."},
 {"f":"Risk versus uncertainty (book)","b":"Uncertainty: cause unknown. Risk: \"known uncertainty\", once the cause is understood."},
 {"f":"Sample standard deviation","b":"&radic;[&Sigma;(X &minus; mean)&sup2; &divide; (n &minus; 1)]."},
 {"f":"Beta, modified duration, delta","b":"Beta: stock versus index (market risk). Modified duration: bond versus rates. Delta: option versus underlying."},
 {"f":"VaR (1%) of 12%","b":"99% confident the loss will not exceed 12%; 1% chance it will."},
 {"f":"Beta = 1, below 1, above 1","b":"Moves with the market; less volatile; more volatile."},
 {"f":"Beta 1.2, market up 15%","b":"Stock up <b>18%</b>."},
 {"f":"Klarman on beta","b":"\"Preposterous\" that one number from past prices could describe risk. Ignores fundamentals and price; assumes equal upside and downside."},
 {"f":"Sensitivity versus scenario analysis","b":"Sensitivity: change one variable, hold others. Scenario: best, worst and most likely cases."},
 {"f":"Margin of safety","b":"Gap between value and price when buying well below intrinsic value. Popularised by <b>Benjamin Graham</b>. No universal standard; no guarantee."},
 {"f":"Benjamin Graham's nickname","b":"\"The father of value investing\" (also \"Dean of Wall Street\")."},
 {"f":"Main source of bond versus equity returns","b":"Bonds: coupon. Equity: appreciation (dividend is small)."},
 {"f":"Buffett on stocks versus bonds","b":"Compare their returns; buy whichever offers more."},
 {"f":"Jensen's alpha","b":"Portfolio return &minus; [Rf + &beta; &times; market risk premium]. Excess over the CAPM return."},
 {"f":"Sharpe ratio","b":"(Rp &minus; Rf) &divide; <b>standard deviation</b>. Suits investors <b>not</b> adequately diversified."},
 {"f":"Treynor ratio","b":"(Rp &minus; Rf) &divide; <b>beta</b>. Suits investors <b>adequately diversified</b>."},
 {"f":"Higher or lower is better for Jensen, Sharpe, Treynor?","b":"<b>Higher</b> for all three."},
 {"f":"Loss aversion","b":"Avoiding losses matters more than gains; losses hurt about <b>twice</b> as much. Leads to inaction."},
 {"f":"Confirmation bias","b":"Also <b>my-side bias</b>. Seeking information that confirms existing beliefs."},
 {"f":"Ownership bias","b":"Also the <b>endowment effect</b>. Valuing what you own more than others would."},
 {"f":"Gambler's fallacy","b":"Predicting random events from the past, expecting things to \"balance out\"."},
 {"f":"Winner's curse","b":"Winning a bid by overpaying: a behavioural win, a financial loss."},
 {"f":"Herd mentality","b":"Following others, assuming they know more. Leads to bubbles and crashes. Keynes: better to fail conventionally than succeed unconventionally."},
 {"f":"Anchoring","b":"Over-relying on the first piece of information; waiting for a \"right price\" that is no longer realistic."},
 {"f":"Projection bias","b":"Projecting the recent past into the distant future, ignoring the distant past."},
 {"f":"Graham: voting and weighing","b":"\"In the short run, market is a voting machine but in the long run, it is a weighing machine.\""},
 {"f":"Mr. Market","b":"Graham's moody partner who quotes prices daily. Do not share his emotions; exploit his mispricing."},
 {"f":"Templeton's advice","b":"\"Invest at the point of maximum pessimism.\""},
 {"f":"Stock turnover ratio","b":"Shares traded in a period &divide; <b>free float</b> shares (held by non-promoters)."},
 {"f":"Traded value turnover ratio","b":"Traded value &divide; market capitalisation."},
 {"f":"Barings: who and where (Annexure 3)","b":"Nick Leeson, head of derivatives at <b>Barings Futures Singapore</b>. He ran both front and back office."},
 {"f":"Leeson's original trade","b":"Sold <b>straddles</b> (call + put) on Nikkei 225 futures: a bet the market would stay stable. Loses on a big move either way."},
 {"f":"What went wrong at Barings","b":"Kobe earthquake, Nikkei fell. Instead of cutting the loss he bought huge long futures to prop up the index, and misled London and both exchanges."},
 {"f":"Five lessons from Barings","b":"One trader can't move the market; clear position limits; monitor them (separate front and back office); exchanges share large-position data; margin everyone, institutions too."},
 {"f":"Barings: the book's verdict","b":"\"Not the derivatives failure, it was <b>management's failure</b>.\" Root cause: poor operational controls (<b>operational risk</b>)."},
 {"f":"Why were SGX-DT and OSE unharmed by Barings?","b":"They had collected <b>margins</b>. But they never cross-checked his positions, as they competed for business."},
 {"f":"2008: what banks did (Annexure 3)","b":"Lent to weaker borrowers, loosened loan to value (80:20 to 85:15), sold the loans on and booked profits up front. <b>Moral hazard</b>."},
 {"f":"2008: why home buyers saw a call option","b":"Almost 100% financing. Prices up: sell and keep the gain. Prices down: hand the keys to the bank."},
 {"f":"2008: lessons for investors","b":"Do your own due diligence, not just ratings; ask \"what could go wrong here?\"; don't decide only on historical data."},
 {"f":"Frauds in Annexure 3","b":"Companies: Enron (2001), WorldCom (2002), Satyam (2009, about Rs 5,000 crore). Fund managers: Madoff ($65 billion Ponzi), Milken (junk bonds, insider trading), Rajaratnam (Galleon, insider trading)."},
]

MCQS = [
 {"id":"12.1","q":"Callability feature in bonds ______.","o":["Is most prevalent when interest rates are expected to fall","Favours investors","Is against the interest of issuers","Is most prevalent when interest rates are expected to rise"],"a":0,"w":"Book sample question. When rates fall, issuers redeem high-coupon bonds and refinance more cheaply."},
 {"id":"12.2","q":"The ______ refers to the difference between value and price, when securities are bought at a price significantly below their intrinsic value.","o":["Margin of safety","Sensitivity analysis","Intrinsic value","Holding period return"],"a":0,"w":"Book sample question."},
 {"id":"12.3","q":"______ factors the systematic risk using equity beta.","o":["Jensen's alpha","Sharpe ratio","Treynor ratio"],"a":0,"w":"Book sample question, answered in the book's own words for Jensen's alpha."},
 {"id":"12.4","q":"An investment of Rs 200 earns a net profit of Rs 20. The ROI is:","o":["10%","20%","1%","110%"],"a":0,"w":"20 &divide; 200 &times; 100 = 10%."},
 {"id":"12.5","q":"In the book's example, total cost is Rs 3,770, sale proceeds Rs 4,480 and dividends Rs 150. The simple return is about:","o":["23%","19%","12%","4.2%"],"a":0,"w":"(4,480 + 150) &divide; 3,770 &minus; 1 = 0.23."},
 {"id":"12.6","q":"A holding period return of 23% was earned over 15 months. The simple annualised return is:","o":["18.4%","23%","28.75%","15.3%"],"a":0,"w":"(23% &divide; 15) &times; 12 = 18.4%."},
 {"id":"12.7","q":"An investment grows from Rs 1,000 to Rs 1,610.51 in 5 years. Its CAGR is:","o":["10%","12.2%","61%","8%"],"a":0,"w":"(1,610.51 &divide; 1,000)<sup>1/5</sup> &minus; 1 = 1.10 &minus; 1 = 10%. The simple average (61% &divide; 5 = 12.2%) ignores compounding."},
 {"id":"12.8","q":"Which return measure takes compounding into account?","o":["CAGR","Holding period return","Simple annualised return","Absolute return in rupees"],"a":0,"w":"CAGR assumes periodic returns are reinvested."},
 {"id":"12.9","q":"CAGR is the accepted standard measure of return except for:","o":["Periods of less than one year","Periods of more than five years","Equity investments","Bond investments"],"a":0,"w":"As stated in the book."},
 {"id":"12.10","q":"An investor receives dividends on different dates and then sells the share. The CAGR is best calculated using:","o":["The XIRR function","The simple annualised formula","The direct CAGR formula with two values","Holding period return"],"a":0,"w":"The book's example gives 8.06% using XIRR."},
 {"id":"12.11","q":"Inflation risk is also known as:","o":["Purchasing power risk","Default risk","Liquidity risk","Call risk"],"a":0,"w":"Money received buys less after inflation."},
 {"id":"12.12","q":"Inflation risk is highest in:","o":["Fixed return instruments like bonds and fixed deposits","Equity shares","Commodities","Real estate"],"a":0,"w":"Both interest and principal are fixed in rupee terms."},
 {"id":"12.13","q":"A bond pays an 8% coupon while inflation is 9%. The real return is approximately:","o":["Negative 1%","1%","17%","8%"],"a":0,"w":"The book's example: 8% coupon with 7% inflation gives 1%; at 9% inflation the real return turns negative."},
 {"id":"12.14","q":"According to the book, business risk is usually measured as the:","o":["Standard deviation of EBIT or EBITDA","Beta of the stock","Credit rating","Modified duration"],"a":0,"w":"Any factor that makes operating income volatile is business risk."},
 {"id":"12.15","q":"Which of the following investments has no market risk, according to the book?","o":["Bank deposits and small savings schemes","Listed equity shares","Gold","Corporate bonds"],"a":0,"w":"They are not marketable, so they neither lose nor gain from market prices."},
 {"id":"12.16","q":"A sovereign government has no default risk on its:","o":["Local currency borrowings","Foreign currency borrowings","All borrowings","Corporate guarantees"],"a":0,"w":"It can raise taxes or print money to repay domestic currency debt."},
 {"id":"12.17","q":"As per the book, which credit rating symbol represents default status?","o":["D","AAA","A1","BBB"],"a":0,"w":"AAA and A1 indicate the highest creditworthiness."},
 {"id":"12.18","q":"When interest rates fall, reinvestment risk:","o":["Increases","Reduces or is eliminated","Stays the same","Turns into credit risk"],"a":0,"w":"Coupons have to be reinvested at lower rates."},
 {"id":"12.19","q":"Which risk is classified in the book as unsystematic?","o":["Credit risk","Interest rate risk","Inflation risk","Reinvestment risk"],"a":0,"w":"Unsystematic: credit, business, liquidity. The others are systematic."},
 {"id":"12.20","q":"Which risk is classified in the book as systematic?","o":["Reinvestment risk","Business risk","Liquidity risk","Credit risk"],"a":0,"w":"Systematic: market, inflation, exchange rate, interest rate and reinvestment."},
 {"id":"12.21","q":"Systematic risk is also known as:","o":["Undiversifiable risk","Diversifiable risk","Specific risk","Credit risk"],"a":0,"w":"It cannot be eliminated through diversification."},
 {"id":"12.22","q":"Ashima holds many bonds and switches to highly rated ones. Which risk remains, since it affects all bonds?","o":["Interest rate risk","Credit risk","Business risk","Liquidity risk of one issuer"],"a":0,"w":"If rates rise, all her bonds fall in price."},
 {"id":"12.23","q":"Which measure shows the sensitivity of a bond's price to small changes in interest rates?","o":["Modified duration","Beta","Delta","Sharpe ratio"],"a":0,"w":"Beta is for stocks versus the index; delta is for options versus the underlying."},
 {"id":"12.24","q":"A portfolio's VaR (1%) is 12%. This means:","o":["There is 99% confidence the loss will not exceed 12%","The portfolio will lose 12% for sure","There is 12% chance of a 1% loss","The portfolio will gain 12%"],"a":0,"w":"Confidence level = 1 &minus; significance level."},
 {"id":"12.25","q":"A stock has a beta of 0.8. If the market rises by 10%, the stock is expected to rise by:","o":["8%","10%","12.5%","0.8%"],"a":0,"w":"0.8 &times; 10% = 8%. Beta below 1 means less volatile than the market."},
 {"id":"12.26","q":"Beta is a measure of:","o":["Systematic risk","Unsystematic risk","Credit risk","Liquidity risk"],"a":0,"w":"It is a proxy of risk that cannot be diversified away."},
 {"id":"12.27","q":"Changing one input in a valuation model while keeping all others constant, to see the effect on value, is called:","o":["Sensitivity analysis","Scenario analysis","Margin of safety","Value at risk"],"a":0,"w":"Scenario analysis uses best, worst and most likely cases instead."},
 {"id":"12.28","q":"The concept of margin of safety was popularised by:","o":["Benjamin Graham","Seth Klarman","Peter Lynch","John Templeton"],"a":0,"w":"Known as the father of value investing; followed by Warren Buffett."},
 {"id":"12.29","q":"Which statement about margin of safety is correct?","o":["There is no universal standard for how wide it should be","It guarantees a successful investment","It is fixed at 25% by SEBI","It applies only to bonds"],"a":0,"w":"Each investor sets their own number; it provides a cushion, not a guarantee."},
 {"id":"12.30","q":"Equity returns come primarily from:","o":["Appreciation in the value of the investment","Fixed coupon income","Interest on deposits","Guaranteed dividends"],"a":0,"w":"Dividend is a small part, and neither is assured."},
 {"id":"12.31","q":"Portfolio return 15%, risk-free rate 6%, standard deviation 12%. The Sharpe ratio is:","o":["0.75","1.25","7.5","0.5"],"a":0,"w":"(15 &minus; 6) &divide; 12 = 0.75."},
 {"id":"12.32","q":"Portfolio return 15%, risk-free rate 6%, beta 1.2. The Treynor ratio is:","o":["7.5","0.75","12.5","10.8"],"a":0,"w":"(15 &minus; 6) &divide; 1.2 = 7.5."},
 {"id":"12.33","q":"Portfolio return 15%, risk-free rate 6%, beta 1.2, market risk premium 7%. Jensen's alpha is:","o":["0.6%","9%","1.8%","14.4%"],"a":0,"w":"CAPM return = 6 + 1.2 &times; 7 = 14.4%. Alpha = 15 &minus; 14.4 = 0.6%."},
 {"id":"12.34","q":"Which measure is appropriate for an investor who has adequately diversified across multiple asset classes, as per the book?","o":["Treynor ratio","Sharpe ratio","Standard deviation alone","Holding period return"],"a":0,"w":"Sharpe suits investors who have not diversified adequately."},
 {"id":"12.35","q":"The Sharpe ratio measures the risk premium earned per unit of:","o":["Standard deviation","Beta","Market return","Duration"],"a":0,"w":"Treynor uses beta."},
 {"id":"12.36","q":"Studies show the pain of loss is about ______ as strong as the pleasure of a gain of similar size.","o":["Twice","Half","Ten times","Equally"],"a":0,"w":"This drives loss aversion, which leads to inaction."},
 {"id":"12.37","q":"A trader's reason for buying a stock fails, so the trader makes up a new reason to keep holding it. This is:","o":["Confirmation bias","Gambler's fallacy","Winner's curse","Projection bias"],"a":0,"w":"The book's own example of confirmation (my-side) bias."},
 {"id":"12.38","q":"Holding positions you would not buy at today's price because you own them is:","o":["Ownership bias (endowment effect)","Herd mentality","Anchoring","Loss aversion"],"a":0,"w":"Things we own seem more valuable to us."},
 {"id":"12.39","q":"Winning a competitive bid by overpaying for the asset is called:","o":["Winner's curse","Gambler's fallacy","Anchoring","Confirmation bias"],"a":0,"w":"A behavioural win but possibly a financial loss."},
 {"id":"12.40","q":"An investor refuses to sell a falling stock until it returns to the price they first paid, ignoring new information. This is:","o":["Anchoring","Herd mentality","Winner's curse","Gambler's fallacy"],"a":0,"w":"The book's example of anchoring: waiting for a \"right price\" that is no longer viable."},
 {"id":"12.41","q":"Believing that after five red results, black is now \"due\" on a roulette wheel is an example of:","o":["Gambler's fallacy","Ownership bias","Projection bias","Winner's curse"],"a":0,"w":"Expecting random events to balance out."},
 {"id":"12.42","q":"\"It is better for reputations to fail conventionally than to succeed unconventionally\" was said by Keynes in the context of:","o":["Herd mentality","Anchoring","Loss aversion","Margin of safety"],"a":0,"w":"Most people do not go against the crowd."},
 {"id":"12.43","q":"\"In the short run, market is a voting machine but in the long run, it is a weighing machine\" is attributed in the book to:","o":["Benjamin Graham","Warren Buffett","Peter Lynch","David Dreman"],"a":0,"w":"From the book's pearls of wisdom."},
 {"id":"12.44","q":"\"Invest at the point of maximum pessimism\" is attributed in the book to:","o":["John Templeton","Walter Schloss","Charlie Munger","Seth Klarman"],"a":0,"w":"From the book's pearls of wisdom."},
 {"id":"12.45","q":"The stock turnover ratio is calculated by dividing the number of shares traded in a period by:","o":["The number of free float shares outstanding","Total shares including promoters","Market capitalisation","Daily average volume"],"a":0,"w":"Free float means shares held by non-promoter shareholders."},
 {"id":"12.46","q":"Traded value of a stock in a year is Rs 500 crore and its market capitalisation is Rs 2,500 crore. The traded value turnover ratio is:","o":["0.2","5","0.5","2"],"a":0,"w":"500 &divide; 2,500 = 0.2."},
 {"id":"12.47","q":"As per the book's Annexure 3, the Board of Banking Supervision placed responsibility for the Barings debacle mainly on:","o":["Poor operational controls at Barings","The use of derivatives","Inadequate margins at the exchanges","The Kobe earthquake"],"a":0,"w":"\"Barings' failure was not the derivatives failure, it was management's failure.\""},
 {"id":"12.48","q":"Nick Leeson's short straddles on Nikkei 225 futures would lose money if:","o":["The market moved sharply in either direction","The market stayed stable","Volatility fell","The options expired worthless"],"a":0,"w":"Selling a call and a put together is a bet on a stable market."},
 {"id":"12.49","q":"Which Barings lesson does the book say SEBI has acted on in India?","o":["Margins apply to all categories of participants, including institutions","Exchanges must merge their order books","Traders may run both front and back office","Index futures are banned for banks"],"a":0,"w":"Big institutions are as prone to risk as individuals, so everyone is margined."},
 {"id":"12.50","q":"Leeson's limit breaches went unnoticed mainly because:","o":["He supervised the back office himself","The exchanges hid his positions","He traded only on one exchange","Barings had no position limits"],"a":0,"w":"The fix: different people in charge of front and back office."},
 {"id":"12.51","q":"In the book's account of 2008, banks selling mortgages on and caring little about borrower quality is an example of:","o":["Moral hazard","Herd immunity","Reinvestment risk","Call risk"],"a":0,"w":"They booked profits up front and passed the risk to investors."},
 {"id":"12.52","q":"Which lesson for investors does the book draw from the 2008 credit event?","o":["Do independent due diligence besides relying on credit ratings","Buy only AAA-rated mortgage securities","Rely fully on historical default data","Avoid all fixed income"],"a":0,"w":"Keep asking \"what could go wrong here?\""},
 {"id":"12.53","q":"As per the book, Satyam's promoter confessed in 2009 to inflating cash and bank balances by about:","o":["Rs 5,000 crore","Rs 500 crore","Rs 50,000 crore","Rs 65 billion"],"a":0,"w":"Satyam was later acquired by Tech Mahindra."},
 {"id":"12.54","q":"The book describes Bernard Madoff's fraud as:","o":["A $65 billion Ponzi scheme","Insider trading in junk bonds","Inflated cash balances","Hiding losses on index futures"],"a":0,"w":"The largest financial fraud in US history, exposed in December 2008."},
]

CASES = [
 {"id":"C23","title":"Comparing two fund managers","text":"Fund P returned 16% a year with a standard deviation of 20% and a beta of 1.25. Fund Q returned 13% with a standard deviation of 10% and a beta of 0.8. The risk-free rate is 6% and the market risk premium is 6%. Neha, the investor, holds a broadly diversified portfolio across asset classes.",
  "qs":[
   {"q":"Which fund has the higher Sharpe ratio?","o":["Fund Q: 0.70 versus 0.50","Fund P: 0.50 versus 0.70","Fund P: 8.0 versus 8.75","Both are equal"],"a":0,"w":"P: (16 &minus; 6) &divide; 20 = 0.50. Q: (13 &minus; 6) &divide; 10 = 0.70."},
   {"q":"What are the Treynor ratios?","o":["P 8.0; Q 8.75","P 0.50; Q 0.70","P 10; Q 7","P 12.8; Q 10.4"],"a":0,"w":"P: 10 &divide; 1.25 = 8.0. Q: 7 &divide; 0.8 = 8.75."},
   {"q":"What is Fund P's Jensen's alpha?","o":["2.5%","10%","1.0%","negative 2.5%"],"a":0,"w":"CAPM return = 6 + 1.25 &times; 6 = 13.5%. Alpha = 16 &minus; 13.5 = 2.5%."},
   {"q":"Neha is well diversified. As per the book, which ratio suits her best?","o":["Treynor ratio","Sharpe ratio","Standard deviation","Holding period return"],"a":0,"w":"The book says Treynor suits investors who have adequately diversified; Sharpe suits those who have not."},
  ]},
 {"id":"C24","title":"Raman's investment diary","text":"Raman bought shares for Rs 50,000 and sold them 2 years later for Rs 60,500, with no dividends. He keeps his savings in bank deposits too. When a stock he owns falls 30%, he refuses to sell until it returns to his purchase price, and he buys stocks mainly after seeing friends make money on them.",
  "qs":[
   {"q":"What is Raman's CAGR on the shares?","o":["10%","21%","10.5%","5%"],"a":0,"w":"(60,500 &divide; 50,000)<sup>1/2</sup> &minus; 1 = 1.21<sup>0.5</sup> &minus; 1 = 10%."},
   {"q":"What is his simple (holding period) return?","o":["21%","10%","10.5%","42%"],"a":0,"w":"60,500 &divide; 50,000 &minus; 1 = 21%. Simple annualised would be 10.5%; CAGR is 10%."},
   {"q":"Refusing to sell until the price returns to his purchase price shows:","o":["Anchoring","Herd mentality","Winner's curse","Gambler's fallacy"],"a":0,"w":"He anchors to his first price and ignores new information."},
   {"q":"Buying stocks after seeing friends make money shows:","o":["Herd mentality","Ownership bias","Projection bias","Confirmation bias"],"a":0,"w":"Following others in the belief they know more."},
  ]},
]

DATA = {"id":"ch12","short":"Ch12","title":"Chapter 12: Fundamentals of risk and return","cards":CARDS,"mcqs":MCQS,"cases":CASES}
