CARDS = [
 {"f":"Five departments of the Ministry of Finance (book)","b":"Economic Affairs, Expenditure, Revenue, Financial Services, Disinvestment."},
 {"f":"Which MoF department prepares the Union Budget?","b":"<b>Department of Economic Affairs</b> (also nodal for capital markets and fiscal policy)."},
 {"f":"Department of Revenue works through...","b":"Two boards: <b>CBDT</b> and <b>CBEC</b>."},
 {"f":"Ministry of Corporate Affairs","b":"Companies Act, ROC, Competition Act 2002 (replaced MRTP 1969); supervises ICAI, ICSI, ICWAI."},
 {"f":"RBI's six functions (book)","b":"Monetary authority; regulator of financial system; manager of forex (FEMA 1999); issuer of currency; developmental role; banker to government and banks."},
 {"f":"SEBI was established under...","b":"<b>Section 3</b> of the SEBI Act, 1992."},
 {"f":"SEBI and the Forward Markets Commission","b":"Merged on <b>28 September 2015</b>; SEBI now regulates commodity markets."},
 {"f":"IRDAI","b":"Insurance regulator under the IRDA Act, <b>1999</b>; supervises the Tariff Advisory Committee."},
 {"f":"PFRDA","b":"PFRDA Act <b>2013</b>; constituted October <b>2003</b>; promotes old age income security; runs the NPS."},
 {"f":"IBBI","b":"Under the IBC <b>2016</b>; regulates insolvency professionals; also the authority for <b>valuers</b>."},
 {"f":"SCRA 1956: SEBI's power over exchange rules","b":"SEBI can make or amend the <b>bye-laws</b> of recognised stock exchanges."},
 {"f":"SEBI Act sections 11(1) and 11(2)","b":"11(1): SEBI's duty to protect investors and develop and regulate the market. 11(2): the measures it may take."},
 {"f":"PIT and PFUTP regulations are made under...","b":"<b>Section 30</b> of the SEBI Act."},
 {"f":"Insider (PIT 2015)","b":"A connected person, or anyone with possession of or access to UPSI."},
 {"f":"Connected person: time window","b":"Associated with the company during the <b>six months</b> before the act."},
 {"f":"UPSI","b":"Unpublished price sensitive information: not generally available and likely to materially affect the price once public."},
 {"f":"Which rating change is excluded from UPSI?","b":"<b>ESG</b> rating changes."},
 {"f":"Regulation 3(1) of PIT","b":"No sharing of UPSI except for legitimate purposes, duties or legal obligations: <b>need to know</b>."},
 {"f":"Regulation 4 of PIT","b":"No trading while in possession of UPSI; such trades are presumed to be motivated by it."},
 {"f":"Initial disclosure of holdings (PIT)","b":"Within <b>seven days</b> of becoming KMP, director or promoter."},
 {"f":"Chinese wall","b":"Separates insider areas from public areas (sales, marketing, advice). Crossing the wall only on need to know, with the compliance officer informed."},
 {"f":"Analysts under the PIT code (book)","b":"Disclose holdings to the compliance officer; do not trade in a listed company for <b>30 days from preparing</b> a report on it."},
 {"f":"Fraud under PFUTP","b":"Any act, expression, omission or concealment to induce dealing. Gain or loss avoidance is irrelevant."},
 {"f":"Mis-selling (PFUTP)","b":"Selling by false statements, concealing facts or risks, or <b>not taking reasonable care</b> on suitability."},
 {"f":"SEBI's actions against an intermediary (PFUTP)","b":"Warning or censure; suspension; cancellation of registration."},
 {"f":"IOSCO report on analyst conflicts","b":"<b>September 2003</b>."},
 {"f":"RA Regulation 4","b":"A person outside India issuing research on Indian listed securities must have an <b>agreement with a registered RA</b>."},
 {"f":"Who is exempt from RA registration (reg 3)?","b":"IAs, credit rating agencies, AMCs or fund managers issuing research (complying with Chapter III); a registered RA's principal officer, associated persons and partners (complying with reg 7)."},
 {"f":"RA qualification (reg 7)","b":"Graduate degree or CFA Charter <b>plus</b> NISM certification; <b>or</b> NISM PG Program in Securities Market (Research Analysis)."},
 {"f":"Renewing NISM certification (reg 7(2))","b":"Before the existing one expires, or within <b>three years</b> of registration."},
 {"f":"RA deposit (reg 8)","b":"Marked as lien to the body recognised under reg 14 (RAASB); in liquid or overnight fund units or a scheduled bank deposit."},
 {"f":"Forms of certificate (reg 9)","b":"Form <b>B</b>: research analyst. Form <b>C</b>: part-time research analyst."},
 {"f":"Validity of RA registration (reg 10)","b":"Until <b>suspended or cancelled</b> by SEBI."},
 {"f":"Rejected RA application (reg 12)","b":"After a hearing; communicated within <b>30 days</b>; must stop acting as an RA."},
 {"f":"IBC: who forms the committee of creditors?","b":"<b>Financial</b> creditors. Operational creditors can start proceedings but cannot sit on it."},
 {"f":"IBC timeline","b":"<b>180 days</b> for resolution; extensions often granted. Liquidation is a last resort."},
 {"f":"IBC: what happens to the board?","b":"Considered dissolved once the IRP is appointed; management reports to the IRP."},
 {"f":"Eight items of the RA code of conduct","b":"Honesty and good faith; diligence; conflict of interest; no insider trading or front running; confidentiality; professional standard; compliance; senior management responsibility."},
 {"f":"Purpose of internal policies (reg 15)","b":"Address conflicts from dealing; promote objective research; <b>prevent use of research to manipulate the market</b>."},
 {"f":"Trading ban around a report (reg 16)","b":"<b>30 days before</b> and <b>5 days after</b> publication, for securities the analyst recommends or follows."},
 {"f":"Pre-IPO shares (reg 16)","b":"Analysts may not buy or receive an issuer's shares before its IPO if it is in the same business as companies they cover."},
 {"f":"Analyst compensation (reg 17)","b":"Not linked to specific IB, merchant banking or brokerage deals; approved annually by a board or committee without those divisions."},
 {"f":"Quiet periods after a managed issue (reg 18)","b":"<b>40 days</b> after IPO pricing; <b>10 days</b> after FPO pricing."},
 {"f":"IPO underwriter quiet period (reg 18(2))","b":"<b>25 days</b> from the date of the offering."},
 {"f":"Lock-up quiet period (reg 18(3))","b":"<b>15 days before</b> and <b>15 days after</b> the lock-up ends."},
 {"f":"Ownership disclosure threshold (reg 19)","b":"<b>1% or more</b>, at the end of the month before publication."},
 {"f":"Compensation disclosure period (reg 19)","b":"The <b>past twelve months</b>."},
 {"f":"New disclosure on technology (reg 19)","b":"Extent of use of <b>Artificial Intelligence</b> tools in research services."},
 {"f":"Price chart in a report (reg 20)","b":"If a rating or target has existed for 1 year or more: daily closing prices for that period or <b>3 years, whichever is shorter</b>."},
 {"f":"Distribution of reports (reg 22)","b":"Never selectively in advance to internal traders or favoured clients."},
 {"f":"Proxy advisers: timelines","b":"Review policies annually; alert clients of factual errors within <b>24 hours</b>; material revisions within <b>72 hours</b>."},
 {"f":"Change in control of an RA (reg 24)","b":"Needs SEBI's <b>prior approval</b>."},
 {"f":"Record keeping (reg 25)","b":"At least <b>five years</b>; annual compliance audit by an ICAI, ICSI or ICMAI member."},
 {"f":"Grievance redressal (reg 26B)","b":"Within <b>21 calendar days</b>."},
 {"f":"Segregation (reg 26C)","b":"An individual RA cannot provide distribution services; a client gets either research or distribution at group level."},
 {"f":"GSM","b":"Graded Surveillance Measures: for low market cap or net worth stocks whose <b>valuation</b> is not justified by fundamentals."},
 {"f":"ASM","b":"Additional Surveillance Measures: based on <b>price and volume</b> variation and top 25 clients' concentration. Margin 80%, then up to 100%."},
 {"f":"ASM does not apply to...","b":"Stocks already in GSM, trade-for-trade stocks, F&amp;O stocks, PSUs."},
 {"f":"Standard warning in RA ads","b":"\"Investment in securities market is subject to market risks. Read all the related documents carefully before investing.\" At least 10-point font, unchanged."},
 {"f":"Five things RA ads must not contain","b":"Past performance; superlatives like \"Best\" or \"No. 1\"; SEBI logo; assured or target returns; misleading testimonials."},
 {"f":"How long to keep a copy of each ad","b":"<b>Five years</b>."},
 {"f":"Investor Charter grievance route","b":"RA within 21 days; then SCORES 2.0 or RAASB (review by RAASB, then SEBI); then SMART ODR."},
 {"f":"Two investor don'ts in the Investor Charter","b":"Don't give the RA funds to invest; don't share trading or demat login credentials."},
 {"f":"CSCRF's five goals","b":"Anticipate, withstand, contain, recover, evolve."},
 {"f":"CSCRF for standalone RAs","b":"Excluded from CSCRF compliance submission; must give a SaaS declaration."},
]

MCQS = [
 {"id":"14.1","q":"Unhealthy practice in the securities markets includes which of the following?","o":["Insider trading","Disclosure","Transparency","Surveillance"],"a":0,"w":"Book sample question."},
 {"id":"14.2","q":"Which is the central bank in India with the responsibility of administering monetary policy?","o":["Reserve Bank of India","State Bank of India","Central Bank of India","All of the above"],"a":0,"w":"Book sample question."},
 {"id":"14.3","q":"Which authority was set up with the primary responsibility of promoting old age income security by establishing, developing and regulating pension funds?","o":["Pension Fund Regulatory and Development Authority","Association of Mutual Funds in India","Insurance Regulatory and Development Authority","Securities and Exchange Board of India"],"a":0,"w":"Book sample question."},
 {"id":"14.4","q":"______ is the purpose of having written internal policies and controls by a research analyst.","o":["Preventing the use of research reports to manipulate the securities market","Addressing only the actual conflict of interest arising from dealings in a company's securities","Promoting objective research that reflects the biased view of the research analyst","All of the above"],"a":0,"w":"Book sample question. Regulation 15 covers actual <b>or potential</b> conflicts and <b>unbiased</b> research, so the other two options misstate it."},
 {"id":"14.5","q":"Which department of the Ministry of Finance prepares the Union Budget?","o":["Department of Economic Affairs","Department of Expenditure","Department of Revenue","Department of Financial Services"],"a":0,"w":"It is also the nodal agency for fiscal policy and the capital market."},
 {"id":"14.6","q":"The Competition Act, 2002, which replaced the MRTP Act, 1969, is administered by the:","o":["Ministry of Corporate Affairs","Ministry of Finance","RBI","SEBI"],"a":0,"w":"MCA also administers the Companies Act."},
 {"id":"14.7","q":"The Foreign Exchange Management Act, 1999 is administered by:","o":["RBI","SEBI","Ministry of Corporate Affairs","IRDAI"],"a":0,"w":"As the manager of foreign exchange."},
 {"id":"14.8","q":"SEBI was established under:","o":["Section 3 of the SEBI Act, 1992","Section 30 of the SEBI Act, 1992","The SCRA, 1956","The Companies Act, 2013"],"a":0,"w":"Section 30 is the power under which PIT and PFUTP regulations are made."},
 {"id":"14.9","q":"SEBI merged with the Forward Markets Commission on:","o":["28 September 2015","1 April 1992","30 March 2026","28 September 2005"],"a":0,"w":"SEBI now regulates commodity markets."},
 {"id":"14.10","q":"Which regulator is also the authority for regulation and development of valuers in India?","o":["IBBI","PFRDA","IRDAI","RBI"],"a":0,"w":"IBBI was set up under the IBC, 2016."},
 {"id":"14.11","q":"Under the SCRA, 1956, who has the power to make or amend the bye-laws of recognised stock exchanges?","o":["SEBI","RBI","Ministry of Corporate Affairs","The exchanges alone"],"a":0,"w":"One of the SCRA powers listed in the book."},
 {"id":"14.12","q":"The SEBI (Prohibition of Insider Trading) Regulations, 2015 were made under:","o":["Section 30 of the SEBI Act, 1992","Section 3 of the SEBI Act, 1992","Section 230 of the Companies Act, 2013","The IBC, 2016"],"a":0,"w":"PFUTP 2003 was also made under section 30."},
 {"id":"14.13","q":"A person associated with a company in a way that gives access to UPSI is a 'connected person' if the association was within the ______ before the act.","o":["Six months","One month","Twelve months","Three years"],"a":0,"w":"As defined in the PIT regulations."},
 {"id":"14.14","q":"Which of the following is NOT listed as UPSI in the book?","o":["Change in ESG rating","Financial results","Dividends","Mergers and acquisitions"],"a":0,"w":"The list includes change in ratings \"other than ESG ratings\"."},
 {"id":"14.15","q":"Under Regulation 4 of the PIT Regulations, an insider who trades while in possession of UPSI:","o":["Is presumed to have been motivated by it, but may prove innocence in specified circumstances","Is always allowed to trade","Must only inform the stock exchange afterwards","Is exempt if the trade is small"],"a":0,"w":"Connected persons must establish that their trades did not violate the regulations."},
 {"id":"14.16","q":"A newly appointed director must disclose holdings in the company's securities within:","o":["Seven days","Thirty days","One day","Ninety days"],"a":0,"w":"Initial disclosure under the PIT regulations."},
 {"id":"14.17","q":"A 'Chinese wall' policy separates:","o":["Insider areas with confidential information from public areas such as sales and marketing","The board from shareholders","Equity research from debt research","Indian and foreign clients"],"a":0,"w":"Crossing the wall is allowed only on need to know, with the compliance officer informed."},
 {"id":"14.18","q":"Under the SEBI PFUTP Regulations, whether there is wrongful gain or avoidance of loss is:","o":["Inconsequential in deciding whether fraud has been committed","The main test of fraud","Required to prove fraud","Relevant only for intermediaries"],"a":0,"w":"Fraud includes any act, expression, omission or concealment to induce dealing."},
 {"id":"14.19","q":"Transactions between persons to create a false appearance of trading or to move the price are called:","o":["Circular transactions","Arbitrage","Hedging","Block deals"],"a":0,"w":"One of the deemed manipulative practices."},
 {"id":"14.20","q":"Which of the following is NOT an action SEBI can take against an intermediary under PFUTP, as per the book?","o":["Award a performance bonus","Issue a warning or censure","Suspend its registration","Cancel its registration"],"a":0,"w":"The book lists warning or censure, suspension and cancellation."},
 {"id":"14.21","q":"The IOSCO report on addressing analysts' conflicts of interest was released in:","o":["September 2003","January 2014","September 2015","March 1992"],"a":0,"w":"It set principles that informed the RA Regulations, 2014."},
 {"id":"14.22","q":"A person located outside India issuing research reports on securities listed in India must:","o":["Enter into an agreement with a SEBI-registered research analyst or research entity","Register with RBI","Get approval from the stock exchange only","Do nothing; foreign persons are exempt"],"a":0,"w":"Regulation 4 of the RA Regulations."},
 {"id":"14.23","q":"Which qualification meets Regulation 7 of the RA Regulations?","o":["A graduate degree plus relevant NISM certification","Class 12 plus five years' trading experience","Any NISM certificate without a degree","A stock broker's licence"],"a":0,"w":"Alternatively, NISM's Post Graduate Program in the Securities Market (Research Analysis), or a CFA Charter plus NISM certification."},
 {"id":"14.24","q":"A part-time research analyst is granted a certificate of registration in:","o":["Form C","Form B","Form A","Form D"],"a":0,"w":"Form B is for a research analyst."},
 {"id":"14.25","q":"A research analyst's certificate of registration is valid:","o":["Until it is suspended or cancelled by SEBI","For three years","For five years","For one year, renewable"],"a":0,"w":"Regulation 10. NISM certification, separately, must be renewed."},
 {"id":"14.26","q":"Under the IBC as described in the book, which creditors form the committee of creditors?","o":["Financial creditors","Operational creditors","Both financial and operational creditors","Shareholders"],"a":0,"w":"Operational creditors can initiate proceedings but cannot be part of the committee."},
 {"id":"14.27","q":"The IBC envisages that an insolvency proceeding should be completed within:","o":["180 days","90 days","365 days","30 days"],"a":0,"w":"Extensions have often been granted."},
 {"id":"14.28","q":"The code of conduct for research analysts is set out in the RA Regulations':","o":["Third Schedule","First Schedule","Chapter V","Regulation 4"],"a":0,"w":"It has eight items."},
 {"id":"14.29","q":"Which of the following is NOT part of the code of conduct for research analysts?","o":["Guaranteeing returns to clients","Honesty and good faith","Confidentiality of the report until made public","Responsibility of senior management"],"a":0,"w":"Assured returns are prohibited, not required."},
 {"id":"14.30","q":"An independent research analyst may not trade in a security they recommend within:","o":["30 days before and 5 days after publication of the report","5 days before and 30 days after publication","10 days before and 10 days after publication","40 days after publication"],"a":0,"w":"Regulation 16(2)."},
 {"id":"14.31","q":"Research analysts may not trade in securities they review:","o":["In a manner contrary to their own recommendation","At any time","Only during market hours","Without a demat account"],"a":0,"w":"Regulation 16(3)."},
 {"id":"14.32","q":"A research entity's analyst compensation must NOT be based on:","o":["Specific merchant banking, investment banking or brokerage transactions","The quality of research","Years of experience","Annual review by the board"],"a":0,"w":"Regulation 17. Pay is reviewed annually by a board or committee without those divisions."},
 {"id":"14.33","q":"An RA that managed a company's IPO cannot publish a report on it for ______ after the securities are priced.","o":["40 days","10 days","25 days","15 days"],"a":0,"w":"10 days for a further public offer; 25 days from the offering for an IPO underwriter."},
 {"id":"14.34","q":"A research entity participating as an underwriter of an IPO cannot publish a report on that issuer before ______ from the date of the offering.","o":["25 days","40 days","10 days","5 days"],"a":0,"w":"Regulation 18(2)."},
 {"id":"14.35","q":"Research analysts must NOT participate in:","o":["Sales pitches and deal road shows for investment banking business","Investor education activities","Meetings with company management for research","Writing reports"],"a":0,"w":"Regulation 18(4). Investor education, including pre-deal research, is allowed."},
 {"id":"14.36","q":"In a research report, an RA must disclose ownership of ______ or more of the subject company's securities.","o":["1%","5%","10%","0.5%"],"a":0,"w":"At the end of the month immediately before publication."},
 {"id":"14.37","q":"Disclosures about compensation received from the subject company cover the past:","o":["Twelve months","Three months","Three years","Five years"],"a":0,"w":"Regulation 19."},
 {"id":"14.38","q":"If a report has held a rating or target for at least one year, it must include a graph of daily closing prices for:","o":["The period assigned or three years, whichever is shorter","Ten years","The last month only","Since listing"],"a":0,"w":"Regulation 20(3)."},
 {"id":"14.39","q":"According to Regulation 22, a research report:","o":["Must not be made available selectively to internal traders or particular clients in advance","Must first go to the trading desk","Can be sold to the highest bidder first","Needs stock exchange approval"],"a":0,"w":"All entitled clients must receive it fairly."},
 {"id":"14.40","q":"Research analysts must preserve records for a minimum of:","o":["Five years","One year","Three years","Ten years"],"a":0,"w":"Regulation 25(2). Annual compliance audit is also required."},
 {"id":"14.41","q":"A research analyst must redress investor grievances within:","o":["21 calendar days","7 days","30 days","45 days"],"a":0,"w":"Regulation 26B; also in the Investor Charter."},
 {"id":"14.42","q":"Under Regulation 26C, an individual research analyst:","o":["Shall not provide distribution services","May provide distribution services to the same client","Must also register as a distributor","May distribute only mutual funds"],"a":0,"w":"Client-level segregation of research and distribution."},
 {"id":"14.43","q":"Graded Surveillance Measures (GSM) target securities:","o":["With low market cap or net worth whose valuation is not commensurate with fundamentals","With the highest trading volumes","In the derivatives segment","Of public sector units"],"a":0,"w":"ASM, by contrast, is based on price and volume variations."},
 {"id":"14.44","q":"Which factor does ASM consider?","o":["Share of volume traded by the top 25 clients","Dividend history","Promoter holding","Credit rating"],"a":0,"w":"Along with price variation and volume variation."},
 {"id":"14.45","q":"Once a stock is shortlisted under ASM, the margin is first raised to:","o":["80%","50%","100%","25%"],"a":0,"w":"It can later be raised to 100% with narrower price bands."},
 {"id":"14.46","q":"Which of the following may an RA's advertisement contain?","o":["Factual details of awards received from independent organisations","Past performance of the RA","The SEBI logo","The phrase \"No. 1 research analyst\""],"a":0,"w":"Superlatives, past performance and the SEBI logo are prohibited."},
 {"id":"14.47","q":"The standard warning in an RA's advertisement must be in a font size of at least:","o":["10","8","12","6"],"a":0,"w":"With no words added or removed."},
 {"id":"14.48","q":"Under the Investor Charter, if an investor is not satisfied after SCORES or RAASB, they can go to:","o":["SMART ODR for online conciliation or arbitration","The stock exchange trading desk","The RA's sales team","No further option"],"a":0,"w":"The RA must first try to redress within 21 days."},
 {"id":"14.49","q":"Which of the following is a 'don't' for investors in the Investor Charter?","o":["Sharing trading or demat login credentials with the RA","Checking the RA's SEBI registration number","Paying fees through banking channels","Reading disclosures in research reports"],"a":0,"w":"The other three are do's."},
 {"id":"14.50","q":"Which of the following is NOT one of the five CSCRF cyber resiliency goals?","o":["Ignore","Anticipate","Withstand","Recover"],"a":0,"w":"The five: anticipate, withstand, contain, recover, evolve."},
]

CASES = [
 {"id":"C27","title":"Priyanka's busy month","text":"Priyanka is an analyst at a research entity that also has an investment banking division. On 1 June she starts preparing a buy report on Zeta Ltd, published on 20 June. Her firm co-managed Zeta's IPO, priced on 5 June. Her bonus this year is proposed to include a share of the IPO fee. She owns 1.2% of Zeta.",
  "qs":[
   {"q":"Under the RA Regulations, when can Priyanka not trade in Zeta's shares?","o":["From 30 days before to 5 days after publication on 20 June","Only on 20 June","Only for 5 days before publication","She can trade at any time"],"a":0,"w":"Regulation 16(2): 30 days before and 5 days after publication."},
   {"q":"Since her firm co-managed the IPO priced on 5 June, the earliest it may publish without special approval is:","o":["40 days after 5 June","10 days after 5 June","25 days after 5 June","Immediately"],"a":0,"w":"40 days after pricing for an IPO; the 20 June date is too early unless legal or compliance staff give prior written approval."},
   {"q":"The proposed bonus is:","o":["Not allowed, as pay cannot be based on a specific investment banking transaction","Allowed if disclosed","Allowed if under 1% of the fee","Allowed after SEBI approval"],"a":0,"w":"Regulation 17(1)."},
   {"q":"What must the report disclose about her 1.2% holding?","o":["That she owns 1% or more of Zeta's securities","Nothing, as it is under 5%","Only her purchase price","Only if she sells"],"a":0,"w":"Regulation 19 requires disclosure of ownership of 1% or more."},
  ]},
 {"id":"C28","title":"A tip at the dinner table","text":"Arun's brother-in-law is the CFO of Omega Ltd. At dinner, he mentions that Omega will announce a merger next week and that the auditors resigned yesterday. Arun runs a small research firm and plans to send a 'buy Omega' message to all his clients the next morning, and to buy for himself first.",
  "qs":[
   {"q":"The merger news and the auditor's resignation are best described as:","o":["Unpublished price sensitive information","Public information","Mosaic analysis","Market commentary"],"a":0,"w":"Both are on the UPSI list: mergers, and resignation of a statutory auditor."},
   {"q":"As the CFO's relative who has received UPSI, Arun is:","o":["An insider, and must not trade while in possession of it","Free to trade, as he is not an employee","Allowed to trade if he informs the exchange","Only barred from selling"],"a":0,"w":"An insider includes anyone in possession of UPSI; relatives of connected persons are deemed connected."},
   {"q":"Buying for himself before sending the recommendation to clients would also breach the code of conduct on:","o":["Front running","Diligence only","Professional standard only","None, it is allowed"],"a":0,"w":"The code bars insider trading and front running, including of one's own report."},
   {"q":"Under which section of the SEBI Act were the PIT Regulations made?","o":["Section 30","Section 3","Section 11(2) only","Section 12"],"a":0,"w":"Both PIT 2015 and PFUTP 2003 were made under section 30."},
  ]},
 {"id":"C29","title":"Sunil's social media launch","text":"Sunil, an individual SEBI-registered research analyst, plans an Instagram campaign: \"India's No. 1 research analyst. 90% accuracy guaranteed. Last year our picks returned 45%. Free trial!\" (the trial needs a paid sign-up). He also wants to sell mutual funds to his research clients and to use the SEBI logo for credibility.",
  "qs":[
   {"q":"Which part of the ad is allowed?","o":["None of the quoted claims; each one breaks the advertisement code","\"No. 1 research analyst\"","\"90% accuracy guaranteed\"","\"Last year our picks returned 45%\""],"a":0,"w":"Superlatives, percentage accuracy or assured returns, past performance and \"free\" when not free are all prohibited."},
   {"q":"Can Sunil use the SEBI logo?","o":["No, advertisements shall not include the SEBI logo","Yes, as he is registered","Yes, with SEBI's email approval","Only on his website"],"a":0,"w":"The SEBI logo must not be used by IAs or RAs."},
   {"q":"Can Sunil sell mutual funds to his research clients?","o":["No, an individual RA shall not provide distribution services","Yes, if he discloses it","Yes, for clients who agree in writing","Only debt funds"],"a":0,"w":"Regulation 26C."},
   {"q":"What standard warning must the ad carry?","o":["\"Investment in securities market is subject to market risks. Read all the related documents carefully before investing.\"","\"Past performance guarantees future returns.\"","\"Approved by SEBI.\"","No warning is needed on social media"],"a":0,"w":"Unchanged, in at least 10-point font, and accurately translated if not in English."},
  ]},
]

DATA = {"id":"ch14","short":"Ch14","title":"Chapter 14: Legal and regulatory environment","cards":CARDS,"mcqs":MCQS,"cases":CASES}
