CARDS = [
 {"f":"What does technical analysis study?","b":"Statistics of trading activity, mainly <b>price and volume</b>."},
 {"f":"Five core assumptions of technical analysis","b":"Price discounts everything; price moves in trends; history repeats; predictable to a degree; volume confirms price."},
 {"f":"Technical versus fundamental: time horizon","b":"Technical: short and medium term trading. Fundamental: long-term investment."},
 {"f":"Line chart","b":"Closing prices joined as a line. Ignores open, high and low."},
 {"f":"Bar (OHLC) chart","b":"Shows open, high, low and close; detailed price action and volatility."},
 {"f":"Point and figure chart","b":"Price moves only; <b>ignores time and volume</b>. Breakouts, support and resistance; long-term trends."},
 {"f":"Renko chart","b":"Fixed price moves (<b>bricks</b>), not time intervals. Trend clarity; trailing stops."},
 {"f":"Heikin-Ashi chart","b":"Adjusted candles that <b>average</b> prices to cut noise; filters whipsaws."},
 {"f":"Who developed Dow Theory, and when?","b":"<b>Charles Dow</b>, editorials 1900 to 1902; formalised by William Hamilton and Robert Rhea."},
 {"f":"Six tenets of Dow Theory","b":"Market discounts everything; three trends; primary trends have three phases; indices must confirm; volume confirms; trends persist until a clear reversal."},
 {"f":"Three phases of a primary trend","b":"Accumulation (smart money enters), public participation, distribution (smart money exits)."},
 {"f":"Indices must confirm each other: example","b":"Nifty and Sensex should move in the same direction."},
 {"f":"Primary trend length","b":"Typically <b>one year or more</b>."},
 {"f":"Secondary trend: length and retracement","b":"About 3 weeks to 3 months; retraces <b>1/3 to 2/3</b> of the primary move."},
 {"f":"Correction versus rally","b":"Correction: a temporary fall in a bull market (often 10% to 20%). Rally: a short bounce in a bear market."},
 {"f":"Tertiary trend length","b":"Usually under <b>3 weeks</b> (some say up to 6)."},
 {"f":"Fibonacci retracement levels for secondary trends (book)","b":"<b>38.2%, 50%, 61.8%</b>."},
 {"f":"Hanging man","b":"Bearish; after an up move; small body; lower shadow at least twice the body. Needs a lower close next to confirm."},
 {"f":"Hammer","b":"Bullish; after a decline; same shape as a hanging man. Price must move up next to confirm."},
 {"f":"Bullish engulfing","b":"Small red then a large green whose body engulfs it. Stronger after <b>four or more</b> red candles."},
 {"f":"Bearish engulfing","b":"A red body engulfs the previous green body; more significant after an advance. Only real bodies count."},
 {"f":"Dark cloud cover","b":"Near the <b>top</b> of congestion: green candle, gap up, then red closing <b>below the midpoint</b> of the green."},
 {"f":"Piercing pattern","b":"<b>Two</b> candles near the <b>bottom</b> of congestion: red, then a gap-down green covering <b>at least half</b> the red."},
 {"f":"Morning star","b":"Three candles: tall red, small body, tall green. <b>Bullish</b>."},
 {"f":"Evening star","b":"Three candles: large green, small body above it, large red closing near the centre of the first body. <b>Bearish</b>."},
 {"f":"Congestion area","b":"A price range where the market trades repeatedly, often for several weeks, before breaking out."},
 {"f":"Symmetrical triangle","b":"Consolidation before a breakout either way. The book also calls it a wedge pattern."},
 {"f":"Ascending triangle","b":"<b>Higher lows</b> against flat resistance; bullish continuation in an uptrend."},
 {"f":"Descending triangle","b":"<b>Lower highs</b> against flat support; bearish continuation in a downtrend."},
 {"f":"Triangle price target","b":"Height at the thickest point, added to (or subtracted from) the breakout point."},
 {"f":"Flag versus pennant","b":"Both continuation patterns after a flagpole. Flag: small rectangle. Pennant: small triangle."},
 {"f":"Support versus resistance","b":"Support: demand, a floor. Resistance: supply, a ceiling."},
 {"f":"Role reversal","b":"Broken support often becomes resistance, and vice versa."},
 {"f":"What makes a support or resistance level stronger?","b":"More touches, higher volume, more time spent near it, more recent."},
 {"f":"Breakout versus false breakout","b":"Breakout: decisive move beyond the level with volume. False: brief breach that reverses, trapping traders."},
 {"f":"Trendline: minimum points","b":"At least <b>two</b>; three or more make it more reliable."},
 {"f":"Channel","b":"Two parallel trendlines. Ascending bullish, descending bearish, horizontal range-bound. Width reflects volatility."},
 {"f":"Are moving averages leading or lagging?","b":"<b>Lagging</b>, but useful for major trends."},
 {"f":"Book's EMA combination","b":"<b>13, 21 and 34</b> EMA (Fibonacci). Uptrend: price &gt; 13 &gt; 21 &gt; 34. Support near the 34 EMA in a bull market."},
 {"f":"Default MACD line","b":"Difference between the <b>26 EMA and the 12 EMA</b>. Slow line = <b>9 EMA</b> of the default line."},
 {"f":"MACD zero line","b":"Separates confirmed bull and bear markets, but a zero-line crossover <b>should not be used for trading</b>."},
 {"f":"MACD negative divergence","b":"Price makes a higher high but MACD a lower high: losing upward momentum."},
 {"f":"RSI range and levels","b":"0 to 100. Above <b>70</b> overbought; below <b>30</b> oversold."},
 {"f":"RSI in bull and bear markets","b":"Bull: rarely below 44 to 45. Bear: rarely above 50 to 55."},
 {"f":"RSI bullish divergence","b":"In an oversold market, stock makes a new low but RSI does not: an early buy signal."},
 {"f":"Where does RSI work best?","b":"In a <b>trading range</b>. In strong trends it can stay overbought or oversold for long."},
 {"f":"ADX","b":"Measures trend <b>strength, not direction</b>. 0 to 100; default 14 bars; below 25 weak."},
 {"f":"ADX buy signal","b":"+DMI crosses above &minus;DMI while ADX is rising."},
 {"f":"RSC","b":"Ratio chart versus a benchmark, normalised to 100. Above 100: outperforming. Use 5 to 6 years of data."},
 {"f":"OBV","b":"Running total: add volume on up-close days, subtract on down-close days. Read with its 20-period average."},
 {"f":"OBV divergence","b":"Volume often leads price; a higher price high without a higher OBV means buying pressure is fading."},
]

MCQS = [
 {"id":"15.1","q":"Which of the following is not a tenet of the Dow Theory?","o":["The market has four trends","The market discounts everything","The averages must confirm each other","A trend remains in effect until a clear reversal occurs"],"a":0,"w":"Book sample question. Dow Theory has three trends: primary, secondary, tertiary."},
 {"id":"15.2","q":"The Hanging Man candlestick pattern is unlikely to have which of the following features?","o":["It is a bullish reversal pattern that occurs after a down move","A small real body and a long lower shadow at least twice the size of the real body","A long lower shadow showing sellers were in control for part of the period","It is a bearish reversal pattern that occurs after an up move"],"a":0,"w":"Book sample question. The bullish version after a decline is the hammer."},
 {"id":"15.3","q":"The piercing pattern is most likely to have which of the following features?","o":["A two-candlestick pattern that occurs near the bottom of the congestion area","A three-candlestick pattern that occurs near the top of the congestion area","A two-candlestick pattern that occurs near the top of the congestion area","A three-candlestick pattern that occurs near the bottom of the congestion area"],"a":0,"w":"Book sample question. Dark cloud cover is the two-candle pattern near the top."},
 {"id":"15.4","q":"The default MACD line is most likely the difference between:","o":["The 26-period EMA and the 12-period EMA","The 12-period EMA and the 9-period EMA","The 26-period EMA and the 9-period EMA","The 26-period EMA and the 21-period EMA"],"a":0,"w":"Book sample question. The 9 EMA of the MACD line is the slow line."},
 {"id":"15.5","q":"Which of the following regarding the RSI is most likely to be true?","o":["When the stock makes a new low and RSI does not, it is called bullish divergence","When the stock makes a new low and RSI does not, it is called bearish divergence","RSI is a very good indicator in a strongly trending market","When the stock makes a new high and RSI does not, it is called bullish divergence"],"a":0,"w":"Book sample question. RSI performs well in a trading range, not in strong trends."},
 {"id":"15.6","q":"Which assumption is central to technical analysis?","o":["Price discounts everything","Prices always equal intrinsic value","Financial statements drive short-term prices","Volume is irrelevant"],"a":0,"w":"All known information is already reflected in the market price."},
 {"id":"15.7","q":"Which chart type ignores time and volume and focuses only on price movements?","o":["Point and figure","Line","Bar (OHLC)","Candlestick"],"a":0,"w":"Renko also uses fixed price bricks rather than time intervals."},
 {"id":"15.8","q":"A Heikin-Ashi chart:","o":["Uses adjusted candles that average price data to reduce noise","Shows only closing prices","Ignores price and shows only volume","Uses fixed price bricks"],"a":0,"w":"It helps traders stay in trends longer by filtering whipsaws. Fixed bricks describe Renko."},
 {"id":"15.9","q":"Dow Theory was organised into a formal theory, after Charles Dow's death, by:","o":["William Hamilton and Robert Rhea","Benjamin Graham and David Dodd","J. Welles Wilder and Gerald Appel","Peter Lynch and John Templeton"],"a":0,"w":"Dow wrote the editorials between 1900 and 1902."},
 {"id":"15.10","q":"In Dow Theory, the phase of a primary trend when smart money enters quietly is the:","o":["Accumulation phase","Public participation phase","Distribution phase","Correction phase"],"a":0,"w":"Smart money exits in the distribution phase."},
 {"id":"15.11","q":"According to Dow Theory, volume should:","o":["Increase in the direction of the primary trend","Decrease in the direction of the primary trend","Stay constant","Be ignored"],"a":0,"w":"Volume confirms the trend."},
 {"id":"15.12","q":"A primary trend typically lasts:","o":["One year or more","A few days","One to three weeks","Exactly six months"],"a":0,"w":"Secondary trends last weeks to months; tertiary trends days to weeks."},
 {"id":"15.13","q":"As per Dow Theory, a secondary trend typically retraces:","o":["One-third to two-thirds of the previous primary move","All of the previous move","Less than 5% of the previous move","Exactly 50% every time"],"a":0,"w":"It usually lasts about 3 weeks to 3 months."},
 {"id":"15.14","q":"A temporary decline within a bull market is called a ______, and a short bounce within a bear market a ______.","o":["Correction; rally","Rally; correction","Breakout; breakdown","Distribution; accumulation"],"a":0,"w":"Also called pullbacks and relief rallies."},
 {"id":"15.15","q":"Which Fibonacci retracement levels does the book list for identifying reversal zones in secondary trends?","o":["38.2%, 50% and 61.8%","10%, 20% and 30%","25%, 50% and 75%","33%, 66% and 100%"],"a":0,"w":"Elsewhere the book also lists 23.6% as a Fibonacci support level."},
 {"id":"15.16","q":"Tertiary trends typically last:","o":["Less than three weeks","More than one year","Three to six months","Exactly one month"],"a":0,"w":"Some definitions extend this to six weeks."},
 {"id":"15.17","q":"A hammer candlestick is:","o":["Bullish, appearing after a price decline","Bearish, appearing after an up move","A three-candle pattern","Always followed by a gap down"],"a":0,"w":"The price must start moving up after it to confirm."},
 {"id":"15.18","q":"In a hammer or hanging man, the lower shadow should be at least ______ the height of the real body.","o":["Twice","Half","Equal to","Ten times"],"a":0,"w":"With little or no upper shadow."},
 {"id":"15.19","q":"A bullish engulfing pattern is more likely to signal a reversal when preceded by:","o":["Four or more red candles","Four or more green candles","A gap up","A doji"],"a":0,"w":"Traders look at the preceding candles too."},
 {"id":"15.20","q":"In a bearish engulfing pattern, what must engulf the previous candle?","o":["The real body of the down candle","The upper shadow","The lower shadow","The volume bar"],"a":0,"w":"Only the real bodies matter."},
 {"id":"15.21","q":"In a dark cloud cover pattern, the bearish candle:","o":["Opens with a gap up and closes below the midpoint of the previous bullish candle","Opens with a gap down and closes above the previous high","Is the first of three candles","Appears near the bottom of a congestion area"],"a":0,"w":"It occurs near the top of the congestion area, in an uptrend."},
 {"id":"15.22","q":"In a piercing pattern, the green candle's body must cover at least ______ of the previous red candle.","o":["Half","One quarter","All","Two-thirds"],"a":0,"w":"After opening with a significant gap down."},
 {"id":"15.23","q":"The morning star is a:","o":["Three-candle bullish pattern","Three-candle bearish pattern","Two-candle bullish pattern","One-candle bearish pattern"],"a":0,"w":"The evening star is its bearish counterpart."},
 {"id":"15.24","q":"In an evening star, the third candle:","o":["Is a large red candle closing near the centre of the first candle's body","Is a large green candle","Is a doji","Opens with a gap up"],"a":0,"w":"It opens below the middle candle."},
 {"id":"15.25","q":"An ascending triangle forms with:","o":["Higher lows against the same resistance level","Lower highs against the same support level","Converging lines from both sides","A sharp fall followed by a rectangle"],"a":0,"w":"It is usually a bullish continuation pattern in an uptrend."},
 {"id":"15.26","q":"A descending triangle is formed when the market makes:","o":["Lower highs and lows at the same level","Higher lows and highs at the same level","Higher highs and higher lows","Equal highs and lows"],"a":0,"w":"It is usually a bearish continuation pattern in a downtrend."},
 {"id":"15.27","q":"An ascending triangle is 40 points high at its thickest point, and price breaks out at 500. The book's method gives a target of:","o":["540","460","520","580"],"a":0,"w":"Add the height at the thickest point to the breakout point: 500 + 40."},
 {"id":"15.28","q":"The sharp price rise before a flag or pennant is called the:","o":["Flagpole","Neckline","Handle","Wick"],"a":0,"w":"Traders enter long when price breaks above the flag or pennant's upper trendline."},
 {"id":"15.29","q":"A flag differs from a pennant in that the flag's consolidation takes the shape of a:","o":["Rectangle","Small triangle","Circle","Head and shoulders"],"a":0,"w":"A pennant is a small triangle; both are traded the same way."},
 {"id":"15.30","q":"Support is a price level where a downtrend is expected to pause because of a concentration of:","o":["Demand","Supply","Volatility","Short sellers"],"a":0,"w":"Resistance is a concentration of supply."},
 {"id":"15.31","q":"Once a support level is broken, it often:","o":["Becomes a new resistance level","Disappears for ever","Becomes stronger support","Turns into a moving average"],"a":0,"w":"Called role reversal."},
 {"id":"15.32","q":"Which of the following makes a support or resistance level stronger?","o":["More touches and higher volume at the level","Fewer touches","Less time spent near the level","An older, more distant level"],"a":0,"w":"Recent levels carry more weight."},
 {"id":"15.33","q":"A trendline needs at least ______ points, and ______ or more increase its reliability.","o":["Two; three","One; two","Three; five","Four; six"],"a":0,"w":"As stated in 15.8."},
 {"id":"15.34","q":"A channel with higher highs and higher lows is:","o":["An ascending channel, indicating bullishness","A descending channel, indicating bearishness","A horizontal channel","A symmetrical triangle"],"a":0,"w":"The channel's width reflects volatility."},
 {"id":"15.35","q":"Moving averages are:","o":["Lagging indicators useful for identifying major trends","Leading indicators that predict tops","Volume indicators","Measures of trend strength only"],"a":0,"w":"A rising MA means an uptrend, and vice versa."},
 {"id":"15.36","q":"In the book's EMA combination, an uptrend shows:","o":["Price &gt; 13 EMA &gt; 21 EMA &gt; 34 EMA","Price &lt; 13 EMA &lt; 21 EMA &lt; 34 EMA","13 EMA &lt; 21 EMA &lt; 34 EMA &lt; price","All EMAs flat"],"a":0,"w":"In a bull market price usually finds support around the 34 EMA."},
 {"id":"15.37","q":"The MACD slow line is generated from the:","o":["9 EMA of the default MACD line","26 EMA of price","12 EMA of price","50-day simple average"],"a":0,"w":"The default line is the 26 EMA minus the 12 EMA."},
 {"id":"15.38","q":"According to the book, a MACD crossover of the zero baseline:","o":["Should not be used for trading","Is the strongest buy signal","Always marks a trend reversal","Is the same as an RSI divergence"],"a":0,"w":"The zero line separates confirmed bull and bear markets."},
 {"id":"15.39","q":"Price makes a higher high but MACD makes a lower high. This suggests:","o":["The stock is losing upward momentum","The uptrend is accelerating","A buying climax has started","Nothing; MACD ignores momentum"],"a":0,"w":"MACD sometimes leads price by showing a shift in momentum."},
 {"id":"15.40","q":"A stock is usually considered overbought when RSI is:","o":["Above 70","Below 30","Exactly 50","Above 100"],"a":0,"w":"RSI ranges from 0 to 100."},
 {"id":"15.41","q":"In a bull market, the RSI rarely falls below:","o":["44 to 45","20","70","10"],"a":0,"w":"In a bear market it rarely rises above 50 to 55."},
 {"id":"15.42","q":"ADX measures:","o":["The strength of a trend, not its direction","The direction of a trend only","The volume of a stock","The relative performance against an index"],"a":0,"w":"It is plotted with +DMI and &minus;DMI, which show direction."},
 {"id":"15.43","q":"An ADX value below ______ is generally considered a weak trend or no trend.","o":["25","50","70","10"],"a":0,"w":"A rising ADX above 25 indicates a strong trend. The default setting is 14 bars."},
 {"id":"15.44","q":"When is an ADX-based buy signal given, as per the book?","o":["When +DMI crosses above &minus;DMI and ADX is rising","When ADX falls below 25","When &minus;DMI crosses above +DMI","Whenever ADX is above 100"],"a":0,"w":"Ignore crossovers when ADX is weak."},
 {"id":"15.45","q":"An RSC value above 100 indicates the stock is:","o":["Outperforming the benchmark","Underperforming the benchmark","Overbought","In a downtrend"],"a":0,"w":"RSC is normalised to 100 against a benchmark such as the Nifty 50."},
 {"id":"15.46","q":"On a day when the stock closes higher than the previous day, OBV:","o":["Adds that day's volume to the running total","Subtracts that day's volume","Stays unchanged","Resets to zero"],"a":0,"w":"On a lower close, the day's volume is subtracted."},
 {"id":"15.47","q":"A stock makes a higher high in price but OBV does not make a higher high. This suggests:","o":["Buying pressure is fading","A strong new uptrend","Rising buying pressure","Nothing; OBV ignores price"],"a":0,"w":"Volume often leads price and can warn of a reversal."},
]

CASES = [
 {"id":"C30","title":"Kabir reads the candles","text":"Kabir watches Alpha Ltd. After falling for six sessions, Alpha forms a candle with a small body near the day's high and a lower shadow three times the body. Months later, near the top of a long trading range, a strong green candle is followed by a candle that opens with a gap up but closes red, below the midpoint of the green candle.",
  "qs":[
   {"q":"The candle after the six-session fall is most likely a:","o":["Hammer","Hanging man","Evening star","Dark cloud cover"],"a":0,"w":"Small body, long lower shadow at least twice the body, after a decline."},
   {"q":"What does Kabir need before acting on it?","o":["Confirmation: price must start moving up next","Nothing; act immediately","A gap down the next day","RSI above 70"],"a":0,"w":"The book says trades are typically taken after the confirmation candle."},
   {"q":"The gap-up red candle closing below the green candle's midpoint, at the top of a range, is:","o":["Dark cloud cover","Piercing pattern","Morning star","Bullish engulfing"],"a":0,"w":"A bearish two-candle pattern near the top of a congestion area."},
   {"q":"If the same shape as the first candle had appeared after a strong rise, it would be a:","o":["Hanging man, a bearish warning","Hammer, bullish","Bullish engulfing","Morning star"],"a":0,"w":"The hanging man needs the next candle to close lower to confirm."},
  ]},
 {"id":"C31","title":"A triangle on Beta Ltd","text":"Beta Ltd is in an uptrend. For two months it has hit Rs 600 four times and fallen back, while each dip has stopped higher than the last: 540, 560, 575. Today it closed at Rs 612 on volume twice the average. The pattern's height at its thickest point is Rs 60.",
  "qs":[
   {"q":"What pattern has Beta formed?","o":["Ascending triangle","Descending triangle","Symmetrical triangle","Flag"],"a":0,"w":"Flat resistance at 600 with higher lows."},
   {"q":"What is the book's price target from the breakout at Rs 600?","o":["Rs 660","Rs 612","Rs 540","Rs 720"],"a":0,"w":"Height at the thickest point (60) added to the breakout point (600)."},
   {"q":"Why does the high volume matter?","o":["Volume confirms the breakout and adds credibility","Volume is irrelevant to breakouts","High volume always signals a false breakout","It means the stock is oversold"],"a":0,"w":"High volume during breakouts adds credibility to the move."},
   {"q":"If price later falls back to Rs 600, the old resistance would be expected to act as:","o":["Support","Resistance","A flagpole","A pivot for selling only"],"a":0,"w":"Role reversal: broken resistance often becomes support."},
  ]},
 {"id":"C32","title":"Indicators on Gamma Ltd","text":"Gamma Ltd's price made a new high this month, but its RSI peaked lower than last month and its MACD fast line made a lower high. RSI had been above 75 for six weeks. ADX is 18 and falling. Over five years, Gamma's RSC against the Nifty 50 has been below 100, but it just crossed above 100.",
  "qs":[
   {"q":"Price makes a new high while RSI does not. This is:","o":["Bearish divergence, an early sell signal","Bullish divergence","A confirmed uptrend","Irrelevant in an overbought market"],"a":0,"w":"In an overbought market, a new price high without a new RSI high is bearish divergence."},
   {"q":"What does the ADX reading of 18 and falling tell the analyst?","o":["The trend is weak; DMI crossovers should be avoided","The trend is strong and rising","The price will fall","The stock is oversold"],"a":0,"w":"ADX below 25 is weak or no trend; it says nothing about direction."},
   {"q":"The MACD lower high while price makes a higher high means:","o":["The stock is losing upward momentum","Momentum is accelerating","A buy signal","The zero line has been crossed"],"a":0,"w":"A negative divergence between price and MACD."},
   {"q":"What does the RSC crossing above 100 after a long time below suggest, as per the book?","o":["The stock may now be a good buy relative to the benchmark","The stock is overbought","The stock is underperforming","Nothing; RSC is only for commodities"],"a":0,"w":"The book: a stock becomes a good buy if RSC stays below 100 for long, then turns up and crosses 100. The signals conflict, so more confirmation is needed."},
  ]},
]

DATA = {"id":"ch15","short":"Ch15","title":"Chapter 15: Technical analysis","cards":CARDS,"mcqs":MCQS,"cases":CASES}
